### ISSUE TITLE
Plugin erroring out every couple of hours

### ISSUE THREAD

**Issue by Ben-Diehlci** [dgreif/ring#1007]
# Bug Report
[7/28/2022, 4:13:31 AM] [Ring] RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (/usr/local/lib/node_modules/homebridge-ring/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  code: 'ECONNRESET',
  timings: {
    start: 1658996011024,
    socket: 1658996011030,
    lookup: 1658996011034,
    connect: 1658996011035,
    secureConnect: 1658996011161,
    upload: 1658996011161,
    response: 1658996011303,
    end: 1658996011307,
    error: 1658996011310,
    abort: undefined,
    phases: {
      wait: 6,
      dns: 4,
      tcp: 1,
      tls: 126,
      request: 0,
      firstByte: 142,
      download: 4,
      total: 286
    }
  }
}
[7/28/2022, 4:13:31 AM] [Ring] Request to https://api.ring.com/devices/v1/locations failed:
[7/28/2022, 4:13:31 AM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:32)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:149:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[7/28/2022, 4:13:31 AM] [Ring] Error connecting to API
[7/28/2022, 4:13:31 AM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:32)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:149:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Describe the Bug
I have done this several times now, but every couple of hours or a little more the Ring Plugin for home bridge will say it can't connect. I then have to either uninstall restart the machine it is running on and install again. Or sometimes I am able to just re-enter my Ring username and password and then 2FA. Yes, if anyone is wondering I did follow the link in the error output to the Github token refresh page but anything on there did not resolve the issue. 

### To Reproduce
 To be honest I don't know, all I do is setup the plugin and then after a couple of hours I believe the plugin refreshes because of Rings policy on 2FA codes needing to be refreshed. When it refreshes it errors out and says it can't connect.  

### Homebridge Ring Config
{
    "bridge": {
        "name": "Homebridge B995",
        "username": "xxxxxxx",
        "port": 51888,
        "pin": "xxxxxxx",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "refreshToken": "xxxxxxxx",
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "nightModeBypassFor": "some",
            "platform": "Ring"
        }
    ]
}

```

### Environment
 - OS: MacOS 11.5.1 (Mac mini Intel Version)
 - Node.js: 16.16.0
 - NPM: 8.11.0
 - homebridge-ring: 11.0.7
 - homebridge: 4.50.0
 - Ring/Eero Wifi system - Mac mini Hardwired to it - Eero Secure Advanced Security and Add blocking turned off

**Comment by Ben-Diehlci** [comment]
So a small update to the issue, I have found that when it gives that error connect, and the plugin stops working. If I just restart the home bridge server a few times from the webpage it will reconnect without me needing to get a new refresh token or logging back in

**Comment by Ben-Diehlci** [comment]
[7/31/2022, 8:15:58 AM] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge B995) is running on port 51888.
[7/31/2022, 8:15:59 AM] [Ring] RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (/usr/local/lib/node_modules/homebridge-ring/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  code: 'ECONNRESET',
  timings: {
    start: 1659269758959,
    socket: 1659269758965,
    lookup: 1659269758969,
    connect: 1659269758970,
    secureConnect: 1659269759104,
    upload: 1659269759104,
    response: 1659269759211,
    end: 1659269759221,
    error: 1659269759226,
    abort: undefined,
    phases: {
      wait: 6,
      dns: 4,
      tcp: 1,
      tls: 134,
      request: 0,
      firstByte: 107,
      download: 10,
      total: 267
    }
  }
}
[7/31/2022, 8:15:59 AM] [Ring] Request to https://api.ring.com/devices/v1/locations failed:
[7/31/2022, 8:15:59 AM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:32)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:149:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[7/31/2022, 8:15:59 AM] [Ring] Error connecting to API
[7/31/2022, 8:15:59 AM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:32)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:149:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[7/31/2022, 8:16:08 AM] [Homebridge UI] Homebridge restart request received
[7/31/2022, 8:16:08 AM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[7/31/2022, 8:16:08 AM] [Homebridge UI] Sending SIGTERM to Homebridge
[7/31/2022, 8:16:08 AM] Got SIGTERM, shutting down Homebridge...
[7/31/2022, 8:16:13 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[7/31/2022, 8:16:18 AM] [HB Supervisor] Restarting Homebridge...
[7/31/2022, 8:16:18 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[7/31/2022, 8:16:18 AM] [HB Supervisor] Started Homebridge v1.5.0 with PID: 1412
[7/31/2022, 8:16:19 AM] Loaded config.json with 0 accessories and 2 platforms.
[7/31/2022, 8:16:19 AM] Loaded 11 cached accessories from cachedAccessories.
[7/31/2022, 8:16:19 AM] ---
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
[7/31/2022, 8:16:20 AM] Loaded plugin: homebridge-config-ui-x@4.50.0
[7/31/2022, 8:16:20 AM] Registering platform 'homebridge-config-ui-x.config'
[7/31/2022, 8:16:20 AM] ---
[7/31/2022, 8:16:20 AM] Loaded plugin: homebridge-ring@11.0.7
[7/31/2022, 8:16:20 AM] Registering platform 'homebridge-ring.Ring'
[7/31/2022, 8:16:20 AM] ---
[7/31/2022, 8:16:20 AM] Loading 2 platforms...
[7/31/2022, 8:16:20 AM] [Ring] Initializing Ring platform...
[7/31/2022, 8:16:20 AM] [Ring] Configuring cached accessory 7475f79f-8435-4c6b-ae79-49c15e059e4a Alarm
[7/31/2022, 8:16:20 AM] [Ring] Configuring cached accessory 988bb3be-dae8-450d-b256-69157924fa5d Ring Motion Sensor 27922
[7/31/2022, 8:16:20 AM] [Ring] Configuring cached accessory a12748fc-4772-4c19-8271-02b5de77cdaa Top of Stairs Window
[7/31/2022, 8:16:20 AM] [Ring] Configuring cached accessory 0a372029-2662-49a7-aeb8-c310f6462bb6 Front Door
[7/31/2022, 8:16:20 AM] [Ring] Configuring cached accessory f3e59491-cee2-4f0a-8d37-0426b22b56d7 Kitchen Window
[7/31/2022, 8:16:20 AM] [Ring] Configuring cached accessory 35698717-bd68-416c-a134-a251883d73bf Ring Motion Sensor 59673
[7/31/2022, 8:16:20 AM] [Ring] Configuring cached accessory be7c3b9f-b690-497c-8542-50ae334a0600 Garage/Basement Door
[7/31/2022, 8:16:20 AM] [Ring] Configuring cached accessory 06249bf9-035d-4443-8b30-3dc7b667dac5 Side Right Window
[7/31/2022, 8:16:20 AM] [Ring] Configuring cached accessory 986cf298-3e6b-48fc-85c0-a7b2dcbdd079 Left Half Window
[7/31/2022, 8:16:20 AM] [Ring] Configuring cached accessory 726abe3e-c8a4-448c-bc46-14e618af0f4d Side Left Window
[7/31/2022, 8:16:20 AM] [Ring] Configuring cached accessory 748df284-982a-4ccd-9c26-c5847fe9a390 Back Sliding Door
Setup Payload:
X-HM://0023WKZLYLI3V
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxx-xx-xxx│     
    └────────────┘     
                       
[7/31/2022, 8:16:20 AM] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge B995) is running on port 51888.
[7/31/2022, 8:16:21 AM] [Ring] RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (/usr/local/lib/node_modules/homebridge-ring/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  code: 'ECONNRESET',
  timings: {
    start: 1659269780953,
    socket: 1659269780959,
    lookup: 1659269780985,
    connect: 1659269780986,
    secureConnect: 1659269781152,
    upload: 1659269781153,
    response: 1659269781294,
    end: 1659269781298,
    error: 1659269781300,
    abort: undefined,
    phases: {
      wait: 6,
      dns: 26,
      tcp: 1,
      tls: 166,
      request: 1,
      firstByte: 141,
      download: 4,
      total: 347
    }
  }
}
[7/31/2022, 8:16:21 AM] [Ring] Request to https://api.ring.com/devices/v1/locations failed:
[7/31/2022, 8:16:21 AM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:32)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:149:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[7/31/2022, 8:16:21 AM] [Ring] Error connecting to API
[7/31/2022, 8:16:21 AM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:32)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:149:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[7/31/2022, 8:16:55 AM] [Homebridge UI] Homebridge restart request received
[7/31/2022, 8:16:55 AM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[7/31/2022, 8:16:55 AM] [Homebridge UI] Sending SIGTERM to Homebridge
[7/31/2022, 8:16:55 AM] Got SIGTERM, shutting down Homebridge...
[7/31/2022, 8:17:00 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[7/31/2022, 8:17:05 AM] [HB Supervisor] Restarting Homebridge...
[7/31/2022, 8:17:05 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[7/31/2022, 8:17:05 AM] [HB Supervisor] Started Homebridge v1.5.0 with PID: 1448
[7/31/2022, 8:17:05 AM] Loaded config.json with 0 accessories and 2 platforms.
[7/31/2022, 8:17:05 AM] Loaded 11 cached accessories from cachedAccessories.
[7/31/2022, 8:17:05 AM] ---
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
[7/31/2022, 8:17:06 AM] Loaded plugin: homebridge-config-ui-x@4.50.0
[7/31/2022, 8:17:06 AM] Registering platform 'homebridge-config-ui-x.config'
[7/31/2022, 8:17:06 AM] ---
[7/31/2022, 8:17:07 AM] Loaded plugin: homebridge-ring@11.0.7
[7/31/2022, 8:17:07 AM] Registering platform 'homebridge-ring.Ring'
[7/31/2022, 8:17:07 AM] ---
[7/31/2022, 8:17:07 AM] Loading 2 platforms...
[7/31/2022, 8:17:07 AM] [Ring] Initializing Ring platform...
[7/31/2022, 8:17:07 AM] [Ring] Configuring cached accessory 7475f79f-8435-4c6b-ae79-49c15e059e4a Alarm
[7/31/2022, 8:17:07 AM] [Ring] Configuring cached accessory 988bb3be-dae8-450d-b256-69157924fa5d Ring Motion Sensor 27922
[7/31/2022, 8:17:07 AM] [Ring] Configuring cached accessory a12748fc-4772-4c19-8271-02b5de77cdaa Top of Stairs Window
[7/31/2022, 8:17:07 AM] [Ring] Configuring cached accessory 0a372029-2662-49a7-aeb8-c310f6462bb6 Front Door
[7/31/2022, 8:17:07 AM] [Ring] Configuring cached accessory f3e59491-cee2-4f0a-8d37-0426b22b56d7 Kitchen Window
[7/31/2022, 8:17:07 AM] [Ring] Configuring cached accessory 35698717-bd68-416c-a134-a251883d73bf Ring Motion Sensor 59673
[7/31/2022, 8:17:07 AM] [Ring] Configuring cached accessory be7c3b9f-b690-497c-8542-50ae334a0600 Garage/Basement Door
[7/31/2022, 8:17:07 AM] [Ring] Configuring cached accessory 06249bf9-035d-4443-8b30-3dc7b667dac5 Side Right Window
[7/31/2022, 8:17:07 AM] [Ring] Configuring cached accessory 986cf298-3e6b-48fc-85c0-a7b2dcbdd079 Left Half Window
[7/31/2022, 8:17:07 AM] [Ring] Configuring cached accessory 726abe3e-c8a4-448c-bc46-14e618af0f4d Side Left Window
[7/31/2022, 8:17:07 AM] [Ring] Configuring cached accessory 748df284-982a-4ccd-9c26-c5847fe9a390 Back Sliding Door
Setup Payload:
X-HM://0023WKZLYLI3V
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxx-xx-xxx │     
    └────────────┘     
                       
[7/31/2022, 8:17:07 AM] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge B995) is running on port 51888.
[7/31/2022, 8:17:08 AM] [Ring] Found the following locations:
[7/31/2022, 8:17:08 AM] [Ring]   locationId: bc178941-0f07-4e0b-84e5-6361ebc3bac9 - Home
[7/31/2022, 8:17:08 AM] [Ring] Creating location socket.io connection - Home
[7/31/2022, 8:17:09 AM] [Ring] Ring connected to socket.io server
[7/31/2022, 8:17:09 AM] [Ring] Configuring 0 cameras and 22 devices for location "Home" - locationId: bc178941-0f07-4e0b-84e5-6361ebc3bac9
[7/31/2022, 8:17:09 AM] [Ring] Hidden accessory 66e3f365-1e99-4b78-bdef-a91c9995465a hub.kili Ring Alarm Pro
[7/31/2022, 8:17:09 AM] [Ring] Hidden accessory 416ea900-f75d-476e-ac53-a190101fe80e battery-manager.kibo Battery Manager
[7/31/2022, 8:17:09 AM] [Ring] Hidden accessory 1e17880c-64c6-4df6-9f50-c6c632ab0b85 adapter.sheila Sheila Adapter
[7/31/2022, 8:17:09 AM] [Ring] Hidden accessory 1cc57382-7a2d-4303-ac3a-e6c7ef04dd0f security-keypad Master Bedroom Keypad
[7/31/2022, 8:17:09 AM] [Ring] Hidden accessory d07a1f5c-4345-41f9-b02e-f6e518a3602f security-keypad 1st Floor Keypad
[7/31/2022, 8:17:09 AM] [Ring] Hidden accessory a590d0dd-004b-4e21-804b-e524a0c53e33 adapter.sidewalk Sidewalk Adapter

**Comment by dgreif** [comment]
This is a known issue when running on very old versions of MacOS.  If you are able to update to a newer OS, that should fix it.  Otherwise I suggest running homebridge on a raspberry pi

**Comment by Ben-Diehlci** [comment]
Awesome thank you, no idea why I didn't even think to update MacOS. Great plugin! Thank you for all the hard work.
