### ISSUE TITLE
Errors in Console

### ISSUE THREAD

**Issue by 400HPMustang** [dgreif/ring#106]
Getting the following errors in my console. I'm hoping it's something that can be fixed?

> [8/13/2019, 3:20:57 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...

> [8/13/2019, 8:34:33 AM] [Ring] sip INVITE request failed with status 480
[8/13/2019, 8:34:33 AM] [Ring] Failed to prepare stream for Front Door (0.221s)
[8/13/2019, 8:34:33 AM] [Ring] Error: sip INVITE request failed with status 480
    at sipClient.send (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip-session.js:154:28)
    at searching (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-ring\node_modules\sip\sip.js:1313:5)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-ring\node_modules\sip\sip.js:1294:41
    at Object.message (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-ring\node_modules\sip\sip.js:1113:7)
    at Object.signal (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-ring\node_modules\sip\sip.js:979:55)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-ring\node_modules\sip\sip.js:1341:24
    at onMessage (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-ring\node_modules\sip\sip.js:555:9)
    at content (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-ring\node_modules\sip\sip.js:490:7)
    at headers (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-ring\node_modules\sip\sip.js:477:9)
    at TLSSocket.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-ring\node_modules\sip\sip.js:501:27)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:265:13)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by dgreif** [comment]
This happens when you start/stop/start video feeds from one camera quickly.  `480` means `Temporarily Unavailable`.  This error comes from the Ring servers and is not something that the plugin controls.  We could probably add a retry after some set amount of time, but by then HomeKit would most likely show that the feed is not responding.

**Comment by dgreif** [comment]
I spent a ton of time trying to track down the `480` errors and unfortunately I can't crack it.  I think this is just something we are going to have to live with until Ring opens up docs for their API and makes it clear how to avoid pitfalls like this one (which will probably be never).  This only happens when you reconnect within a few seconds of disconnecting, so it shouldn't be too common

**Comment by adrianguanipa** [comment]
This plugin was working fine until recently, the cameras are operating normally, I can open them with no issues from the Ring's app, but from HomeKit is a different story. The Camera Snapshots are working in the Home app, but when opening the live feed on one of the cameras from any of my Apple devices I get a no response and this error in the log.

The only thing that changed recently in my network is that I switched from the first-gen Ring Alarm Base Station to the all-new Ring Alarm Pro which has the option to store the camera recordings locally. I did try turning this feature off temporarily to see if it would make a difference, but nothing, the error persists. All Apple devices are on the latest versions and have been rebooted. I did also removed the plugin from HomeBridge and installed and authenticated it again with the same result. HomeBridge and plugins are running the latest versions too.

I can't believe I'm the only one having this problem, can someone offer some help, please?

Thank you.

![image](https://user-images.githubusercontent.com/64798434/144454912-3f5f3e2c-f54b-4b34-8299-b52b59752f67.png)
