### ISSUE TITLE
Error connecting to API  - Ring device created but says failed to fetch name

### ISSUE THREAD

**Issue by terryllowery** [dgreif/ring#1084]
# Bug Report

### Describe the Bug
When trying to setup ring homebridge on Raspbian 64bit it fails to connect fully 

### To Reproduce
- Enter username and password
- Save generated token.
- View logs for the plugin

### Expected behavior
- Able to setup ring plugin in homebridge

### Screenshots/Logs
Error connecting to API
[10/27/2022, 1:36:35 PM] [homebridge-ring] Error: The Ring account which you used to generate a refresh token does not have any associated locations.  Please use an account that has access to at least one location.
    at RingApi.fetchRawLocations (/var/lib/homebridge/node_modules/homebridge-ring/lib/api/api.js:142:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RingApi.fetchAndBuildLocations (/var/lib/homebridge/node_modules/homebridge-ring/lib/api/api.js:152:30)
    at RingPlatform.connectToApi (/var/lib/homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:159:25)

in account.ring.com it shows the new device but it says "device name not found"

### Environment

 - OS: Rasbian 5.15.61-v8
 - Node.js: [v16.18.0]
 - homebridge-ring v11.3.1

**Comment by dgreif** [comment]
> The Ring account which you used to generate a refresh token does not have any associated locations. Please use an account that has access to at least one location.

Are you sure you are logging in with the right account? Does it have access to any devices?

**Comment by dgreif** [comment]
Closing due to inactivity
