### ISSUE TITLE
Cameras no longer show up in homekit

### ISSUE THREAD

**Issue by michaeltorbert** [dgreif/ring#1092]
# Bug Report

### Describe the Bug
Recently the video from my Ring cameras stopped working in Homekit. I removed all other plugins other than Homebridge UI and ensured Ring, Homebridge, and Node are up to date.
I refreshed my token, and in the log it appeared to work as there were no errors, and even detected motion (in the log), but the cameras were suddenly missing completely from Homekit itself. No blank screen or anything.
Restarted results in invalid refresh token error. So I refresh the token, restart with no errors but also no video in Homekit, then restart again and get the same error.

### To Reproduce
 - Refresh token
 - Restart Homebridge
 - See error in log and no video. 

### Expected behavior
Working video (or at least the placeholder in Homekit)

### Screenshots/Logs
```
[11/8/2022, 2:12:24 PM] Homebridge v1.5.1 (HAP v0.10.4) (Homebridge2) is running on port 51800.
[11/8/2022, 2:12:25 PM] [Ring] HTTPError: Response code 429 (Too Many Requests)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1667934744830,
    socket: 1667934744838,
    lookup: 1667934744843,
    connect: 1667934744858,
    secureConnect: 1667934744907,
    upload: 1667934744908,
    response: 1667934745007,
    end: 1667934745011,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 8,
      dns: 5,
      tcp: 15,
      tls: 49,
      request: 1,
      firstByte: 99,
      download: 4,
      total: 181
    }
  }
}
[11/8/2022, 2:12:25 PM] [Ring] Request to https://api.ring.com/devices/v1/locations failed:
[11/8/2022, 2:12:25 PM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:32)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:149:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/8/2022, 2:12:25 PM] [Ring] Error connecting to API
[11/8/2022, 2:12:25 PM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:32)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:149:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/8/2022, 2:12:46 PM] [Homebridge UI] [admin] Accessory layout changes saved.
[11/8/2022, 2:13:08 PM] [Homebridge UI] [admin] Accessory layout changes saved.

```

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: Mac OS
 - Node.js: 18.12.1
 - NPM: 8.19.3
 - homebridge-ring: 11.3.1
 - homebridge: 1.5.1

**Comment by smockle** [comment]
> I refreshed my token, and in the log it appeared to work as there were no errors

The logs included in your message above show several errors—
* `HTTPError: Response code 429 (Too Many Requests)`
* `Error: Refresh token is not valid.`
* `Error connecting to API`
—did you perhaps attach the wrong logs?

If not, I’d suggest shutting off Homebridge for an hour (to avoid any rate limits which may be causing the HTTP 429), then trying the steps in https://github.com/dgreif/ring/wiki/Refresh-Tokens again, making sure that you persist the new token value in your `config.json` (i.e. running `npx -p ring-client-api ring-auth-cli` alone is not sufficient).

**Comment by michaeltorbert** [comment]
@smockle I did not attach the wrong log. :)

I turned off Homebridge for a bit, refreshed the token (again), and it's now working.
