### ISSUE TITLE
[Streaming]: Streaming crashed bridge

### ISSUE THREAD

**Issue by Coder84619** [dgreif/ring#1115]
### Streaming Issue

Was in the Eve app and tried to view the Ring live stream. Ring bridge crashed.

### Proposed Solution

Unknown

### Environment

HOOBS

### What operating system are you on?

Mac

### Relevant log output

```shell
11/30/2022, 7:26:04 PMRing BridgeRingPreparing Live Stream for Front Door
11/30/2022, 7:26:05 PMRing BridgeRingStream Prepared for Front Door (0.61s)
11/30/2022, 7:26:05 PMRing BridgeRingActivating stream for Front Door (0.854s)
11/30/2022, 7:26:05 PMRing BridgeRingiceConnectionStateChange: completed
11/30/2022, 7:26:06 PMRing BridgeERRORError: Cannot get schema for 'EcDsaSignature' target
    at AsnSchemaStorage.get (/var/lib/hoobs/ringbridge/node_modules/@peculiar/webcrypto/node_modules/@peculiar/asn1-schema/build/cjs/schema.js:18:19)
    at Function.fromASN (/var/lib/hoobs/ringbridge/node_modules/@peculiar/webcrypto/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:26:52)
    at Function.parse (/var/lib/hoobs/ringbridge/node_modules/@peculiar/webcrypto/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:16:26)
    at Function.sign (/var/lib/hoobs/ringbridge/node_modules/@peculiar/webcrypto/build/webcrypto.js:1580:50)
    at EcdsaProvider.onSign (/var/lib/hoobs/ringbridge/node_modules/@peculiar/webcrypto/build/webcrypto.js:1740:25)
    at EcdsaProvider.sign (/var/lib/hoobs/ringbridge/node_modules/webcrypto-core/build/webcrypto-core.js:160:28)
    at SubtleCrypto.sign (/var/lib/hoobs/ringbridge/node_modules/webcrypto-core/build/webcrypto-core.js:1405:39)
    at Function.create (/var/lib/hoobs/ringbridge/node_modules/@peculiar/x509/build/x509.cjs.js:1812:47)
    at Function.CipherContext.createSelfSignedCertificateWithKey (/var/lib/hoobs/ringbridge/node_modules/dtls/src/context/cipher.ts:108:18)
    at RTCDtlsTransport.setupCertificate (/var/lib/hoobs/ringbridge/node_modules/werift/src/transport/dtls.ts:73:9)
    at ensureCert (/var/lib/hoobs/ringbridge/node_modules/werift/src/peerConnection.ts:1251:34)
    at RTCPeerConnection.ensureCerts (/var/lib/hoobs/ringbridge/node_modules/werift/src/peerConnection.ts:1259:7)
    at RTCPeerConnection.createAnswer (/var/lib/hoobs/ringbridge/node_modules/werift/src/peerConnection.ts:1264:5)
    at WeriftPeerConnection.createAnswer (/var/lib/hoobs/ringbridge/node_modules/ring-client-api/lib/streaming/peer-connection.js:117:24)
    at WebrtcConnection.handleMessage (/var/lib/hoobs/ringbridge/node_modules/ring-client-api/lib/streaming/webrtc-connection.js:29:32)
11/30/2022, 7:26:06 PMRing BridgeRingStopped Live Stream for Front Door
11/30/2022, 7:26:06 PMRing BridgeRingconnectionStateChange: closed
11/30/2022, 7:26:06 PMRing BridgeRingiceConnectionStateChange: closed
11/30/2022, 7:26:15 PMRing Bridge starting
11/30/2022, 7:26:21 PMRing BridgeLoaded plugin 'homebridge-ring'
11/30/2022, 7:26:21 PMRing BridgeLoading 1 platforms...
11/30/2022, 7:26:21 PMRing BridgeRingConfiguring cached accessory fb873293-8e74-4e3b-9422-75c1ac29e580 Front Door
11/30/2022, 7:26:21 PMRing BridgeRingConfiguring cached accessory 316b19af-787b-4a64-acbb-ab4342bce3e2 media room
11/30/2022, 7:26:21 PMRing BridgeRingConfiguring cached accessory 158a4695-401b-4ad8-bf94-98f9ede0ed9f Downstairs
11/30/2022, 7:26:21 PMRing BridgeBridge is running on port 51856.
11/30/2022, 7:26:22 PMRing BridgeRingFound the following locations:
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment]
This is a duplicate of #1108
