### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by athal7** [dgreif/ring#1133]
# Bug Report

### Describe the Bug
Fails to start

### To Reproduce
 - Start Homebridge

### Expected behavior
Start

### Screenshots/Logs
```
[05/01/2023, 04:38:28] ====================
[05/01/2023, 04:38:28] ERROR LOADING PLUGIN homebridge-ring:
[05/01/2023, 04:38:29] Error: Cannot find module '../toDate/index.js'
Require stack:
- /usr/local/lib/node_modules/homebridge-ring/node_modules/date-fns/addMonths/index.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/date-fns/addYears/index.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/werift/lib/dtls/src/context/cipher.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/werift/lib/webrtc/src/utils.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/werift/lib/webrtc/src/media/rtpReceiver.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/werift/lib/webrtc/src/media/router.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/werift/lib/webrtc/src/peerConnection.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/werift/lib/webrtc/src/index.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/peer-connection.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/streaming-connection-base.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/webrtc-connection.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/ring-camera.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/location.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/api.js
- /usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/index.js
- /usr/local/lib/node_modules/homebridge-ring/lib/ring-platform.js
- /usr/local/lib/node_modules/homebridge-ring/lib/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/date-fns/addMonths/index.js:10:38)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/date-fns/addYears/index.js:10:38)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/dtls/src/context/cipher.ts:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
[05/01/2023, 04:38:29] ====================
```

### Additional context
n/a

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```json
        {
            "refreshToken": "xxx",
            "unbridgeCameras": true,
            "hideDoorbellSwitch": true,
            "hideInHomeDoorbellSwitch": false,
            "avoidSnapshotBatteryDrain": false,
            "disableLogs": false,
            "platform": "Ring",
            "_bridge": {
                "username": "xxx",
                "port": xxx
            }
        }

```

### Environment
 - OS: Raspbian
 - Node.js: 18.12.1
 - NPM: 8.9.12
 - homebridge-ring: 11.7.1
 - homebridge: 1.6.0
 - hoobs: n/a
 - homebridge-config-ui: 4.50.2

**Comment by dgreif** [comment]
it looks like the `date-fns` package may not have been installed correctly. I'd try removing the plugin and then reinstalling

**Comment by athal7** [comment]
I just tried that, no change though. Same error

**Comment by athal7** [comment]
All set after reinstalling date-fns directly
