### ISSUE TITLE
[Streaming]: negotiate codecs failed and caused homebridge to reboot everytime checking live stream

### ISSUE THREAD

**Issue by ethanyc216** [dgreif/ring#1145]
### Streaming Issue

I am facing the following issue with one of my camera after upgraded to homebridge-ring v11.7.1. tried restart raspberry pi and homebridge still wont work. 

Other two cameras working fine. Only this ring stick up cam battery (3rd gen) is not working. other two cameras are doorbell and indoor cam. The live stream is watchable from ring app. 

live streaming was working before until i upgraded. but rigtht now even if i downgraded still facing the same problem. not sure where caused the issue.

I checked wiki on streaming troubleshooting but didnt found related issue

### Environment

Homebridge

### What operating system are you on?

Linux

### Relevant log output

```shell
[27/01/2023, 05:26:37] [Ring] No snapshot cached for Garage
[27/01/2023, 05:26:37] [Ring] Loading new snapshot into cache for Garage
[27/01/2023, 05:26:38] [Ring] No snapshot cached for Front Door
[27/01/2023, 05:26:38] [Ring] Loading new snapshot into cache for Front Door
[27/01/2023, 05:26:39] [Ring] Preparing Live Stream for Garage
[27/01/2023, 05:26:40] [Ring] Stream Prepared for Garage (0.644s)
[27/01/2023, 05:26:40] [Ring] Activating stream for Garage (0.762s)
[27/01/2023, 05:26:40] [Ring] WebSocket connected for Garage
[27/01/2023, 05:26:40] Error: negotiate codecs failed.
    at RTCPeerConnection.setRemoteRTP (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:1022:13)
    at /var/lib/homebridge/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:890:14
    at Array.map (<anonymous>)
    at RTCPeerConnection.setRemoteDescription (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:855:38)
    at WeriftPeerConnection.createAnswer (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/peer-connection.js:116:23)
    at WebrtcConnection.handleMessage (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/webrtc-connection.js:29:46)
    at /var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/streaming-connection-base.js:38:25
    at doInnerSub (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
    at outerNext (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
[27/01/2023, 05:26:40] Got SIGTERM, shutting down Homebridge...
[27/01/2023, 05:26:40] [Ring] Stopped Live Stream for Garage
[27/01/2023, 05:26:40] [Ring] connectionStateChange: closed
[27/01/2023, 05:26:40] [Ring] iceConnectionStateChange: closed
[27/01/2023, 05:26:40] [Ring] Call ended before answered
[27/01/2023, 05:26:40] [Ring] Snapshot cached for Front Door (2.947s)
[27/01/2023, 05:26:41] [Ring] Snapshot cached for Garage (3.083s)
[27/01/2023, 05:26:45] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[27/01/2023, 05:26:50] [HB Supervisor] Restarting Homebridge...
```

### Honesty Time

- [x] I swear this is worth your time!

**Comment by wmcdade** [comment]
I have exactly the same issue that started yesterday when I rebuilt by Homebridge installation from fresh. I have tried the plugin with 1.4, 1.5.1,1.6 and 2.0 (versions of Homebridge), and all result in the same behavior.

Log details:
```
[28/01/2023, 21:16:29] [Ring] Preparing Live Stream for Front Door
[28/01/2023, 21:16:29] [Ring] Stream Prepared for Front Door (0.412s)
[28/01/2023, 21:16:29] [Ring] Activating stream for Front Door (0.518s)
[28/01/2023, 21:16:29] Error: negotiate codecs failed.
    at RTCPeerConnection.setRemoteRTP (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:1022:13)
    at /var/lib/homebridge/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:890:14
    at Array.map (<anonymous>)
    at RTCPeerConnection.setRemoteDescription (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:855:38)
    at WeriftPeerConnection.createAnswer (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/peer-connection.js:116:23)
    at WebrtcConnection.handleMessage (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/webrtc-connection.js:29:46)
    at /var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/streaming-connection-base.js:38:25
    at doInnerSub (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
    at outerNext (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
[28/01/2023, 21:16:29] Got SIGTERM, shutting down Homebridge...
[28/01/2023, 21:16:29] [Ring] Stopped Live Stream for Front Door
[28/01/2023, 21:16:29] [Ring] connectionStateChange: closed
[28/01/2023, 21:16:29] [Ring] iceConnectionStateChange: closed
[28/01/2023, 21:16:29] Got SIGTERM, shutting down child bridge process...
[28/01/2023, 21:16:34] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[28/01/2023, 21:16:39] [HB Supervisor] Restarting Homebridge...
[28/01/2023, 21:16:39] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[28/01/2023, 21:16:39] [HB Supervisor] Started Homebridge v1.6.0 with PID: 5634
```

**Comment by ethanyc216** [comment]
> 

Do all your cameras cause the crash or just one of them? I have three, but only one of them caused the crash. Not sure why...

**Comment by lokipowers** [comment]
I have the same issue running on Mac. Was running fine, charged up the doorbell, and now I get a negotiate codecs failed error. The motion detection still works, the snapshots still work, just the live feed is dead. 

Worth pointing out, the live feed is also dead on their MacOS App, but working fine on their iOS App.

Homebridge: 1.6.0
Homebridge Ring: 11.7.1
MacOS: Ventura 13.1

```
[2/2/2023, 6:09:32 AM] [homebridge-ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/5141212c-5ff2-4dd1-bb93-12665bc4f89f.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...
[2/2/2023, 8:54:15 AM] [homebridge-ring] Preparing Live Stream for Front Door
[2/2/2023, 8:54:16 AM] [homebridge-ring] Stream Prepared for Front Door (0.672s)

/Users/{user}/.nvm/versions/node/v18.5.0/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:1022
      throw new Error("negotiate codecs failed.");
            ^
Error: negotiate codecs failed.
    at RTCPeerConnection.setRemoteRTP (/Users/{user}/.nvm/versions/node/v18.5.0/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:1022:13)
    at /Users/{user}/.nvm/versions/node/v18.5.0/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:890:14
    at Array.map (<anonymous>)
    at RTCPeerConnection.setRemoteDescription (/Users/{user}/.nvm/versions/node/v18.5.0/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:855:38)
    at WeriftPeerConnection.createAnswer (/Users/{user}/.nvm/versions/node/v18.5.0/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/peer-connection.js:116:23)
    at WebrtcConnection.handleMessage (/Users/{user}/.nvm/versions/node/v18.5.0/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/webrtc-connection.js:29:46)
    at /Users/{user}/.nvm/versions/node/v18.5.0/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/streaming-connection-base.js:38:25
    at doInnerSub (/Users/{user}/.nvm/versions/node/v18.5.0/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
    at outerNext (/Users/{user}/.nvm/versions/node/v18.5.0/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (/Users/stevejudge/.nvm/versions/node/v18.5.0/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
[2/2/2023, 8:54:17 AM] [homebridge-ring] Child bridge process ended
[2/2/2023, 8:54:17 AM] [homebridge-ring] Process Ended. Code: 1, Signal: null
[2/2/2023, 8:54:24 AM] [homebridge-ring] Restarting Process...
```

**Comment by wmcdade** [comment]
> @wmcdade Do all your cameras cause the crash or just one of them? I have three, but only one of them caused the crash. Not sure why...

I'm sorry but I only have one Ring camera, which is the [Ring Video Doorbell (2nd Gen)](https://www.amazon.co.uk/dp/B0931VRJT5), all others are Logitec Circle View's which do not need Homebridge for obvious reasons.

**Comment by wmcdade** [comment]
> > @wmcdade Do all your cameras cause the crash or just one of them? I have three, but only one of them caused the crash. Not sure why...
> 
> I have a battery-operated Ring doorbell that is not causing this issue, and a wired floodlight cam plus which is causing this same crash.

@dquins that's odd, my Ring is battery-powered and has the problem. Maybe this has been caused by a FW update? My Doorbell camera FW is "cam-1.15.12100" and the status is "Up-to-date" with the last health check (today) 02/02/2023 03:11 PM.

**Comment by wmcdade** [comment]
This may be a clue to the cause. When I just attempted to view the live stream in Google Chrome I was initially knocked back with a message stating the browser does not support the codec. Then when I tried again from a different place, I received the below warning.
![image](https://user-images.githubusercontent.com/76210503/216364207-7f9e0e73-09c6-4ed1-89a0-d5059b97093c.png)

**Comment by dgreif** [comment]
@wmcdade can you try turning on legacy mode and then streaming via homebridge?

**Comment by wmcdade** [comment]
@dgreif Yes, that fixed the issue for me.

**Comment by dgreif** [comment]
HEVC encoding is definitely something new that Ring must have just introduced. For anyone else running into this issue, you will need to enable Legacy Mode for any camera which isn't steaming properly. I don't know if it's worth adding transcoding from HEVC to h264, which is what would be needed to make this work without legacy mode. Transcoding is very CPU intensive, so something we've tried to avoid at all costs with this plugin until now

**Comment by dquins** [comment]
> @dgreif Yes, that fixed the issue for me. My Ring doorbell is working in HomeKit once more.

sorry for the basic question, but I cannot seem to enable legacy mode via the app.  I've read a lot that says that the app must serve up the option to enable legacy mode when it senses a device that cannot view the stream, but I am not encountering that scenario in iOS.  
Can I ask you how you enabled legacy mode?

**Comment by wmcdade** [comment]
> > @dgreif Yes, that fixed the issue for me. My Ring doorbell is working in HomeKit once more.
> 
> sorry for the basic question, but I cannot seem to enable legacy mode via the app. I've read a lot that says that the app must serve up the option to enable legacy mode when it senses a device that cannot view the stream, but I am not encountering that scenario in iOS. Can I ask you how you enabled legacy mode?

@dquins, I am also unable to find a way to turn on Legacy Mode from the iOS app. I enabled mine via ring.com as it gave me the option when I opened the live view from the browser.

**Comment by ethanyc216** [comment]
My battery cam firmware version is "cam-1.15.12100" and has the issue. Legacy mode works fine for me. My other two cams (doorbell and indoor cam) has different FW version and don't have problems.  

Ring webpage seems the only way to enable the legacy mode. And there is no option for you to turn HEVC mode back on unless you send a rest request yourself. 

The request to turn on HEVC is 
```
PATCH
https://account.ring.com/api/devices/v1/devices/{deviceId}/settings

Headers: 
csrf-token: xxxxxx

Payload:
{"video_settings":{"hevc_enabled":true}}
```

use `{"video_settings":{"hevc_enabled":false}}` to turn on legacy mode.

**Comment by nickustinov** [comment]
Same here. Spotlight Cam Plus stopped working, no way to enable Legacy video mode in the app.

**Comment by niqbert89** [comment]
Same here. I cant find the Legacy Mode Option.

**Comment by valerioceniccola** [comment]
same, can't see cameras anymore.
