### ISSUE TITLE
Snapshots not refreshing even when doorbell is online, connected, & hardwired

### ISSUE THREAD

**Issue by taherkaraki** [dgreif/ring#115]
@dgreif could be please check my log:

[8/25/2019, 12:28:51 AM] [Ring] Configuring 1 cameras and 1 devices for location "<hidden>" - locationId: <hidden>
[8/25/2019, 12:28:51 AM] [Ring] Adding new accessory doorbell Front Door
[8/25/2019, 12:28:51 AM] Front Door is running on port 52100.
[8/25/2019, 12:28:51 AM] Please add [Front Door] manually in Home app. Setup Code: <hidden>
[8/25/2019, 12:30:54 AM] [Ring] Snapshot for Front Door Requested
[8/25/2019, 12:32:01 AM] [Ring] Snapshot failed to refresh after 60 attempts
[8/25/2019, 12:32:01 AM] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/806918
[8/25/2019, 12:32:01 AM] [Ring] Failed to retrieve snapshot for Front Door (67.55s).  The camera currently reports that is it online
[8/25/2019, 12:32:01 AM] [Ring] Error: Not found with response: no snapshot

    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:218:27)
    at Generator.throw (<anonymous>:null:null)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by dgreif** [comment]
@taherkaraki I appreciate the logs!  That means that Ring does not currently have a snapshot for that camera, so we can't pull it down.  Is it doing that consistently, or just once in a while?  Do snapshots for that camera work in the Ring app?

**Comment by taherkaraki** [comment]
@dgreif yes consistently recently. However, sometimes it retrieves a snapshot after 60 tries, but the only thing I see is a black image while I see the following logs:

[8/25/2019, 4:30:31 PM] [Ring] Snapshot for Front Door Requested
[8/25/2019, 4:31:39 PM] [Ring] Snapshot failed to refresh after 60 attempts
[8/25/2019, 4:31:40 PM] [Ring] Snapshot for Front Door Received (69.876s)

**Comment by dgreif** [comment]
Do snapshots for that camera work in the Ring app? What mode is it?

**Comment by taherkaraki** [comment]
I do not know how to check for snapshots because the app by default only shows a snapshot of the last activity (motion/ring). How to find what mode? Went over all of the settings in the app and there's no mention for mode.
