### ISSUE TITLE
cannot access ring doorbell from homebridge

### ISSUE THREAD

**Issue by tellice** [dgreif/ring#1156]
When i try to access my ring doorbell from homekit, homebridge comes up with this error

2/13/2023, 10:12:06 AM] [Ring] Stream Prepared for Front Door (1.899s)
[2/13/2023, 10:12:06 AM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/432c3128-5d05-4370-b72f-d8fc749ccb34.  getaddrinfo ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[2/13/2023, 10:12:07 AM] [Ring] Activating stream for Front Door (2.395s)
[2/13/2023, 10:12:08 AM] Error: negotiate codecs failed.
    at RTCPeerConnection.setRemoteRTP (/usr/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:1022:13)
    at /usr/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:890:14
    at Array.map (<anonymous>)
    at RTCPeerConnection.setRemoteDescription (/usr/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:855:38)
    at WeriftPeerConnection.createAnswer (/usr/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/peer-connection.js:116:23)
    at WebrtcConnection.handleMessage (/usr/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/webrtc-connection.js:29:46)
    at /usr/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/streaming-connection-base.js:38:25
    at doInnerSub (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
    at outerNext (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)

I am running node.js version 18.14.0

**Comment by emogu2** [comment]
I've been having the same issue and found your ticket in my search for an answer. Then I found that it was resolved in a previous ticket here:
https://github.com/dgreif/ring/issues/1145#issuecomment-1413962463

Go to Ring.com, attempt to view live feed. Click on it even if it says unable to view. That will present the option to switch to legacy mode. Do so and your feed will reappear in HK.

**Comment by dgreif** [comment]
See https://github.com/dgreif/ring/wiki/Streaming-Legacy-Mode
