### ISSUE TITLE
ring intercom error endless loop error - Error: listen EADDRINUSE: address already in use :::48784

### ISSUE THREAD

**Issue by fate8383** [dgreif/ring#1157]
[2/13/2023, 12:25:46 PM] [homebridge-ring] Loaded homebridge-ring v11.7.1 child bridge successfully
[2/13/2023, 12:25:46 PM] Got SIGTERM, shutting down child bridge process...
[2/13/2023, 12:25:46 PM] Loaded 0 cached accessories from cachedAccessories.0E99E22686E5.
Error: listen EADDRINUSE: address already in use :::48784
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at EventedHTTPServer.listen (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)

I have tried , remove cache, re-add, unchild rechild bridge, several reboots and no success. Ring app works fine. Any advice? Thanks

**Comment by fate8383** [comment]
never mind port 48784 got stuck for some reason, killed it and restarted it is working.
