### ISSUE TITLE
Request to location API failed (503) and Homebridge crashed entirely

### ISSUE THREAD

**Issue by tbaur** [dgreif/ring#1160]
# Bug Report

### Describe the Bug

API call hit a 502, and it crashed homebridge entirely. Logs below. This happened 3-4 times last night. Clearly the Ring API was having issues, but it shouldn't crash homebridge all together. 

### Screenshots/Logs

[2/17/2023, 4:54:44 AM] [Ring] Request to https://app.ring.com/api/v1/mode/location/0950258e-XXX failed with status 502. Response body: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

[2/17/2023, 4:54:44 AM] HTTPError: Response code 502 (Bad Gateway)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2/17/2023, 4:54:44 AM] Got SIGTERM, shutting down Homebridge...

### Environment

OSX and current versions of node, npm, homebridge, and homebridge-ring

**Comment by tbaur** [comment]
More of the similar crashing.

[2/23/2023, 7:27:27 AM] [Ring] Request to https://app.ring.com/api/v1/mode/location/0950258e-XXX failed with status 400. Response body: envproxy unknown host

[2/23/2023, 7:27:27 AM] HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2/23/2023, 7:27:27 AM] Got SIGTERM, shutting down Homebridge...

**Comment by tbaur** [comment]
And then after repeat issues, repeat crashing and homebridge restarts, the API then rejects and causes even further spinning.

[2/23/2023, 7:27:40 AM] [Ring] HTTPError: Response code 429 (Too Many Requests)

**Comment by dgreif** [comment]
@tbaur sorry I didn't see this issue sooner. The 429 is a rate-limiting response, likely because you restarted many times which caused a large number of requests. Are you still experiencing the 502 and 400 errors which originally caused you trouble?

**Comment by dgreif** [comment]
Thanks for the update. In your second comment, I see `envproxy unknown host` as the error. Do you have some sort of Proxy or VPN set up? I haven't seen errors like this before, so I'm guessing it's something related to your network

**Comment by dgreif** [comment]
@tbaur just to make sure I understand your intent with this issue - is the ring plugin _generally_ working for you, but occasionally crashing or crash-looping if an unexpected server error is encountered?

**Comment by tsightler** [comment]
So this has been out here a long time and it doesn't seem to happen often enough to be critical, but I had a little time tonight and did some digging and I think this is simply because the `request()` function in rest-client.ts looks for specific status codes and retries them, but for any return codes that are not explicitly handled (401, 404, 504) it throws the error.  However, as far as I can see, none of the callers of `request()` actually attempt to catch an error, so the unhandled promise rejection leads to the node process exiting since that is the default for modern node versions since v16 (maybe v15 during development).  Prior to that, this probably was less of an issue.

I don't see this in ring-mqtt because I use `process.on('unhandledRejection')` to catch such events for a few other "normal" cases such as invalid token and make the error messages slight cleaner by not outputting the stack trace because otherwise users open cases about them, but it also has the advantage of catching these crashing cases.  However, I don't think this approach is appropriate for a library.

I believe the proper fix is to implement error handling via a catch for every call to request, since it is certainly possible that any given request my actually fail.  However, in ring-client-api alone there are around 70 callers to `request()` and certainly some library users will call `request()` directly for some things as well (I have at least a half-dozen such calls in ring-mqtt)

I don't have time to try to fix all of these right now so that leaves a few alternatives.  The working assumption of most of the code has always been that a call to `request()` will retry automatically until it succeeds so my lean is to handle all 500 level responses the same as a gateway timeout.

This still leaves 400 errors, in general I don't think "Bad requests" errors should be retried, so I'm not sure what to do with them.  Maybe just log but don't throw the error?  I don't think that behavior would be worse than what the code did prior in Node v14 and earlier when it generated promise rejections but the node process didn't exit. 

Fully open to other suggestions, is there some cleaner option I am missing?

**Comment by tsightler** [comment]
To be fair, it's more because Node changed behavior that it crashes now, since they made unhandled rejections exit by default sometime after NodeJS 14.  You can always run node with `--unhandled-rejections=warn` which was the behavior when the code was originally written many years ago.

Not that I'm disagreeing with you, but I just don't have time to go hunt down every consumer and put in proper error handling.  I'm currently testing out just not throwing an error, but just logging it.

**Comment by dgreif** [comment]
Haven't had any new reports of this in a few years, so I'm going to close it under the assumption that it's not happening much or at all now
