### ISSUE TITLE
One Ring Camera will not work.

### ISSUE THREAD

**Issue by rcfortugno** [dgreif/ring#1165]
# Bug Report

### Describe the Bug
One of my cameras isn't working, even after uninstalling and re-installing the plugin.
All the other ones work

### To Reproduce
 - Start Homebridge
 - Attempt to open camera
 - see error

### Expected behavior
Camera should open and view, instead it says 'No Response, This camera is not responding' A clear and concise description of what you expected to happen.

### Screenshots/Logs
Error: negotiate codecs failed.
    at RTCPeerConnection.setRemoteRTP (/usr/local/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:1022:13)
    at /usr/local/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:890:14
    at Array.map (<anonymous>)
    at RTCPeerConnection.setRemoteDescription (/usr/local/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:855:38)
    at WeriftPeerConnection.createAnswer (/usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/peer-connection.js:116:23)
    at WebrtcConnection.handleMessage (/usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/webrtc-connection.js:29:46)
    at /usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/streaming-connection-base.js:38:25
    at doInnerSub (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
    at outerNext (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by tsightler** [comment]
> Error: negotiate codecs failed.

This is a duplicate of https://github.com/dgreif/ring/issues/1145. Ring is doing crazy things randomly enabled HEVC/H.265 and causing all kinds of problems (See Ring community forum). You will need to enable Legacy Video mode.

Note that it breaks all kinds of things, not just projects dependent on ring-client-api, see this Ring community thread:  https://community.ring.com/t/hevc-not-supported-not-true-as-other-are-showing-camera-preview-but-one-is-not/181441
