### ISSUE TITLE
[Streaming]: 

### ISSUE THREAD

**Issue by mikeelmasry** [dgreif/ring#1168]
### Streaming Issue

I have been using Homebridge and dgreif Ring plug in for over close to 2 years now. Big thank you to the developer of this plugin!

Recently, I noticed that the Ring cameras (Stick Up Cam and Video Doorbell Pro) cause Homebridge to crash whenever I try to view the live stream through Homekit. The thumbnail preview seems to work fine and all the cameras work fine in the Ring app. My guess is something changed on Ring's end in regards to codecs that is causing the problem.

### Proposed Solution

According to the logs, it would appear to be a codec error. My only guess is that something changed on Ring's end that is causing the issue. It has worked great for a long time and I haven't done anything with Homebridge that I could think of that could have caused the issue. I honestly am just guessing as to what could be the issue. I'm not smart enough to figure this out which is why I am asking for help.

### Environment

Homebridge

### What operating system are you on?

Linux

### Relevant log output

```shell
[2/21/2023, 10:17:16 AM] [Ring] Preparing Live Stream for Front Yard
[2/21/2023, 10:17:17 AM] [Ring] Stream Prepared for Front Yard (0.605s)
[2/21/2023, 10:17:17 AM] [Ring] Activating stream for Front Yard (0.848s)
[2/21/2023, 10:17:19 AM] Error: negotiate codecs failed.
    at RTCPeerConnection.setRemoteRTP (/usr/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:1022:13)
    at /usr/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:890:14
    at Array.map (<anonymous>)
    at RTCPeerConnection.setRemoteDescription (/usr/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:855:38)
    at WeriftPeerConnection.createAnswer (/usr/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/peer-connection.js:116:23)
    at WebrtcConnection.handleMessage (/usr/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/webrtc-connection.js:29:46)
    at /usr/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/streaming-connection-base.js:38:25
    at doInnerSub (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
    at outerNext (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
[2/21/2023, 10:17:19 AM] Got SIGTERM, shutting down Homebridge...
[2/21/2023, 10:17:19 AM] [Harmony Hub] INFO - shutdown
[2/21/2023, 10:17:19 AM] [Ring] Stopped Live Stream for Front Yard
[2/21/2023, 10:17:19 AM] [Ring] connectionStateChange: closed
[2/21/2023, 10:17:19 AM] [Ring] iceConnectionStateChange: closed
[2/21/2023, 10:17:24 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[2/21/2023, 10:17:29 AM] [HB Supervisor] Restarting Homebridge...
[2/21/2023, 10:17:29 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[2/21/2023, 10:17:29 AM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 429
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by smockle** [comment]
This could be another duplicate of https://github.com/dgreif/ring/issues/1145.

@mikeelmasry Do you get the same error if you [enable Legacy Mode](https://support.ring.com/hc/en-us/articles/4417503172116-Legacy-Video-Mode-)?

**Comment by mikeelmasry** [comment]
Changing to Legacy Mode worked! 
Thank you! 🙏🏽
