### ISSUE TITLE
Install of homebridge-ring v11.8.0 (2023-06-09) fails using Homebridge UI

### ISSUE THREAD

**Issue by Dernheart** [dgreif/ring#1237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Installation fails

### To Reproduce

Removed privous version of homebridge-ring
rebooted home-bridge Raspberry Pi
Install homebridge-ring v11.8.0

### Expected behavior

homebridge-ring installed

### Relevant log output

```shell
1806 timing reifyNode:node_modules/homebridge-ring/node_modules/web-encoding Completed in 42165ms
1807 timing reifyNode:node_modules/homebridge-ring Completed in 42404ms
1808 timing reifyNode:node_modules/homebridge-ring/node_modules/@peculiar/asn1-x509 Completed in 43113ms
1809 timing reifyNode:node_modules/homebridge-ring/node_modules/msw Completed in 43108ms
1810 timing reifyNode:node_modules/homebridge-ring/node_modules/@babel/runtime Completed in 43992ms
1811 timing reifyNode:node_modules/homebridge-ring/node_modules/axios Completed in 44095ms
1812 timing reifyNode:node_modules/homebridge-ring/node_modules/tsyringe Completed in 44279ms
1813 timing reifyNode:node_modules/homebridge-ring/node_modules/@mswjs/interceptors Completed in 44495ms
1814 timing reifyNode:node_modules/homebridge-ring/node_modules/protobufjs Completed in 44728ms
1815 timing reifyNode:node_modules/homebridge-ring/node_modules/binary-data Completed in 50522ms
1816 timing reifyNode:node_modules/homebridge-ring/node_modules/@types/node Completed in 51240ms
1817 timing reifyNode:node_modules/homebridge-ring/node_modules/graphql Completed in 52359ms
1818 timing reifyNode:node_modules/homebridge-ring/node_modules/@zxing/text-encoding Completed in 60469ms
1819 timing reifyNode:node_modules/homebridge-ring/node_modules/werift Completed in 61362ms
1820 timing reifyNode:node_modules/homebridge-ring/node_modules/lodash Completed in 61445ms
1821 timing reifyNode:node_modules/homebridge-ring/node_modules/rxjs Completed in 79914ms
1822 timing reifyNode:node_modules/homebridge-ring/node_modules/date-fns Completed in 264860ms
1823 timing reify:unpack Completed in 264921ms
1824 timing reify:rollback:createSparse Completed in 15184ms
1825 timing reify:rollback:retireShallow Completed in 0ms
1826 timing command:install Completed in 346465ms
1827 verbose stack Error: process terminated
1827 verbose stack     at /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:199:39
1827 verbose stack     at process.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:53:5)
1827 verbose stack     at process.emit (node:events:525:35)
1828 verbose cwd /var/lib/homebridge
1829 verbose Linux 5.15.76-v7+
1830 verbose node v18.12.1
1831 verbose npm  v8.19.2
1832 error process terminated
1833 error signal SIGTERM
1834 verbose exit 1
1835 timing npm Completed in 348092ms
1836 verbose unfinished npm timer reify 1686291805912
1837 verbose code 1
1838 error A complete log of this run can be found in:
1838 error     /home/pi/.npm/_logs/2023-06-09T06_23_24_293Z-debug-0.log
```

### Homebridge Ring Config

```shell
no homebridge-ring config present
```

### OS

Homebridge Raspbian v1.0.39 - Raspberry Pi 2 Model B Rev 1.1

### Node.js Version

v18.12.1

### NPM Version

v8.19.2

### Homebridge/HOOBs Version

v1.6.1

### Homebridge Ring Plugin Version

v11.8.0

### Operating System

Raspbian

**Comment by Dernheart** [comment]
same happened from command line "npm i -g --unsafe-perm homebridge-ring"

**Comment by Dernheart** [comment]
Successfully installed via command line "hb-service add homebridge-ring"

**Comment by dgreif** [comment]
Sounds like you got it fixed 🎉. These errors are usually something related to your local npm cache, and not something I can fix from the package so I don't think there is anything else to be done here.
