### ISSUE TITLE
“Ring Login Failed” Error

### ISSUE THREAD

**Issue by Bank1824** [dgreif/ring#1256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I’m getting this error when I attempt to generate a new refresh token in the homebridge config ui: "TypeError: Cannot use 'in' operator to search for 'error' in <html>
<head><title>406 Not Acceptable</title></head>
<body>
<center><h1>406 Not Acceptable</h1></center>
<hr><center>openresty</center>
</body>
</html>

    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:186:119)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"

I also can’t log in the Scrypted plugin, or the app. I’ve called Ring support and they haven’t been able to help me with the login issue. Hope you can provide some insight.

### To Reproduce

Attempt to refresh token by logging in to ring account. Error is produced.

### Expected behavior

Login is successful and I’m able to put in my 2FA code to generate a new refresh token.

### Relevant log output

```shell
[07/07/2023, 00:58:17] [homebridge-ring] HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1688709497071,
    socket: 1688709497094,
    lookup: 1688709497100,
    connect: 1688709497114,
    secureConnect: 1688709497148,
    upload: 1688709497150,
    response: 1688709497223,
    end: 1688709497234,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 23,
      dns: 6,
      tcp: 14,
      tls: 34,
      request: 2,
      firstByte: 73,
      download: 11,
      total: 163
    }
  }
}
[07/07/2023, 00:58:17] [homebridge-ring] Request to https://api.ring.com/devices/v1/locations failed:
[07/07/2023, 00:58:17] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:140:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:143:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:184:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[07/07/2023, 00:58:17] [homebridge-ring] Error connecting to API
[07/07/2023, 00:58:17] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:140:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:143:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:184:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[07/07/2023, 01:00:18] [Homebridge UI] [homebridge-ring] TypeError: Cannot use 'in' operator to search for 'error' in <html>
<head><title>406 Not Acceptable</title></head>
<body>
<center><h1>406 Not Acceptable</h1></center>
<hr><center>openresty</center>
</body>
</html>

    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:186:119)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Homebridge Ring Config

```shell
{
    "refreshToken": "eyJydCI6ImV5SmhiR2NpT2lKU1V6STFOaUlzSW1wcmRTSTZJaTl2WVhWMGFDOXBiblJsY201aGJDOXFkMnR6SWl3aWEybGtJam9pTkdSak9EUXlaR0lpTENKMGVYQWlPaUpLVjFRaWZRLmV5SnBZWFFpT2pFMk9EZzJOVFkyTVRRc0ltbHpjeUk2SWxKcGJtZFBZWFYwYUZObGNuWnBZMlV0Y0hKdlpEcDFjeTFsWVhOMExURTZOREJrWm1ReU1Ua2lMQ0p5WldaeVpYTm9YMk5wWkNJNkluSnBibWRmYjJabWFXTnBZV3hmWVc1a2NtOXBaQ0lzSW5KbFpuSmxjMmhmYzJOdmNHVnpJanBiSW1Oc2FXVnVkQ0pkTENKeVpXWnlaWE5vWDNWelpYSmZhV1FpT2pFeE1qYzJNekkyTENKeWJtUWlPaUppVTE5SmNuWnBVak53SWl3aWMyVnpjMmx2Ymw5cFpDSTZJakEwWXpRMU56QmlMVFZoWkRZdE5EYzBaaTFpTUdaakxUUmlNVFE0TURSbE56QmhZaUlzSW5SNWNHVWlPaUp5WldaeVpYTm9MWFJ2YTJWdUluMC5xVHN5U1ZpbWVsc1hvRDB4ck05eklLTzZhcDA0N0pUYUhrOERWekZKZEk3SlZ2T0M5MEpINW93NGk2QlJFbDdQS25TaG1nZkZ4b21zM2w4N3J5Y2VDeWkxQlo4ZWFOQ3dadUpVazVLT3NobHBYNks0RUQ0QnVrTWZ0aHF1SkEtcWQ3aUJPck5BZ0NWMXF2eGpIelRHb3o2MHg1X3Z1cTdWQkt2ZXoyYXdha2ExZ0UzbXVENGpEdm9Bbnkwc09VUG9zREc2SGd6MERMNHBDcldKQmJWeDZWZ29hY3ozTDdWbFdpdFlOM1RWM1pZeFJSVzlKTW5abHNXc0RSV21wYllsM2czXzd6T2pRS0lvUFFwckpXdzlsVlFYd3Q1QVMyZ2VtUWZJXzdrcmd5R3FPUXhtMWh2Rzl3WnFEUkxTYnM1V3VocEV5ekZUczBWS1poLXk2cURZU1EiLCJoaWQiOiI3NGZmZmJhMi0yZDVmLTU5ZGMtYmIwMC04NDk5OThiMjU1YTkiLCJwbmMiOnsiZ2NtIjp7InRva2VuIjoiZnc3OEdMc3NHLUk6QVBBOTFiSEJMN185TFJoOWJrd3FVNlVhUE5ZMTlhOEJqTXJTbG1qOUtjY2JMZmkwWXZ4cnhkMThLM1VwVVpDQ3B1QVJWcG1CR3A3dUY2QnZHVXVhVU56SGZpX1VrOURlbmsxcVdYUmVZRERGcnZiVklkOWJxeGVHRW5fN2VsZGRYbkJUYjFvVW9UeWgiLCJhbmRyb2lkSWQiOiI1MDY0NTc0NDU1NzM1NTU3NjYwIiwic2VjdXJpdHlUb2tlbiI6IjEwMjc4MjM3NzY0ODAwNDU4MjYiLCJhcHBJZCI6IndwOnJlY2VpdmVyLnB1c2guY29tIzE2NjcyODE2LTNiOTgtNDMzYy04YmM3LTQ5ZTcxNDJhYTBhMiJ9LCJrZXlzIjp7InByaXZhdGVLZXkiOiJwcUZqeWliX1J3V01MckttZGNTdXlPeUtQVUJ6RE1VeWFBcjFhYkJja2tZIiwicHVibGljS2V5IjoiQkVjMHp1RU9UNnR6Yl9LUG90dEl3WDVkaW1QaGJaZWF3dlFsVmkxNEplWEI1MkVVanEtYXZGWWI5TWxsaUM5bl9CVmpxdE9HRWdnUzZwM3JoVUVJb1Y0IiwiYXV0aFNlY3JldCI6Ik5XYjJxV1VZcDF4ZjBhQXk1WGZOV3cifSwiZmNtIjp7InRva2VuIjoiZk9mNm5HcTlJTWs6QVBBOTFiRnVnOE9TQVA2TUhrcnhiZTZfcm9xLXFCVV9mZERQT1JQWUZEaFJ5WFp2MFBaNWY3VUxNTmtNM3paY2ZzaFI5THhVSGNCMlN6dWEweGZLQUkzZmJRWHZwbWZvVlRVVVJPd2ZpZU13SkR5dUFUbzdHNXg3NktFZElmUkxudmE2WDBGNFg1Yk0iLCJwdXNoU2V0IjoiZTlUbjY4WUVDT006QVBBOTFiRlF0M0JlSGhoelpaZW1VbFFxQ2lESnduRkVfeV9xS2JzbXVudHFLMzJRZklPYkRGN3JGVTBGY0ZRTHNNaTk3cDVQeklEUHFkY2pyMl9SbWdrVVZRSXJNU0VjV1VHOTNmY0VOQWlrZDE3VzVNa1l3NTRsb1ZkdHh0U1J0Unp0bGFzaUI4Z2oifX19",
    "unbridgeCameras": true,
    "alarmOnEntryDelay": false,
    "showPanicButtons": false,
    "cameraStatusPollingSeconds": 1,
    "_bridge": {
        "username": "0E:16:19:93:B6:DF",
        "port": 53017
    },
    "platform": "Ring"
}
```

### OS

Raspbian GNU/Linux Bullseye

### Node.js Version

v18.16.1

### NPM Version

Not sure

### Homebridge/HOOBs Version

V1.6.1

### Homebridge Ring Plugin Version

v11.8.0

### Operating System

Docker

**Comment by Bank1824** [comment]
This issue resolved itself.
