### ISSUE TITLE
Refresh token is not valid

### ISSUE THREAD

**Issue by kerimc** [dgreif/ring#1273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

s6-rc: info: service legacy-services successfully started
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/rest-client.js:93:15)
    at RingRestClient.<anonymous> (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/rest-client.js:97:36)
    at Generator.next (<anonymous>)
    at /ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/rest-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/rest-client.js:4:12)
    at RingRestClient.getAuth (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/rest-client.js:96:16)
    at RingRestClient.<anonymous> (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/rest-client.js:121:33)
    at Generator.throw (<anonymous>)
    at rejected (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/rest-client.js:6:65)

Node.js v18.17.0

### Expected behavior

Wan to integrate https://github.com/jeroenterheerdt/ring-hassio, 
follwed the refresh token generation as described here:
https://github.com/dgreif/ring/wiki/Refresh-Tokens 

### OS

Linux

### Node.js Version

 Node.js v18.17.0

### NPM Version

v7.5.2

### ring-client-api

9.19.0

### Operating System

Debian

**Comment by tsightler** [comment]
ring-hassio is a long dead project based on ring-client-api from ages ago that is unlikely to work at this point.  Ring API changes over time and dead projects will eventually not work.  I noticed you forked it and just replaced ring-client-api with new major version, but doesn't appear that you made other required changes.

I'm not sure what you are trying to do, but if you are looking for live streaming, I might humbly suggest my own project, ring-mqtt as a replacement for ring-hassio.

**Comment by msl2424** [comment]
I have a related issue. This evening I suddenly got the following message in my logs:

`2023-07-28T23:21:55.317Z ring-mqtt Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
2023-07-28T23:22:24.312Z ring-mqtt Websocket for location id e952c570-d654-4e0c-9f91-debf3303c150 is disconnected`

To resolve, I attempted to re-authenticate via the Web UI, but I received this message in the logs:

`2023-07-29T00:08:44.234Z ring-mqtt Username/Password was accepted, waiting for 2FA code to be entered.
2023-07-29T00:08:48.652Z ring-mqtt Saving updated refresh token to state file
2023-07-29T00:08:48.653Z ring-mqtt A new refresh token was generated, attempting to re-establish connection to Ring API
2023-07-29T00:08:49.731Z ring-mqtt Successfully saved updated state file: /data/ring-state.json
2023-07-29T00:08:50.656Z ring-mqtt Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
2023-07-29T00:08:50.657Z ring-mqtt Failed to re-establish connection to Ring API using generated refresh token`

The wiki listed at https://github.com/dgreif/ring/wiki/Refresh-Tokens was not super helpful to me. Any guidance on what to do to re-connect Ring-MQTT with Video Streaming? All my entities are offline.

**Comment by tsightler** [comment]
@msl2424 Not every problem is related to this project, I'd always suggest, when you experience a sudden issue, that you check Ring status first (well, after giving them 30 mintues or so to acknowledge that the issue exist).  Ring is currently experiencing a major system outage:

https://status.ring.com/

Well, technically they claim everything is back, but it was at least a 2.5 hour outage.  Authentication was down for all apps and web pages.

**Comment by msl2424** [comment]
Update: I re-started the add-on, and now it's working. The issue of "refresh token is not valid" occurs every now and then. Hard to tell why. Thanks for the prompt response.

**Comment by tsightler** [comment]
It's not that hard to tell why, you can almost always be sure it's a Ring outage.  Ring has lots of short, unacknowledged outages, especially with authentication.  I agree there could be improvements in recoverability from these issues, but as we don't control Ring servers, it's somewhat difficult to predict the various failure modes that can occur and pretty much impossible to test such scenarios.  We can emulate things like no connectivity at all, but partial failures where existing connections are still alive but new connections report the token being invalid can be difficult to deal with.

**Comment by tsightler** [comment]
I'm going to close this now as we know that current ring-client-api works and can generate usable tokens.  If you have additional issues in the future, please provide detailed steps and sample code from current versions of ring-client-api and we can look into it.
