### ISSUE TITLE
Ring Plugin, Service name is already in use on the network

### ISSUE THREAD

**Issue by KhMeRA** [dgreif/ring#128]
Dustin, I used to PM you regarding to this issue. I bring it here if someone experience the same problem could help. 
After reinstalling oznu/hombridge on my synology docker, I was running into the problem with Ring plugin, just Ring plugin all my other plugin are working fine but for now I only installed Ring plugin for troubleshooting purpose. Accoring to homegridge terminal or log file, It appear that homebrige found all devices and assesses for my Ring then generate a Homekit code for me then later on I got the error: 
 Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:198:13)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:198:13)

The homebrige keep looping the process nonstop. Does anyone know is the problem and how to fix it?

Note: I've reinstalled homebridge and docker many times, all folders under docker was removed during uninstall process,  but the problem still here.

**Comment by dgreif** [comment]
@KhMeRA I have tried everything I can think of to recreate this issue, but I am unable to.  Were you able to get it resolved?

**Comment by dgreif** [comment]
I think all these issues got resolved via DM

**Comment by KhMeRA** [comment]
Agree. Thanks.
