### ISSUE TITLE
Unable to authenticate with Ring servers

### ISSUE THREAD

**Issue by risograph** [dgreif/ring#1284]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe The Bug

I have generated a refreshtoken successfully with the CLI tool and now when starting homebridge the ring plugin remains non-functional because the token is invalid according to an error in the logs.

### To Reproduce

use homebridge-nest 11.8.1
start homebridge gui x 1.6.0
view logs
406 error after booting nest plugin

### Expected behavior

honestly not sure bc i havent gotten there yet.
i assume my connected devices would appear without error.

### Relevant log output

```shell
[8/7/2023, 9:29:19 AM] [Ring] HTTPError: Response code 406 (Not Acceptable)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1691364554493,
    socket: 1691364554595,
    lookup: 1691364554597,
    connect: 1691364555096,
    secureConnect: 1691364557895,
    upload: 1691364559497,
    response: 1691364559695,
    end: 1691364559793,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 102,
      dns: 2,
      tcp: 499,
      tls: 2799,
      request: 1602,
      firstByte: 198,
      download: 98,
      total: 5300
    }
  }
}
[8/7/2023, 9:29:19 AM] [Ring] Request to https://api.ring.com/devices/v1/locations failed:
[8/7/2023, 9:29:19 AM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:140:15)
    at RingRestClient.getAuth (/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:143:32)
    at RingRestClient.getAuth (/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:184:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[8/7/2023, 9:29:19 AM] [Ring] Error connecting to API
[8/7/2023, 9:29:19 AM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:140:15)
    at RingRestClient.getAuth (/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:143:32)
    at RingRestClient.getAuth (/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:184:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Homebridge Ring Config

```shell
{
    "refreshToken": "xxxxx",
    "platform": "Ring"
}
```

### OS

macOS Ventura

### Node.js Version

v20.4.0

### NPM Version

v9.7.2?

### Homebridge/HOOBs Version

v1.6.0

### Homebridge Ring Plugin Version

11.8.1

### Operating System

Docker

**Comment by tsightler** [comment]
Perhaps obvious but, as a general rule, if the API responds that the token is invalid, then it's because the token is invalid.  If you just generated it, then that would indicate that there was a copy/paste error (commonly the unintentional insertion of line breaks since the token is very long) or some other issue with how the token was placed into the configuration.  Other options include temporary Ring outages (they happen), or Ring has changed something and broken authentication completely, however, that latter issue would usually be followed by a significant number of reports in very short order.

You might consider using one of the UI based options for generating a token to avoid any potential copy/paste issues.

**Comment by dgreif** [comment]
`406` in particular can also mean that you are being rate limited. If this occurs, you simply need to wait a bit (e.g. a few hours) and try again. This doesn't happen often, but can occur if you try to log in many times in a row.

**Comment by raiubreaksthings** [comment]
I am seeing this as well. Same error string. Also requested updated token All devices work except voice requests to turn off "backyard" lights, Siri now asks what room and gets stuck in a loop. Cameras will not load from the home app. 
I rolled back to previous version and that corrected the voice request backyard issue, but not the cameras. 

[08/08/2023, 11:25:08] [Ring] connectionStateChange: closed
[08/08/2023, 11:25:08] [Ring] iceConnectionStateChange: closed
[08/08/2023, 11:25:08] [Ring] Failed to activate stream
[08/08/2023, 11:25:08] [Ring] RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at Function.padStart (/usr/local/lib/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:972:13)
    at Function.encodeSignature (/usr/local/lib/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:940:22)
    at Function.sign (/usr/local/lib/node_modules/homebridge-ring/node_modules/@peculiar/webcrypto/build/webcrypto.js:1575:54)
    at EcdsaProvider.onSign (/usr/local/lib/node_modules/homebridge-ring/node_modules/@peculiar/webcrypto/build/webcrypto.js:1737:25)
    at EcdsaProvider.sign (/usr/local/lib/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:157:28)
    at SubtleCrypto.sign (/usr/local/lib/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:1405:39)
    at Function.create (/usr/local/lib/node_modules/homebridge-ring/node_modules/@peculiar/x509/build/x509.cjs.js:2407:35)
    at Function.value [as createSelfSignedCertificateWithKey] (/usr/local/lib/node_modules/homebridge-ring/node_modules/dtls/src/context/cipher.ts:108:18)
    at RTCDtlsTransport.setupCertificate (/usr/local/lib/node_modules/homebridge-ring/node_modules/werift/src/transport/dtls.ts:76:9)

**Comment by raiubreaksthings** [comment]
Also need to note, the Cameras do work using the Ring application.

**Comment by tsightler** [comment]
@raiubreaksthings I'm not really clear what you are posting about.  You posted issues with streaming and Siri commands, but this issue is about authentication, however you could never even attempt to stream if you couldn't authenticate so it's very confusing. 
 It's generally better not to attempt to mix mulitple issues in threads, did you potentially post in the incorrect thread?

**Comment by raiubreaksthings** [comment]
I apologize I Google searched the message in the air string in this post came up and it’s the same error message I get when trying to watch the live stream from the home app on any of my devices. Not sure how much more clear I can make that.Sent from my iPhoneOn Aug 8, 2023, at 12:40 PM, tsightler ***@***.***> wrote:﻿
@raiubreaksthings I'm not really clear what you are posting about.  You posted issues with streaming and Siri commands, but this issue is about authentication, however you could never even attempt to stream if you couldn't authenticate so it's very confusing.
It's generally better not to attempt to mix mulitple issues in threads, did you potentially post in the incorrect thread?

**Comment by raiubreaksthings** [comment]
Says authentication error:Sent from my iPhoneOn Aug 8, 2023, at 12:40 PM, tsightler ***@***.***> wrote:﻿
@raiubreaksthings I'm not really clear what you are posting about.  You posted issues with streaming and Siri commands, but this issue is about authentication, however you could never even attempt to stream if you couldn't authenticate so it's very confusing.
It's generally better not to attempt to mix mulitple issues in threads, did you potentially post in the incorrect thread?

**Comment by tsightler** [comment]
@raiubreaksthings It's confusing because the logs you posted have no similarity to the logs posted in the original post on this issue so it's not at all clear why you think this is the same.  However, the logs you posted do match the logs from issue https://github.com/dgreif/ring/issues/1253, which is why I thought you may have posted on the incorrect issue.

If you were having the issue discussed in this thread, then nothing would work at all.

**Comment by raiubreaksthings** [comment]
I will migrate my notes over to that issue.

**Comment by johnrr70** [comment]
Similar wxperince....

Logs here....Tried manually updating token

[8/10/2023, 2:30:18 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 5A20) is running on port 51219.
[8/10/2023, 2:30:19 PM] [Ring] HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1691692218696,
    socket: 1691692218707,
    lookup: 1691692219505,
    connect: 1691692219522,
    secureConnect: 1691692219561,
    upload: 1691692219562,
    response: 1691692219623,
    end: 1691692219625,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 11,
      dns: 798,
      tcp: 17,
      tls: 39,
      request: 1,
      firstByte: 61,
      download: 2,
      total: 929
    }
  }
}
[8/10/2023, 2:30:19 PM] [Ring] Request to https://api.ring.com/devices/v1/locations failed:
[8/10/2023, 2:30:19 PM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:140:15)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:143:32)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:184:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[8/10/2023, 2:30:19 PM] [Ring] Error connecting to API
[8/10/2023, 2:30:19 PM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:140:15)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:143:32)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:184:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by dgreif** [comment]
@johnrr70 please see #1286 for your specific issue. I'm going to hide your comment as it's a bit off topic for this issue, but you are welcome to post on #1286 where I've asked users to provide some specific data to help us narrow the problem down.

**Comment by DerMuri** [comment]
I don't a a VPN running.

Did you have the VPN running on the Homebridge or on the client side?

> I've just had this, however the error was due to using a VPN on my computer. I couldn't even get onto Ring's website. I know they don't like VPN's. Once turned off I had no issue. Do you have a VPN turned on?

**Comment by PeterLawrence1** [comment]
I have Homebridge installed on my Mac

**Comment by dgreif** [comment]
Haven't heard back from @risograph, so I'm going to close this and assume it was rate limiting related.
