### ISSUE TITLE
Ring Homebridge not working, getting 406 error

### ISSUE THREAD

**Issue by Jozer99** [dgreif/ring#1337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

A few days ago, I lost connection between Homebridge and Ring.  Reboots of the router and homebridge server didn't fix it.  Logging on to homebridge, I get the following error

`[18/10/2023, 19:54:36] [Homebridge UI] [homebridge-ring] Incoming Request: /send-code
[18/10/2023, 19:54:36] [Homebridge UI] [homebridge-ring] Logging in with email 'xxx@xxx.com'
[18/10/2023, 19:54:36] [Homebridge UI] [homebridge-ring] TypeError: Cannot use 'in' operator to search for 'error' in <html>
<head><title>406 Not Acceptable</title></head>
<body>
<center><h1>406 Not Acceptable</h1></center>
<hr><center>openresty</center>
</body>
</html>

    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:186:119)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

I tried getting a new refresh token but get the same error.  

### To Reproduce

Not sure what brought it about, but Homebridge-Ring is unable to connect to Ring servers, getting an Error 406 as described above.  This happens when attempting to log in, or attempting to get a new Auth Token.

### Expected behavior

Homebridge-Ring connects to Ring servers without issue.  

### Relevant log output

```shell
`[18/10/2023, 19:54:36] [Homebridge UI] [homebridge-ring] Incoming Request: /send-code
[18/10/2023, 19:54:36] [Homebridge UI] [homebridge-ring] Logging in with email 'xxx@xxx.com'
[18/10/2023, 19:54:36] [Homebridge UI] [homebridge-ring] TypeError: Cannot use 'in' operator to search for 'error' in <html>
<head><title>406 Not Acceptable</title></head>
<body>
<center><h1>406 Not Acceptable</h1></center>
<hr><center>openresty</center>
</body>
</html>

    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:186:119)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`
```

### OS

Homebridge OS on Raspberry Pi, latest version of OS, Homebridge, and Plugin

### Node.js Version

18.16.0

### NPM Version

9.5.1

### ring-client-api

Whatever comes with the plugin version 12.0.1

### Operating System

See above.

**Comment by Jozer99** [comment]
Noticed a few more errors in the log, hope this helps:

`[18/10/2023, 20:08:49] [Ring] HTTPError: Response code 406 (Not Acceptable)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1697674128814,
    socket: 1697674128852,
    lookup: 1697674128937,
    connect: 1697674129044,
    secureConnect: 1697674129119,
    upload: 1697674129123,
    response: 1697674129302,
    end: 1697674129355,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 38,
      dns: 85,
      tcp: 107,
      tls: 75,
      request: 4,
      firstByte: 179,
      download: 53,
      total: 541
    }
  }
}
[18/10/2023, 20:08:49] [Ring] Request to https://api.ring.com/devices/v1/locations failed:
[18/10/2023, 20:08:49] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:140:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:143:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:184:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[18/10/2023, 20:08:49] [Ring] Error connecting to API
[18/10/2023, 20:08:49] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:140:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:143:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:184:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by tsightler** [comment]
The 406 error typically means your IP has been rate limited or otherwise temporarily blocked.  This can sometimes happen if, for example, you are using VPN and/or "privacy" services on your router as Ring blocks access to their systems from many of those IP blocks.  However, it can also happen it cases where, for example, a token expired because ring-client-api tries over and over and Ring will temporarily block access.  You'll need to stop all connections to Ring from that location for 8-12 hours and then try again.

If you do a search for "406" under closed issues you will see a number of other reports and various solutions, most involved simply stopping ring-homebridge for a while and tryting again later.

**Comment by tsightler** [comment]
Closing due to no response.
