### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by rsinjab** [dgreif/ring#1340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Failed to reach Ring server
RequestError: getaddrinfo ENOTFOUND app.ring.com

### Expected behavior

Plugin to connect using the API

### Relevant log output

```shell
[25/10/2023, 19:07:26] [homebridge-ring] Failed to reach Ring server at https://app.ring.com/api/v1/clap/tickets?locationID=4a571653-c69d-4526-872f-8271d023c0a9.  getaddrinfo ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[25/10/2023, 19:07:26] [homebridge-ring] RequestError: getaddrinfo ENOTFOUND app.ring.com
    at ClientRequest.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.origin.emit (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  code: 'ENOTFOUND',
  timings: {
    start: 1698246446475,
    socket: 1698246446475,
    lookup: 1698246446506,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1698246446506,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 31,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 31
    }
  }
}
[25/10/2023, 19:07:31] [homebridge-ring] Failed to reach Ring server at https://app.ring.com/api/v1/clap/tickets?locationID=4a571653-c69d-4526-872f-8271d023c0a9.  getaddrinfo ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[25/10/2023, 19:07:31] [homebridge-ring] RequestError: getaddrinfo ENOTFOUND app.ring.com
    at ClientRequest.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.origin.emit (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  code: 'ENOTFOUND',
  timings: {
    start: 1698246451519,
    socket: 1698246451520,
    lookup: 1698246451537,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1698246451538,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 17,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 19
    }
  }
}
```

### Screenshots

![Screenshot 2023-10-25 at 7 08 45 PM](https://github.com/dgreif/ring/assets/81008089/58d31b3b-bde4-46fd-aefa-a8d29506349b)

### Homebridge Ring Config

```shell
"platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "refreshToken": "**************************************************",
            "unbridgeCameras": true,
            "alarmOnEntryDelay": true,
            "hideDoorbellSwitch": true,
            "nightModeBypassFor": "some",
            "debug": true,
            "_bridge": {
                "username": "0E:56:EE:B5:35:8C",
                "port": 35671
            },
            "platform": "Ring"
```

### Additional context

I have tried pinging api.ring.com and it works fine.
Tried restarting HB and the child bridge with no luck

### OS

Raspbian

### Node.js Version

v18.16.0

### NPM Version

9.5.1

### Homebridge/HOOBs Version

v4.51.0

### Homebridge Ring Plugin Version

v12.0.1

### Operating System

Raspbian

**Comment by tsightler** [comment]
ENOTFOUND is pretty straightforward, your host is unable to resolve the app.ring.com address.  This is not an issue with the API and there's not much we can do to help you, you will need to figure out why your host cannot resolve this address, most likely some DNS issue.
