### ISSUE TITLE
Response Code 422

### ISSUE THREAD

**Issue by shanekelly55** [dgreif/ring#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Just today after updating node.js to the latest version, none of my Ring cameras work in HomeBridge.  I m getting the following:

[28/02/2024, 21:30:58] [homebridge-ring] Request to https://api.ring.com/clients_api/doorbots/363340030/siren_on failed with status 422. Response body: 
[28/02/2024, 21:30:58] [homebridge-ring] HTTPError: Response code 422 (Unprocessable Entity)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1709177457808,
    socket: 1709177457810,
    lookup: 1709177457852,
    connect: 1709177457896,
    secureConnect: 1709177457945,
    upload: 1709177457945,
    response: 1709177458061,
    end: 1709177458062,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 42,
      tcp: 44,
      tls: 49,
      request: 0,
      firstByte: 116,
      download: 1,
      total: 254
    }
  }
}
[28/02/2024, 21:31:58] [homebridge-ring] Request to https://api.ring.com/clients_api/doorbots/363340030/siren_on failed with status 422. Response body: 
[28/02/2024, 21:31:58] [homebridge-ring] HTTPError: Response code 422 (Unprocessable Entity)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1709177518085,
    socket: 1709177518087,
    lookup: 1709177518147,
    connect: 1709177518189,
    secureConnect: 1709177518234,
    upload: 1709177518234,
    response: 1709177518338,
    end: 1709177518339,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 60,
      tcp: 42,
      tls: 45,
      request: 0,
      firstByte: 104,
      download: 1,
      total: 254
    }
  }
}

### Expected behavior

For the cameras to work again.

### Relevant log output

```shell
[28/02/2024, 21:30:58] [homebridge-ring] Request to https://api.ring.com/clients_api/doorbots/363340030/siren_on failed with status 422. Response body: 
[28/02/2024, 21:30:58] [homebridge-ring] HTTPError: Response code 422 (Unprocessable Entity)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1709177457808,
    socket: 1709177457810,
    lookup: 1709177457852,
    connect: 1709177457896,
    secureConnect: 1709177457945,
    upload: 1709177457945,
    response: 1709177458061,
    end: 1709177458062,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 42,
      tcp: 44,
      tls: 49,
      request: 0,
      firstByte: 116,
      download: 1,
      total: 254
    }
  }
}
[28/02/2024, 21:31:58] [homebridge-ring] Request to https://api.ring.com/clients_api/doorbots/363340030/siren_on failed with status 422. Response body: 
[28/02/2024, 21:31:58] [homebridge-ring] HTTPError: Response code 422 (Unprocessable Entity)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1709177518085,
    socket: 1709177518087,
    lookup: 1709177518147,
    connect: 1709177518189,
    secureConnect: 1709177518234,
    upload: 1709177518234,
    response: 1709177518338,
    end: 1709177518339,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 60,
      tcp: 42,
      tls: 45,
      request: 0,
      firstByte: 104,
      download: 1,
      total: 254
    }
  }
}
```

### Homebridge Ring Config

```shell
unsure how to get this
```

### OS

Debian GNU/Linux Bookworm (12)

### Node.js Version

v20.11.1

### NPM Version

unsure

### Homebridge/HOOBs Version

latest

### Homebridge Ring Plugin Version

v12.1.0

### Operating System

Debian GNU/Linux Bookworm (12)

**Comment by tsightler** [comment]
Since the problem is occurring after making changes, but there were no code changes in the plugin, I would guess you will need to look at the items that changed.  Unfortunately, not much input that can be added from this side.  Sometimes simple errors like this are temporary on the Ring side as well.
