### ISSUE TITLE
Unable to connect to Ring API

### ISSUE THREAD

**Issue by JaySwede** [dgreif/ring#141]
I have been unable to connect to Ring's API anymore. In the past this worked great but about a month ago it just stopped working. I have tried authenticating with both the email/password in the config and also the refreshtoken. Neither has been successful. Any help or direction would be appreciated.

`[10/1/2019, 1:49:32 PM] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed
[10/1/2019, 1:49:32 PM] [Ring] Error connecting to API
[10/1/2019, 1:49:32 PM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/node/lib/node_modules/homebridge-ring/lib/api/rest-client.js:85:15)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/node/lib/node_modules/homebridge-ring/lib/api/rest-client.js:89:36)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/node/lib/node_modules/homebridge-ring/lib/api/rest-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/node/lib/node_modules/homebridge-ring/lib/api/rest-client.js:4:12)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/node/lib/node_modules/homebridge-ring/lib/api/rest-client.js:88:16)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/node/lib/node_modules/homebridge-ring/lib/api/rest-client.js:113:33)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/node/lib/node_modules/homebridge-ring/lib/api/rest-client.js:6:65)
`

**Comment by JaySwede** [comment]
System error of some kind on my end. Nothing to see here...

**Comment by dgreif** [comment]
Looks like your `refreshToken` had expired.  You should be able to generate a new one and be good to go
