### ISSUE TITLE
Unable to connect to API

### ISSUE THREAD

**Issue by cooperb125** [dgreif/ring#143]
Hello! I get this error when trying to install the Ring extension in Homebridge. It's a fresh install, using the "sudo npm install homebridge-ring" command:

`pi@raspberrypi:~ $ sudo npm install homebridge-ring@5.6.2
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

homebridge-ring@5.6.2
added 167 packages in 16.112s`

When I try to launch Homebridge, I get this:

`[2019-10-4 10:00:47] Homebridge is running on port 51828.
[2019-10-4 10:00:49] [Ring] Error connecting to API
[2019-10-4 10:00:49] [Ring] TypeError: Cannot read property 'getValue' of undefined
    at RingCamera.get data [as data] (/usr/local/lib/node_modules/homebridge-ring/lib/api/ring-camera.js:64:28)
    at RingCamera.get batteryLevel [as batteryLevel] (/usr/local/lib/node_modules/homebridge-ring/lib/api/ring-camera.js:73:37)
    at new RingCamera (/usr/local/lib/node_modules/homebridge-ring/lib/api/ring-camera.js:42:22)
    at allCameras.map.data (/usr/local/lib/node_modules/homebridge-ring/lib/api/api.js:103:285)
    at Array.map (<anonymous>)
    at RingApi.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/api.js:103:273)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/api.js:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
[2019-10-4 10:00:51] [Config] Homebridge Config UI X v4.6.1 is listening on :: port 8080
`

I've even turned off all my added extensions to see if that will solve the problem, but it has not. Any help would be appreciated!

**Comment by dgreif** [comment]
@cooperb125 thanks for reporting this issue!  I made a small mistake in the last release, but it should be fixed in v5.8.1.  Can you update and let me know if it works for you now?

The code that failed is related to determining if a camera has a battery or not. Would you mind posting which camera models you are using with the plugin and if they are wired/battery/solar?

**Comment by cooperb125** [comment]
Thanks! That sort of worked :) It got slightly further, and I can add some of my cameras, but this is the error I get when trying to load it:

`[2019-10-4 11:27:52] [Ring] Snapshot for Front Door Requested
[2019-10-4 11:27:52] [Ring] No snapshot available and device Front Door is offline
[2019-10-4 11:27:52] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/1803397
[2019-10-4 11:27:52] [Ring] Failed to retrieve snapshot for Front Door (0.433s).  The camera currently reports that is it offline
[2019-10-4 11:27:52] [Ring] Error: Not found with response: no snapshot

    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:231:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:6:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
`

**Comment by cooperb125** [comment]
I solved the issue with the no snapshot. That camera's battery is dead haha...but these three cameras are Stickup Cams and a floodlight that don't show in HomeKit, but appear to be added in Homebridge:

[2019-10-4 11:31:15] N. Ext - W. Facing is running on port 34303.
[2019-10-4 11:31:15] Please add [N. Ext - W. Facing] manually in Home app. Setup Code: 031-45-154
[2019-10-4 11:31:15] S. Ext - Truckcam is running on port 37095.
[2019-10-4 11:31:15] Please add [S. Ext - Truckcam] manually in Home app. Setup Code: 031-45-154
[2019-10-4 11:31:15] Shed is running on port 37149.
[2019-10-4 11:31:15] Please add [Shed] manually in Home app. Setup Code: 031-45-154
[2019-10-4 11:31:15] W. Ext - Floodlight is running on port 45727.
[2019-10-4 11:31:15] Please add [W. Ext - Floodlight] manually in Home app. Setup Code: 031-45-154

**Comment by dgreif** [comment]
Glad you figured out the snapshot issue!  Here's a link to the wiki which walks you through how to fix your last issue: https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#cannot-add-camera-from-home
