### ISSUE TITLE
TypeError: plugin.initializer is not a function

### ISSUE THREAD

**Issue by Bullet55NL** [dgreif/ring#151]
Hello,

I tried to install and configure the ring plugin on my homebridge device. I am using a raspberry pi 2 as a homebridge. I currently have a Nest thermostat plugin already installed & configured to work with homekit. After I installed the ring doorbell plugin, configured my config.json & booted up homebridge I get this error;

_/home/pi/.nvm/versions/node/v10.4.0/lib/node_modules/homebridge/lib/server.js:165
      plugin.initializer(this._api);
             ^

TypeError: plugin.initializer is not a function
    at Server.<anonymous> (/home/pi/.nvm/versions/node/v10.4.0/lib/node_modules/homebridge/lib/server.js:165:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/home/pi/.nvm/versions/node/v10.4.0/lib/node_modules/homebridge/lib/server.js:139:22)
    at new Server (/home/pi/.nvm/versions/node/v10.4.0/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/home/pi/.nvm/versions/node/v10.4.0/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/home/pi/.nvm/versions/node/v10.4.0/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)_

Can you please help me. Thanks in advance :-)

**Comment by dgreif** [comment]
See #12.  Probably just need to update homebridge.

**Comment by Bullet55NL** [comment]
Thanks, this worked!

You are a life saver :-)
