### ISSUE TITLE
No Snapshot and Live stream is "no response"

### ISSUE THREAD

**Issue by kahnartist81** [dgreif/ring#173]
Hello again,
Not sure what's going on with my setup. Everything was working fine this morning (mostly), snapshots were updating, and notifications were being sent. Now, all of a sudden my cameras are all offline, but the alarm and sensors are still working. My last  snapshot was 6 hours ago. They are working perfectly fine on the Ring app.

Also, I've never been able to actually live view any of my cameras. Was always just using the snapshot which refreshed every minute or so.

**Comment by kahnartist81** [comment]
Yes, looks like only my cameras are currently not working, any part of them. Lights, Sirens, sensors, oh my! Here's my most recent log to show everything seems to be loading up correctly, but the cameras just don't want to respond.
[recent log.txt](https://github.com/dgreif/ring/files/3816950/recent.log.txt)

**Comment by matth3w** [comment]
I have run into the same issues. I updated to the most recent version, but that did nothing. I then decided to remove the camera from HomeKit and re-add them to see if that would fix my issues, but it didn't. In fact, I can't re-add the cameras at all now, even after deleting their corresponding files in the HomeKit persist folder. Oh, and before all of this I got a new authToken from ring, put that didn't seem to fix anything. My security system still works though.

**Comment by dgreif** [comment]
Hey guys, sorry you are having trouble getting the cameras back into HomeKit.  Deleting the corresponding files from the persist folder is the most I've ever had to do to get them to be available again.  I'd try restarting everything - homebridge server, iPhone, Home hub (apple tv, iPad) and try it again

**Comment by kahnartist81** [comment]
Update. When I got home last night I was able to delete each of the cameras from the Home app then re-add them and the snapshots worked again. BUT, the live view still does not work. When I click into the camera, I get the spinning wheel then a "no response" alert. This happens for all 5 cameras. 
![A176D9F8-8434-4CC2-A4B2-7B83E3A79FB6](https://user-images.githubusercontent.com/33696994/68405656-5938a380-0135-11ea-96b4-9794cea8d207.png)

**Comment by dgreif** [comment]
https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#live-stream-troubleshooting

**Comment by kahnartist81** [comment]
After having done all of the main steps last night when finally getting the cameras back in the Home app. I just tried to access the feed again to get the most recent log information. Here it is pasted below. The first is the output info, the second is the error info.

> [2019-11-7 09:35:07] [Ring] Preparing Live Stream for Driveway
[2019-11-7 09:35:42] [Ring] Waiting for stream data from Driveway (35.367s)
[2019-11-7 09:35:42] [Ring] Received stream data from Driveway (35.446s)
[2019-11-7 09:36:20] [Ring] Snapshot for Driveway Requested
[2019-11-7 09:36:20] [Ring] Snapshot for Front Door Requested
[2019-11-7 09:36:20] [Ring] Snapshot for Family Room Requested
[2019-11-7 09:36:20] [Ring] Snapshot for Backyard Requested
[2019-11-7 09:36:22] [Ring] Snapshot for Family Room Received (1.828s)
[2019-11-7 09:36:22] [Ring] Snapshot for Driveway Received (2.467s)
[2019-11-7 09:36:23] [Ring] Snapshot for Front Door Received (2.446s)
[2019-11-7 09:36:23] [Ring] Snapshot for Backyard Received (2.442s)
[2019-11-7 09:36:27] [Ring] Preparing Live Stream for Driveway
[2019-11-7 09:36:58] [Ring] Preparing Live Stream for Front Door
[2019-11-7 09:37:03] [Ring] Waiting for stream data from Driveway (35.528s)
[2019-11-7 09:37:03] [Ring] Received stream data from Driveway (35.537s)
[2019-11-7 09:37:20] [Ring] Preparing Live Stream for Driveway
[2019-11-7 09:37:47] [Ring] Snapshot for Driveway Requested
[2019-11-7 09:37:47] [Ring] Snapshot for Front Door Requested
[2019-11-7 09:37:47] [Ring] Snapshot for Front Door is still within it's life time (84.85s old)
[2019-11-7 09:37:47] [Ring] Snapshot for Front Door Received (0s)
[2019-11-7 09:37:47] [Ring] Snapshot for Family Room Requested
[2019-11-7 09:37:47] [Ring] Snapshot for Backyard Requested
[2019-11-7 09:37:47] [Ring] Snapshot for Backyard is still within it's life time (84.687s old)
[2019-11-7 09:37:47] [Ring] Snapshot for Backyard Received (0.001s)
[2019-11-7 09:37:49] [Ring] Snapshot for Family Room Received (1.761s)
[2019-11-7 09:37:49] [Ring] Snapshot for Driveway Received (2.372s)
[2019-11-7 09:37:55] [Ring] Waiting for stream data from Driveway (35.41s)
[2019-11-7 09:37:55] [Ring] Received stream data from Driveway (35.416s)
[2019-11-7 09:38:48] [Ring] Snapshot for Front Door Requested
[2019-11-7 09:38:48] [Ring] Snapshot for Front Door is still within it's life time (145.718s old)
[2019-11-7 09:38:48] [Ring] Snapshot for Front Door Received (0s)
[2019-11-7 09:38:48] [Ring] Snapshot for Backyard Requested
[2019-11-7 09:38:48] [Ring] Snapshot for Backyard is still within it's life time (145.722s old)
[2019-11-7 09:38:48] [Ring] Snapshot for Backyard Received (0.001s)
[2019-11-7 09:38:50] [Ring] Snapshot for Family Room Requested
[2019-11-7 09:38:50] [Ring] Snapshot for Driveway Requested
[2019-11-7 09:38:51] [Ring] Snapshot for Family Room Received (1.741s)
[2019-11-7 09:38:52] [Ring] Snapshot for Driveway Received (2.324s)

> [2019-11-7 09:37:34] [Ring] sip INVITE request failed with status 480
[2019-11-7 09:37:34] [Ring] Failed to prepare stream for Front Door (35.418s)
[2019-11-7 09:37:34] [Ring] Error: sip INVITE request failed with status 480
    at sipClient.send (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-session.js:169:28)
    at searching (/usr/local/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:1316:5)
    at /usr/local/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:1297:41
    at Object.message (/usr/local/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:1116:7)
    at Object.signal (/usr/local/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:982:55)
    at /usr/local/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:1344:24
    at onMessage (/usr/local/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:558:9)
    at content (/usr/local/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:493:7)
    at headers (/usr/local/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:480:9)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:504:27)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20)

**Comment by dgreif** [comment]
The `480` error happens when you start live video, stop it, and start it again in quick succession.  This error comes from the Ring servers and I have not found a good way to prevent it after many hours of trial and error.  I would recommend restarting you homebridge server and trying live streaming again.

**Comment by kahnartist81** [comment]
Weird. I tried the homebridge restart and nothing has changed. Luckily the snapshots constantly update, so I can just use the ring app for live stream for now.

Side note, I know it's not your app, but you recommend it on the bottom of your page, about the dummy buttons. I installed them exactly how you mentioned and they show up and everything, but they don't actually do anything they're supposed to. Am I missing something on how you intend them to work with the ring setup?
![PNG image](https://user-images.githubusercontent.com/33696994/68434682-6f168a80-016e-11ea-8b62-546a97e17482.png)

**Comment by dgreif** [comment]
You need to set up a second automation that will disarm the alarm when `Arrived Home` turns on.  Sorry I can't help more on the live streams, seems like HomeKit is messed up or your network is blocking the connection (though that's not likely since it was working before).  Maybe try restarting all your HomeKit devices as well
