### ISSUE TITLE
Connection issues: Failed to Reach Ring server

### ISSUE THREAD

**Issue by QuarterSwede** [dgreif/ring#179]
After succesfully setting up Homebridge and this Ring plugin on a x86_64 SBC running Lubuntu 19.04, I get flakey connection issues. It will connect and run fine for a period of time and then randomly lose connection to the Ring servers. The time varies. Sometimes it'll run solid for 24 hours, sometimes less than an hour. I have only two plugins, Ring and HarmonyHub. Two terminal outputs are below.

>
[10/27/2019, 5:25:38 PM] Homebridge is running on port 51826.
[10/27/2019, 5:25:40 PM] [Ring] Creating location socket.io connection
[10/27/2019, 5:25:40 PM] [Harmony Hub] Fetching Logitech Harmony activities...
[10/27/2019, 5:25:40 PM] [Ring] Ring connected to socket.io server
[10/27/2019, 5:25:41 PM] [Ring] Configuring 0 cameras and 14 devices for location "Colorado Springs" - locationId: 0c2bd787-a0dd-40cd-946c-a172e8bd01a0
[10/27/2019, 5:25:41 PM] [Harmony Hub] Found activities: 
        Watch a Movie
        Watch TV
        PowerOff
        Watch Apple TV
        Play Wii U
        Watch Fire TV Stick
[10/28/2019, 12:41:07 PM] [Ring] Reconnecting location socket.io connection
[10/28/2019, 12:41:08 PM] [Ring] Creating location socket.io connection
[10/28/2019, 12:41:42 PM] [Ring] Ring connected to socket.io server
[10/28/2019, 12:49:46 PM] [Ring] Reconnecting location socket.io connection
[10/28/2019, 12:49:47 PM] [Ring] Creating location socket.io connection
[10/28/2019, 12:50:07 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/clap/tickets?locationID=0c2bd787-a0dd-40cd-946c-a172e8bd01a0.  Trying again in 5 seconds...
[10/28/2019, 12:50:32 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/clap/tickets?locationID=0c2bd787-a0dd-40cd-946c-a172e8bd01a0.  Trying again in 5 seconds...
[10/28/2019, 12:51:07 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/clap/tickets?locationID=0c2bd787-a0dd-40cd-946c-a172e8bd01a0.  Trying again in 5 seconds...
[10/28/2019, 12:51:37 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/clap/tickets?locationID=0c2bd787-a0dd-40cd-946c-a172e8bd01a0.  Trying again in 5 seconds...
[10/28/2019, 12:52:02 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/clap/tickets?locationID=0c2bd787-a0dd-40cd-946c-a172e8bd01a0.  Trying again in 5 seconds...
[10/28/2019, 12:52:18 PM] [Ring] Ring connected to socket.io server
[10/28/2019, 1:59:50 PM] [Ring] Reconnecting location socket.io connection
[10/28/2019, 1:59:51 PM] [Ring] Creating location socket.io connection
[10/28/2019, 2:00:11 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/clap/tickets?locationID=0c2bd787-a0dd-40cd-946c-a172e8bd01a0.  Trying again in 5 seconds...
[10/28/2019, 2:00:26 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/clap/tickets?locationID=0c2bd787-a0dd-40cd-946c-a172e8bd01a0.  Trying again in 5 seconds...
[10/28/2019, 2:01:28 PM] [Ring] Ring connected to socket.io server
[10/28/2019, 2:01:28 PM] [Ring] Reconnecting location socket.io connection
[10/28/2019, 2:01:29 PM] [Ring] Creating location socket.io connection
[10/28/2019, 2:01:39 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/clap/tickets?locationID=0c2bd787-a0dd-40cd-946c-a172e8bd01a0.  Trying again in 5 seconds...
[10/28/2019, 2:02:43 PM] [Ring] Ring connected to socket.io server
[10/28/2019, 2:04:07 PM] [Ring] Reconnecting location socket.io connection
[10/28/2019, 2:04:08 PM] [Ring] Creating location socket.io connection
[10/28/2019, 2:04:28 PM] [Ring] Ring connected to socket.io server
[10/28/2019, 2:05:52 PM] [Ring] Reconnecting location socket.io connection
[10/28/2019, 2:05:53 PM] [Ring] Creating location socket.io connection
[10/28/2019, 2:06:20 PM] [Ring] Ring connected to socket.io server
[10/28/2019, 2:16:59 PM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)                                                                                                                             
[10/28/2019, 2:16:59 PM] Got SIGTERM, shutting down Homebridge...
>

This is slightly different (not sure if the same of different issue:

>
[11/11/2019, 6:16:17 PM] Homebridge is running on port 51826.
[11/11/2019, 6:16:18 PM] [Ring] Creating location socket.io connection
[11/11/2019, 6:16:19 PM] [Ring] Ring connected to socket.io server
[11/11/2019, 6:16:20 PM] [Harmony Hub] Fetching Logitech Harmony activities...
[11/11/2019, 6:16:20 PM] [Ring] Configuring 0 cameras and 14 devices for location "Colorado Springs" - locationId: 0c2bd787-a0dd-40cd-946c-a172e8bd01a0
[11/11/2019, 6:16:21 PM] [Harmony Hub] Found activities: 
        Watch a Movie
        Watch TV
        PowerOff
        Watch Apple TV
        Play Wii U
        Watch Fire TV Stick
errorhub Error: connect EHOSTUNREACH 192.168.0.28:5222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.0.28',
  port: 5222
}
errorhub Error: connect EHOSTUNREACH 192.168.0.28:5222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.0.28',
  port: 5222
}
[11/12/2019, 7:18:51 PM] [Ring] Reconnecting location socket.io connection
[11/12/2019, 7:18:52 PM] [Ring] Creating location socket.io connection
[11/12/2019, 7:19:12 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/clap/tickets?locationID=0c2bd787-a0dd-40cd-946c-a172e8bd01a0.  Trying again in 5 seconds...
[11/12/2019, 7:19:19 PM] [Ring] Ring connected to socket.io server
[11/12/2019, 7:20:06 PM] Error: MAX_CLIENTS=6
    at Connection.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:355:17)                                                                
    at StreamParser.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)                                                           
    at StreamParser.emit (events.js:210:5)                                                                                                                                                   
    at SaxLtx.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)                                                                
    at SaxLtx.emit (events.js:210:5)                                                                                                                                                         
    at SaxLtx._handleTagOpening (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:31:18)                                                                      
    at SaxLtx.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)                                                                                 
    at StreamParser.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)                                                               
    at Connection.onData (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)                                                                  
    at Socket.emit (events.js:215:7)                                                                                                                                                         
    at addChunk (_stream_readable.js:308:12)                                                                                                                                                 
    at readableAddChunk (_stream_readable.js:289:11)                                                                                                                                         
    at Socket.Readable.push (_stream_readable.js:223:10)                                                                                                                                     
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) 
[11/12/2019, 7:20:06 PM] Got SIGTERM, shutting down Homebridge...
>

Anyone else having the same issue or know what's going on? I love the plugin otherwise as I have been able to add a motion detector automation to trigger my kitchen cabinet lights after 9pm.

**Comment by dgreif** [comment]
Sorry you are having issues, but this is not due to the plugin.  Some part of your network is being flakey.  You can see that the Harmony Hub plugin is also outputting errors `EHOSTUNREACH 192.168.0.28:5222` which means it can't reach a device on you network.

**Comment by QuarterSwede** [comment]
That's a start then. I'll check my network and see what's going on. Thanks for the help!

**Comment by derflr** [comment]
I have the same issues. Did you ever figure this out?
