### ISSUE TITLE
Not able to update Snapshot

### ISSUE THREAD

**Issue by solbadguy2010** [dgreif/ring#182]
Any Idea how to solve this? 

[11/15/2019, 6:54:04 PM] [Ring] Snapshot for Haustür Requested
[11/15/2019, 6:54:54 PM] [Ring] Snapshot failed to refresh after 60 attempts
[11/15/2019, 6:54:54 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/24313994
[11/15/2019, 6:54:55 PM] [Ring] Failed to retrieve snapshot for Haustür (50.634s).  The camera currently reports that is it online
[11/15/2019, 6:54:55 PM] [Ring] Error: Not found with response: no snapshot
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:231:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by dgreif** [comment]
I've had a number of users with similar issues and hadn't taken the time to add a wiki entry.  I just added all I know under https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#snapshot-issues .  Let me know if that helps you get it sorted out
