### ISSUE TITLE
Overlapping Services

### ISSUE THREAD

**Issue by bgolub** [dgreif/ring#186]
Any idea how to fix this error? I've tried renaming all my sensors to unique names but still get the error:

```
`11/22/2019, 7:33:35 AM] [Ring] Error: Overlapping services for device Front Door Sensor - Front Door Sensor != Front Door - function(displayName, subtype) {
  Service.call(this, displayName, '00000080-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.ContactSensorState);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.StatusActive);
  this.addOptionalCharacteristic(Characteristic.StatusFault);
  this.addOptionalCharacteristic(Characteristic.StatusTampered);
  this.addOptionalCharacteristic(Characteristic.StatusLowBattery);
  this.addOptionalCharacteristic(Characteristic.Name);
}
    at ContactSensor.getService (/homebridge/node_modules/homebridge-ring/lib/homebridge/base-accessory.js:35:19)
    at ContactSensor.registerCharacteristic (/homebridge/node_modules/homebridge-ring/lib/homebridge/base-accessory.js:43:30)
    at new ContactSensor (/homebridge/node_modules/homebridge-ring/lib/homebridge/contact-sensor.js:13:14)
    at /homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:150:123
    at Array.forEach (<anonymous>)
    at RingPlatform.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:131:28)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by dgreif** [comment]
It's an existing issue with renaming devices.  I added logic to prevent duplicate services from being created, but it's causing a bunch of other issues.  Planning to fix it up soon but haven't had time to do it.  For now, try renaming that sensor back to `Front Door` instead of `Front Door Sensor`

**Comment by bgolub** [comment]
Thanks. That did the trick! Looking forward to better renaming support later.

**Comment by dgreif** [comment]
This check has been removed in v`5.10.0` and shouldn't cause you any more issues when renaming devices
