### ISSUE TITLE
Overlapping services - Smoke Alarm

### ISSUE THREAD

**Issue by waltersobchak40** [dgreif/ring#190]
Hi All, 
I've noticed that my cameras aren't sending images to Home.app over the past couple of weeks. I looked more closely and found an error on the smoke alarm when loading. I've copied what I think is the most relevant lines from the log files. Any ideas?

```
[11/28/2019, 10:01:07 PM] [Ring] Configuring 4 cameras and 24 devices for location "Home" - locationId: 1d5c00d7-71a6-43f4-755b-a397f48f9514
[11/28/2019, 10:01:07 PM] [Ring] Error connecting to API
[11/28/2019, 10:01:07 PM] [Ring] Error: Overlapping services for device Entry - First Alert Smoke Alarm 1 - Entry - First Alert Smoke Alarm 1 != First Alert Smoke Alarm 1 - function(displayName, subtype) {
  Service.call(this, displayName, '00000087-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.SmokeDetected);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.StatusActive);
  this.addOptionalCharacteristic(Characteristic.StatusFault);
  this.addOptionalCharacteristic(Characteristic.StatusTampered);
  this.addOptionalCharacteristic(Characteristic.StatusLowBattery);
  this.addOptionalCharacteristic(Characteristic.Name);
}
    at SmokeAlarm.getService (/usr/local/lib/node_modules/homebridge-ring/lib/homebridge/base-accessory.js:35:19)
    at SmokeAlarm.registerCharacteristic (/usr/local/lib/node_modules/homebridge-ring/lib/homebridge/base-accessory.js:43:30)
    at new SmokeAlarm (/usr/local/lib/node_modules/homebridge-ring/lib/homebridge/smoke-alarm.js:13:14)
    at /usr/local/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:150:123
    at Array.forEach (<anonymous>)
    at RingPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:131:28)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:5:58)
```

**Comment by dgreif** [comment]
This check has been removed in v`5.10.0` and shouldn't cause you any more issues
