### ISSUE TITLE
Error while obtaining machine id: Error: Command failed: ioreg -rd1 -c IOPlatformExpertDevice

### ISSUE THREAD

**Issue by chester645** [dgreif/ring#207]
I am getting an error when running on MacOS Catalina:

[12/24/2019, 1:18:37 AM] [Ring] Error: Error while obtaining machine id: Error: Command failed: ioreg -rd1 -c IOPlatformExpertDevice
/bin/sh: ioreg: command not found

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
    at /usr/local/lib/node_modules/homebridge-ring/node_modules/node-machine-id/dist/index.js:1:7964
    at ChildProcess.exithandler (child_process.js:302:5)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)

**Comment by chester645** [comment]
I had to update the path in my plist launchagent to:

<key>EnvironmentVariables</key>
        <dict>
        <key>PATH</key>
            <string>**/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:$PATH**</string>
        <key>HOME</key>
