### ISSUE TITLE
Cannot set property of 'xxx' undefined (homebridge-ring)

### ISSUE THREAD

**Issue by crockpotveggies** [dgreif/ring#208]
Trying to boot up homebridge-ring and it sees most of my devices, but apparently one particular ID is undefined or is triggering an error:

```
Dec 23 23:18:47 jstation homebridge[7506]: [12/23/2019, 11:18:47 PM] TypeError: Cannot set property 'xxxx-7cd5-xxxx-991c-xxxx' of undefined
Dec 23 23:18:47 jstation homebridge[7506]:     at Ring.configureAccessory (/usr/local/lib/node_modules/homebridge-platform-ring-video-doorbell/index.js:129:36)
Dec 23 23:18:47 jstation homebridge[7506]:     at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:386:24)
Dec 23 23:18:47 jstation homebridge[7506]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:8)
Dec 23 23:18:47 jstation homebridge[7506]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Dec 23 23:18:47 jstation homebridge[7506]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Dec 23 23:18:47 jstation homebridge[7506]:     at Module._compile (module.js:652:30)
Dec 23 23:18:47 jstation homebridge[7506]:     at Object.Module._extensions..js (module.js:663:10)
Dec 23 23:18:47 jstation homebridge[7506]:     at Module.load (module.js:565:32)
Dec 23 23:18:47 jstation homebridge[7506]:     at tryModuleLoad (module.js:505:12)
Dec 23 23:18:47 jstation homebridge[7506]:     at Function.Module._load (module.js:497:3)
Dec 23 23:18:47 jstation homebridge[7506]:     at Function.Module.runMain (module.js:693:10)
Dec 23 23:18:47 jstation homebridge[7506]:     at startup (bootstrap_node.js:188:16)
Dec 23 23:18:47 jstation homebridge[7506]:     at bootstrap_node.js:609:3
Dec 23 23:18:47 jstation homebridge[7506]: [12/23/2019, 11:18:47 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by crockpotveggies** [comment]
Closing, this was an old ring extension and erasing and recreating the `/accessories` folder fixed the problem.
