### ISSUE TITLE
406 Not Acceptable error

### ISSUE THREAD

**Issue by rpavlik** [dgreif/ring#247]
# Bug Report

### Describe the Bug

I can't log in - I'm getting a "406 Not Acceptable" error. I changed my script-dedicated account password following an unexpected "got a login from an Android app" notification in my email (though looking at the debug, that was probably just this package). I also updated ring-alarm-mqtt (and thus this package) before putting the new (longer) password.

### To Reproduce

 - Run the auth-cli script - I've tried using the latest master as well as an older version that previously worked.
 - Attempt to log in (I'm using a 24-character password, which is the only thing I changed between it working and not working. Have tried down to a 12 character which still doesn't work.)
 - See error

### Expected behavior

Login to work - as I mentioned, I was using this before (older version, shorter password) successfully for quite some time.

### Screenshots/Logs

Not sure what parts of the logs are useful here - I've erred on the side of "include nothing that might be related to a token"... hopefully it's still useful.

```
  follow-redirects options { protocol: 'https:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/oauth/token',
  method: 'POST',
  headers:
   { Accept: 'application/json, text/plain, */*',
     'Content-Type': 'application/json',
     '2fa-support': 'true',
     '2fa-code': '',
     hardware_id: 'XXXX',
     'User-Agent': 'axios/0.19.1',
     'Content-Length': 151 },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'oauth.ring.com',
  port: null,
  nativeProtocols:
   { 'http:':
      { _connectionListener: [Function: connectionListener],
        METHODS: [Array],
        STATUS_CODES: [Object],
        Agent: [Function],
        ClientRequest: [Function],
        globalAgent: [Agent],
        IncomingMessage: [Function],
        OutgoingMessage: [Function],
        Server: [Function],
        ServerResponse: [Function],
        createServer: [Function: createServer],
        get: [Function: get],
        request: [Function: request],
        maxHeaderSize: [Getter] },
     'https:':
      { Agent: [Function],
        globalAgent: [Agent],
        Server: [Function],
        createServer: [Function: createServer],
        get: [Function: get],
        request: [Function: request] } } } +0ms
  ring { status: 406,
  ring   statusText: 'Not Acceptable',
  ring   headers:
  ring    { date: 'Mon, 27 Jan 2020 22:45:15 GMT',
  ring      'content-type': 'text/html',
  ring      'transfer-encoding': 'chunked',
  ring      connection: 'close',
  ring      'set-cookie':
  ring       [ '__cfduid=XXXX; expires=Wed, 26-Feb-20 22:45:15 GMT; path=/; domain=.ring.com; HttpOnly; SameSite=Lax' ],
  ring      'cf-cache-status': 'DYNAMIC',
  ring      'expect-ct':
  ring       'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  ring      server: 'cloudflare',
  ring      'cf-ray': 'XXXX' },
  ring   config:
  ring    { url: 'https://oauth.ring.com/oauth/token',
  ring      method: 'post',
  ring      data:
  ring       '{"client_id":"ring_official_android","scope":"client","grant_type":"password","password":"XXXX","username":"XXXX"}',
  ring      headers:
  ring       { Accept: 'application/json, text/plain, */*',
  ring         'Content-Type': 'application/json',
  ring         '2fa-support': 'true',
  ring         '2fa-code': '',
  ring         hardware_id: 'XXXX',
  ring         'User-Agent': 'axios/0.19.1',
  ring         'Content-Length': 151 },
  ring      transformRequest: [ [Function: transformRequest] ],
  ring      transformResponse: [ [Function: transformResponse] ],
  ring      timeout: 0,
  ring      adapter: [Function: httpAdapter],
  ring      xsrfCookieName: 'XSRF-TOKEN',
  ring      xsrfHeaderName: 'X-XSRF-TOKEN',
  ring      maxContentLength: -1,
  ring      validateStatus: [Function: validateStatus] },
  ring   request:
  ring    ClientRequest {
  ring      _events:
  ring       [Object: null prototype] {
  ring         socket: [Function],
  ring         abort: [Function],
  ring         aborted: [Function],
  ring         error: [Function],
  ring         timeout: [Function],
  ring         prefinish: [Function: requestOnPrefinish] },
  ring      _eventsCount: 6,
  ring      _maxListeners: undefined,
  ring      output: [],
  ring      outputEncodings: [],
  ring      outputCallbacks: [],
  ring      outputSize: 0,
  ring      writable: true,
  ring      _last: true,
  ring      chunkedEncoding: false,
  ring      shouldKeepAlive: false,
  ring      useChunkedEncodingByDefault: true,
  ring      sendDate: false,
  ring      _removedConnection: false,
  ring      _removedContLen: false,
  ring      _removedTE: false,
  ring      _contentLength: null,
  ring      _hasBody: true,
  ring      _trailer: '',
  ring      finished: true,
  ring      _headerSent: true,
  ring      socket:
  ring       TLSSocket {
  ring         _tlsOptions: [Object],
  ring         _secureEstablished: true,
  ring         _securePending: false,
  ring         _newSessionPending: false,
  ring         _controlReleased: true,
  ring         _SNICallback: null,
  ring         servername: 'oauth.ring.com',
  ring         alpnProtocol: false,
  ring         authorized: true,
  ring         authorizationError: null,
  ring         encrypted: true,
  ring         _events: [Object],
  ring         _eventsCount: 8,
  ring         connecting: false,
  ring         _hadError: false,
  ring         _handle: [TLSWrap],
  ring         _parent: null,
  ring         _host: 'oauth.ring.com',
  ring         _readableState: [ReadableState],
  ring         readable: true,
  ring         _maxListeners: undefined,
  ring         _writableState: [WritableState],
  ring         writable: false,
  ring         allowHalfOpen: false,
  ring         _sockname: null,
  ring         _pendingData: null,
  ring         _pendingEncoding: '',
  ring         server: undefined,
  ring         _server: null,
  ring         ssl: [TLSWrap],
  ring         _requestCert: true,
  ring         _rejectUnauthorized: true,
  ring         parser: null,
  ring         _httpMessage: [Circular],
  ring         [Symbol(res)]: [TLSWrap],
  ring         [Symbol(asyncId)]: 110,
  ring         [Symbol(lastWriteQueueSize)]: 0,
  ring         [Symbol(timeout)]: null,
  ring         [Symbol(kBytesRead)]: 0,
  ring         [Symbol(kBytesWritten)]: 0,
  ring         [Symbol(connect-options)]: [Object] },
  ring      connection:
  ring       TLSSocket {
  ring         _tlsOptions: [Object],
  ring         _secureEstablished: true,
  ring         _securePending: false,
  ring         _newSessionPending: false,
  ring         _controlReleased: true,
  ring         _SNICallback: null,
  ring         servername: 'oauth.ring.com',
  ring         alpnProtocol: false,
  ring         authorized: true,
  ring         authorizationError: null,
  ring         encrypted: true,
  ring         _events: [Object],
  ring         _eventsCount: 8,
  ring         connecting: false,
  ring         _hadError: false,
  ring         _handle: [TLSWrap],
  ring         _parent: null,
  ring         _host: 'oauth.ring.com',
  ring         _readableState: [ReadableState],
  ring         readable: true,
  ring         _maxListeners: undefined,
  ring         _writableState: [WritableState],
  ring         writable: false,
  ring         allowHalfOpen: false,
  ring         _sockname: null,
  ring         _pendingData: null,
  ring         _pendingEncoding: '',
  ring         server: undefined,
  ring         _server: null,
  ring         ssl: [TLSWrap],
  ring         _requestCert: true,
  ring         _rejectUnauthorized: true,
  ring         parser: null,
  ring         _httpMessage: [Circular],
  ring         [Symbol(res)]: [TLSWrap],
  ring         [Symbol(asyncId)]: 110,
  ring         [Symbol(lastWriteQueueSize)]: 0,
  ring         [Symbol(timeout)]: null,
  ring         [Symbol(kBytesRead)]: 0,
  ring         [Symbol(kBytesWritten)]: 0,
  ring         [Symbol(connect-options)]: [Object] },
  ring      _header:
  ring       'POST /oauth/token HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json\r\n2fa-support: true\r\n2fa-code: \r\nhardware_id: XXXXXXXXX\r\nUser-Agent: axios/0.19.1\r\nContent-Length: 151\r\nHost: oauth.ring.com\r\nConnection: close\r\n\r\n',
  ring      _onPendingData: [Function: noopPendingOutput],
  ring      agent:
  ring       Agent {
  ring         _events: [Object],
  ring         _eventsCount: 1,
  ring         _maxListeners: undefined,
  ring         defaultPort: 443,
  ring         protocol: 'https:',
  ring         options: [Object],
  ring         requests: {},
  ring         sockets: [Object],
  ring         freeSockets: {},
  ring         keepAliveMsecs: 1000,
  ring         keepAlive: false,
  ring         maxSockets: Infinity,
  ring         maxFreeSockets: 256,
  ring         maxCachedSessions: 100,
  ring         _sessionCache: [Object] },
  ring      socketPath: undefined,
  ring      timeout: undefined,
  ring      method: 'POST',
  ring      path: '/oauth/token',
  ring      _ended: true,
  ring      res:
  ring       IncomingMessage {
  ring         _readableState: [ReadableState],
  ring         readable: false,
  ring         _events: [Object],
  ring         _eventsCount: 3,
  ring         _maxListeners: undefined,
  ring         socket: [TLSSocket],
  ring         connection: [TLSSocket],
  ring         httpVersionMajor: 1,
  ring         httpVersionMinor: 1,
  ring         httpVersion: '1.1',
  ring         complete: true,
  ring         headers: [Object],
  ring         rawHeaders: [Array],
  ring         trailers: {},
  ring         rawTrailers: [],
  ring         aborted: false,
  ring         upgrade: false,
  ring         url: '',
  ring         method: null,
  ring         statusCode: 406,
  ring         statusMessage: 'Not Acceptable',
  ring         client: [TLSSocket],
  ring         _consuming: true,
  ring         _dumped: false,
  ring         req: [Circular],
  ring         responseUrl: 'https://oauth.ring.com/oauth/token',
  ring         redirects: [] },
  ring      aborted: undefined,
  ring      timeoutCb: null,
  ring      upgradeOrConnect: false,
  ring      parser: null,
  ring      maxHeadersCount: null,
  ring      _redirectable:
  ring       Writable {
  ring         _writableState: [WritableState],
  ring         writable: true,
  ring         _events: [Object],
  ring         _eventsCount: 2,
  ring         _maxListeners: undefined,
  ring         _options: [Object],
  ring         _redirectCount: 0,
  ring         _redirects: [],
  ring         _requestBodyLength: 151,
  ring         _requestBodyBuffers: [],
  ring         _onNativeResponse: [Function],
  ring         _currentRequest: [Circular],
  ring         _currentUrl: 'https://oauth.ring.com/oauth/token' },
  ring      [Symbol(isCorked)]: false,
  ring      [Symbol(outHeadersKey)]:
  ring       [Object: null prototype] {
  ring         accept: [Array],
  ring         'content-type': [Array],
  ring         '2fa-support': [Array],
  ring         '2fa-code': [Array],
  ring         hardware_id: [Array],
  ring         'user-agent': [Array],
  ring         'content-length': [Array],
  ring         host: [Array] } },
  ring   data:
  ring    '<html>\r\n<head><title>406 Not Acceptable</title></head>\r\n<body bgcolor="white">\r\n<center><h1>406 Not Acceptable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' } +0ms
  ring Failed to fetch oauth token from Ring. Verify that your email and password are correct.  +1ms
Error: Failed to fetch oauth token from Ring. Verify that your email and password are correct. 
    at RingRestClient.<anonymous> (/home/ryan/src/third-party/ring/lib/api/rest-client.js:129:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/ryan/src/third-party/ring/lib/api/rest-client.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Environment
 - OS: Rasbian Buster, as well as Debian Buster
 - Node.js: v10.18.1 and v10.15.2
 - NPM: 6.13.4 and 5.8.0 
 - ring-client-api: 6.1.1

**Comment by dgreif** [comment]
Hey @rpavlik, thanks for following the issue template and providing great detail about what you have tried so far!  Unfortunately I'm unable to recreate the issue, and I don't see anything in the logs that stands out.  I'd recommend you try running the auth-cli using this command: `npx -p ring-client-api ring-auth-cli`.  Let me know if that works

**Comment by dgreif** [comment]
@rpavlik any updates?  I have not been able to reproduce this issue on my end.

**Comment by rpavlik** [comment]
Hey, sorry, I'm actually out of the country right now, so I haven't had a chance to tinker with this yet. I do plan on checking, but if I did it now I wouldn't be able to assure you that any errors I'm seeing aren't because of the way I'm doing remote access.

**Comment by dgreif** [comment]
@rpavlik any updates?

**Comment by rpavlik** [comment]
Seems to be working with your command (and the now mandatory 2fa)

**Comment by Nikorag** [comment]
Sorry to bump an old thread but it's caused by Ring blocking your source. If i run the command behind a public VPN like ExpressVPN i get the 406.
