### ISSUE TITLE
Authentication error, just happening this morning

### ISSUE THREAD

**Issue by david-olshefski** [dgreif/ring#271]
Just started seeing this now. Maybe I need to somehow refresh an authentication token?

(node:34605) UnhandledPromiseRejectionWarning: Error: Refresh token is not valid.  Unable to authenticate with Ring servers.
    at RingRestClient.getGrantData ([...]/doorbot/node_modules/ring-client-api/lib/api/rest-client.js:85:15)
    at RingRestClient.<anonymous> ([...]/doorbot/node_modules/ring-client-api/lib/api/rest-client.js:89:36)
    at Generator.next (<anonymous>)
    at [...]/doorbot/node_modules/ring-client-api/lib/api/rest-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/doorbot/node_modules/ring-client-api/lib/api/rest-client.js:4:12)
    at RingRestClient.getAuth ([...]/doorbot/node_modules/ring-client-api/lib/api/rest-client.js:88:16)
    at RingRestClient.<anonymous> ([...]/doorbot/node_modules/ring-client-api/lib/api/rest-client.js:113:33)
    at Generator.throw (<anonymous>)
    at rejected ([...]/doorbot/node_modules/ring-client-api/lib/api/rest-client.js:6:65)
(node:34605) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:34605) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by david-olshefski** [comment]
I just needed to generate a new token, as per:

https://github.com/dgreif/ring/wiki/Two-Factor-Auth

**Comment by mshepet** [comment]
I've been running into this same issue. I generate a refresh token and it works fine for about a day and then I start seeing the same errors as OP `Refresh token is not valid. Unable to authenticate with Ring servers.` If I regenerate a new token, it works fine but only lasts about a day. Could new tokens have a shorter lifespan now?

**Comment by dgreif** [comment]
@mshepet I haven't seen any issues with my refresh token, but it's possible that Ring changed something on their end.  Keep an eye on it and let me know if it's still happening over the next few days
