### ISSUE TITLE
Failed to reach Ring server at https://api.ring.com/clients_api/dings/active

### ISSUE THREAD

**Issue by donavanbecker** [dgreif/ring#276]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
Continuously getting `Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...`

### To Reproduce
 - Start Homebridge
 - Just continuously happening off an on.
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.
Ever since this error has been showing off and on, live stream has not been working.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
```
[3/31/2020, 9:25:02 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[3/31/2020, 9:25:07 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[3/31/2020, 9:25:08 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Trying again in 5 seconds...
[3/31/2020, 9:25:12 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[3/31/2020, 9:25:13 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Trying again in 5 seconds...
[3/31/2020, 9:25:18 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[3/31/2020, 9:25:19 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Trying again in 5 seconds...
[3/31/2020, 9:25:21 AM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/cb260x-54tjs-0.  Trying again in 5 seconds...
[3/31/2020, 9:25:24 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[3/31/2020, 9:25:24 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Trying again in 5 seconds...
[3/31/2020, 9:25:26 AM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/cb260x-54tjs-0.  Trying again in 5 seconds...
[3/31/2020, 9:25:31 AM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/cb260x-54tjs-0.  Trying again in 5 seconds...
[3/31/2020, 9:25:41 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Trying again in 5 seconds...
[3/31/2020, 9:25:41 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[3/31/2020, 9:25:41 AM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/cb260x-54tjs-0.  Trying again in 5 seconds...
[3/31/2020, 9:25:44 AM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/cb260x-54tjs-0.  Trying again in 5 seconds...
[3/31/2020, 9:25:53 AM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/cb260x-54tjs-0.  Trying again in 5 seconds...
[3/31/2020, 9:25:54 AM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/cb260x-54tjs-0.  Trying again in 5 seconds...
[3/31/2020, 9:25:57 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[3/31/2020, 9:25:57 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Trying again in 5 seconds...
```
### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

{
            "refreshToken": "xxxxxxxxxxxxxxxx",
            "hideLightGroups": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "debug": true,
            "platform": "Ring"
        }
```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: 12.16.1 
 - NPM: 6.14.4 
 - homebridge-ring: 7.2.1
 - homebridge: 0.4.54

**Comment by dgreif** [comment]
This happens if your internet is being flaky.  Could also be that Ring is limiting your request rate for some reason

**Comment by donavanbecker** [comment]
Okay I removed all logins from the ring app and have re issued a refresh token I will see if that helps. Weird that Live feed has stopped lately and haven't changed eero secure settings.

**Comment by donavanbecker** [comment]
```
[3/31/2020, 11:24:12 AM] [Ring] Ding 6810408630585465027 is expired (480).  Fetching a new ding and trying video stream again
```

this is been showing lately too and I haven't had anyone ring my doorbell. Maybe ring has changed something?

**Comment by donavanbecker** [comment]
```
[3/31/2020, 11:27:01 AM] [Ring] Preparing Live Stream for Side Door
[3/31/2020, 11:27:02 AM] [Ring] Waiting for stream data from Side Door (0.729s)
[3/31/2020, 11:27:12 AM] [Ring] Stopped Live Stream for Side Door
[3/31/2020, 11:27:12 AM] [Ring] ffmpeg stderr: [sdp @ 0x7fbce780be00] Could not find codec parameters for stream 1 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'pipe:':
  Metadata:
    title           : Talk
  Duration: N/A, bitrate: 64 kb/s
    Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
    Stream #0:1: Video: h264, none, 90k tbr, 90k tbn, 180k tbc

[3/31/2020, 11:27:12 AM] [Ring] ffmpeg stderr: Stream mapping:
  Stream #0:0 -> #0:0 (pcm_mulaw (native) -> aac (libfdk_aac))

[3/31/2020, 11:27:12 AM] [Ring] ffmpeg stderr: Finishing stream 0:0 without any data written to it.

[3/31/2020, 11:27:12 AM] [Ring] ffmpeg stderr: Output #0, rtp, to 'srtp://192.168.7.97:51799?localrtcpport=65052&pkt_size=188':
  Metadata:
    title           : Talk
[3/31/2020, 11:27:12 AM] [Ring] ffmpeg stderr: 
    encoder         : Lavf58.38.100
    Stream #0:0: Audio: aac (libfdk_aac) (ELD), 16000 Hz, mono, s16, 24 kb/s
    Metadata:
      encoder         : Lavc58.68.102 libfdk_aac

[3/31/2020, 11:27:12 AM] [Ring] ffmpeg stderr: [libfdk_aac @ 0x7fbce7809200] Trying to remove 512 samples, but the queue is empty

[3/31/2020, 11:27:12 AM] [Ring] ffmpeg stderr: size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    

[3/31/2020, 11:27:12 AM] [Ring] ffmpeg stderr: video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

[3/31/2020, 11:27:12 AM] [Ring] ffmpeg stderr: Exiting normally, received signal 15.

[3/31/2020, 11:27:12 AM] [Ring] ffmpeg exited with code 255
[3/31/2020, 11:27:21 AM] [Ring] ffmpeg stderr: pipe:: Operation timed out

[3/31/2020, 11:27:21 AM] [Ring] ffmpeg stderr: size=      75kB time=00:00:22.23 bitrate=  27.7kbits/s speed=0.555x    
video:0kB audio:64kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 16.873314%

[3/31/2020, 11:27:21 AM] [Ring] ffmpeg stderr: Exiting normally, received signal 15.

[3/31/2020, 11:27:21 AM] [Ring] ffmpeg exited with code 255
```

**Comment by donavanbecker** [comment]
Now receiving this:
```
[4/1/2020, 10:44:44 AM] [Ring] Request to https://app.ring.com/api/v1/mode/location/cb260x-54tjs-0 failed with status 502. Response body: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

(node:34610) UnhandledPromiseRejectionWarning: Error: Request failed with status code 502
    at createError (/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-ring/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:34610) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 937)
```

**Comment by veroled** [comment]
Hello, same problem, anyone solved?

**Comment by themick4u** [comment]
Same problem here today. Cannot load camera view in homekit either

**Comment by kkrankall** [comment]
Same problem here

### Screenshots/Logs
```
[1/27/2021, 4:24:02 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:04 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:05 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:06 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:06 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/timestamps.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:07 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:07 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:09 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:10 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:11 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:11 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/timestamps.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:12 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:13 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:14 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:15 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:17 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/timestamps.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:17 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/27/2021, 4:24:18 PM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
```

**Comment by Jericon** [comment]
+1

```
[1/29/2021, 00:39:31] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:32] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:36] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:37] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:37] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:41] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:42] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:42] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:47] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:47] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:47] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:52] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:52] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:52] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:57] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:57] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:39:57] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:40:02] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:40:02] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
[1/29/2021, 00:40:02] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
```

Looks like the HTTP Error Code "Enhance Your Calm" is Error code 420... It indicates a rate limit being hit.

https://evertpot.com/http/420-enhance-your-calm#:~:text=The%20420%20Enhance%20Your%20Calm,they%20were%20being%20rate%20limited.&text=The%20general%20idea%20is%20that,do%20something%20with%20the%20response.
