### ISSUE TITLE
Error connecting to API

### ISSUE THREAD

**Issue by jmac0027** [dgreif/ring#321]
After updating my Node.js to 10.19.0 and refreshing my token, I began receiving the following error. Any idea where to go from here?  Thank you in advance for any ideas!!!

[5/11/2020, 11:27:36 PM] [RingAlarm] Adding new accessory doorbell_v3 Front Door
[5/11/2020, 11:27:36 PM] [RingAlarm] Error connecting to API
[5/11/2020, 11:27:37 PM] [RingAlarm] TypeError: Cannot read property 'length' of undefined
    at StreamController.RTPStreamManagement (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:499:36)
    at new StreamController (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1375:5)
    at new CameraSource (/usr/local/lib/node_modules/homebridge-ring-alarm/homebridge/camera-source.js:32:38)
    at new Camera (/usr/local/lib/node_modules/homebridge-ring-alarm/homebridge/camera.js:14:110)
    at allDevices.forEach.device (/usr/local/lib/node_modules/homebridge-ring-alarm/homebridge/ring-alarm-platform.js:113:21)
    at Array.forEach (<anonymous>)
    at RingAlarmPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-ring-alarm/homebridge/ring-alarm-platform.js:91:28)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring-alarm/homebridge/ring-alarm-platform.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by dgreif** [comment]
based on your folder names, it looks like you are still running `homebridge-ring-alarm`.  That plugin was deprecated a long time ago, and everything has been moved to `homebridge-ring`. You need to update homebridge to version 1+ in order to run the latest `homebridge-ring` plugin.
