### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by hesto2** [dgreif/ring#336]
# Bug Report

### Describe the Bug
I'm attempting to run the recording example on my local machine but am greeted with the following error, has anyone else had an issue similar to this?
```
Starting Video...
(node:5955) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:780:11)
    at Socket._write (net.js:792:8)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at Socket.Writable.write (_stream_writable.js:316:11)
    at FfmpegProcess.start (/mnt/d/Dev/node/@hesto2/ring-worker/dist/node_modules/ring-client-api/lib/api/ffmpeg.js:76:23)
    at SipSession.<anonymous> (/mnt/d/Dev/node/@hesto2/ring-worker/dist/node_modules/ring-client-api/lib/api/sip-session.js:125:16)
    at Generator.next (<anonymous>)
```
### Environment

 - OS: WSL Windows 10
 - Node.js: 12.16.1
 - NPM: 6.13.4
 - ring-client-api: 8.2.0

**Comment by dgreif** [comment]
Looks like it's probably an issue with ffmpeg.  Can you try adding `ffmpegPath: require('ffmpeg-for-homebridge'),` to the config that you pass in to `RingApi`?  This will use a pre-packaged version of homebridge which should work in most environments

**Comment by dgreif** [comment]
`ffmpeg-for-homebridge` is used by default in v9.  As long as it installs properly, you shouldn't see this issue anymore
