### ISSUE TITLE
Error connecting to API

### ISSUE THREAD

**Issue by sushenmathur** [dgreif/ring#376]
# Bug Report
Getting error when attempting to initialise the plugin after the update
### To Reproduce
-Updated the plugin
- Restarted homebridge
 - See error

Error connecting to API
[6/24/2020, 12:15:50 AM] [Ring] Error: Cannot add a Service with the same UUID '00000112-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:276:17)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:683:14
    at Array.forEach (<anonymous>)
    at Accessory.handleUpdatedControllerServiceMap (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:681:38)
    at Accessory.configureController (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:607:14)
    at PlatformAccessory.configureController (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:136:34)
    at new Camera (/homebridge/node_modules/homebridge-ring/lib/homebridge/camera.js:30:19)
    at /homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:198:123
    at Array.forEach (<anonymous>)
    at RingPlatform.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:175:28)

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
![image](https://user-images.githubusercontent.com/21048866/85480999-532ffe00-b604-11ea-8ddb-d84475476403.png)

### Additional context
 Add any other context about the problem here.

### Environment

![image](https://user-images.githubusercontent.com/21048866/85481109-8c686e00-b604-11ea-8a7c-0f31da4cc78a.png)

**Comment by dgreif** [comment]
While I appreciate the information you provided in the template (screenshot for environment was a cool idea), you did not provide the following information that is needed to help solve this issue:

* Homebridge version (or hoobs version)
* `homebridge-ring` version
* `homebridge-ring` section of your config.json (minus refresh token)

**Comment by dgreif** [comment]
@sushenmathur are you able to provide the additional information, or has your issue gone away?

**Comment by sushenmathur** [comment]
@dgreif. its is resolved. Thank you
