### ISSUE TITLE
Error updating Ring plug-in (9.4.1)

### ISSUE THREAD

**Issue by rakgupta** [dgreif/ring#396]
# Bug Report

### Describe the Bug
Get the following error when updating the plug-in (using Cofig-UI-x, HB pre-configured image for RPi).
`DIR: /usr/local/lib
CMD: sudo -E -n npm install homebridge-ring@latest

npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "node_modules": node_modules is a blacklisted name

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-08T22_02_08_114Z-debug.log

Command failed. Please review log for details.`

### To Reproduce
Click on "update"

### Expected behavior
Update the plug-in

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
Detailed log:
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'homebridge-ring@latest'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.0
4 verbose npm-session 15f95a8658716d8b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-ring 233ms
8 http fetch GET 200 https://registry.npmjs.org/homebridge-ring/-/homebridge-ring-9.4.1.tgz 176ms
9 silly pacote tag manifest for homebridge-ring@latest fetched in 443ms
10 verbose stack Error: Invalid package name "node_modules": node_modules is a blacklisted name
10 verbose stack     at invalidPackageName (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:86:15)
10 verbose stack     at Result.setName (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:121:11)
10 verbose stack     at new Result (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:111:23)
10 verbose stack     at Function.resolve (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:58:15)
10 verbose stack     at computeVersionSpec (/usr/lib/node_modules/npm/lib/install/deps.js:320:21)
10 verbose stack     at Installer.normalizeCurrentTree (/usr/lib/node_modules/npm/lib/install.js:410:68)
10 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
10 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
10 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
10 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:368:5
10 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/iferr.js:3:64
10 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
10 verbose stack     at /usr/lib/node_modules/npm/node_modules/call-limit/call-limit.js:28:43
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:79:11)
11 verbose cwd /usr/local/lib
12 verbose Linux 4.19.97-v7l+
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "homebridge-ring@latest"
14 verbose node v12.18.0
15 verbose npm  v6.14.5
16 error code EINVALIDPACKAGENAME
17 error Invalid package name "node_modules": node_modules is a blacklisted name
18 verbose exit [ 1, true ]
`
### Homebridge Ring Config
version 9.4.0 is working

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment
<!-- ✍️edit: -->
 - OS: [e.g. Raspbian]
 - HB version: 1.1.1
  - Node.js Version | v12.16.2
-- Npm Version |v6.14.4

**Comment by rakgupta** [comment]
Moved to Hombridge - not a plugin issue
