### ISSUE TITLE
Refresh token is not valid.  Unable to authenticate with Ring servers.

### ISSUE THREAD

**Issue by fbernaly** [dgreif/ring#400]
# Bug Report

### Describe the Bug
 After updating to v9.5.0 I am getting this:

```
[11/07/2020, 20:43:56] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed:
[11/07/2020, 20:43:56] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:122:36)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:16)
    at RingRestClient.refreshAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:217:33)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:234:26)
    at Generator.throw (<anonymous>)
[11/07/2020, 20:43:56] [Ring] Error connecting to API
[11/07/2020, 20:43:56] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:122:36)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:16)
    at RingRestClient.refreshAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:217:33)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:234:26)
    at Generator.throw (<anonymous>)
```

I ran this to refresh the token, but after restarting homebridge I am still getting that
```
ring-auth-cli
```

Not able to control Ring devices in HomeKit app.

### Environment

 - OS:  Raspbian
 - Node.js: v13.12.0
 - NPM: 6.14.4
 - homebridge-ring: 9.5.0
 - homebridge: 1.1.1

**Comment by dgreif** [comment]
Please install the latest node 12 or node 14 and try again

**Comment by fbernaly** [comment]
Thanks, that worked!!!

**Comment by kudit** [comment]
Having the same issue with Node v14.1.0

Also macOS BigSur.

**Comment by dgreif** [comment]
Refresh tokens sometimes become invalid. You will need to generate a new refresh token and swap it in your config

**Comment by gondalez** [comment]
👋  I've been seeing this issue intermittently too in the homebridge logs.

A restart of homebridge fixes it, which at least helps prove the refresh token is still valid.

```
Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  
```

I wonder if it the credentials in the homebridge process somehow become corrupted/modified?

I usually notice it since it manifests as a visitor presses the doorbell but my homepods don't ring :)

This is the full stack trace:

```
[8/13/2021, 2:02:01 PM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/homebridge/node_modules/homebridge-ring/lib/api/rest-client.js:93:15)
    at RingRestClient.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/api/rest-client.js:97:36)
    at Generator.next (<anonymous>)
    at /homebridge/node_modules/homebridge-ring/lib/api/rest-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/homebridge/node_modules/homebridge-ring/lib/api/rest-client.js:4:12)
    at RingRestClient.getAuth (/homebridge/node_modules/homebridge-ring/lib/api/rest-client.js:96:16)
    at RingRestClient.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/api/rest-client.js:121:33)
    at Generator.throw (<anonymous>)
    at rejected (/homebridge/node_modules/homebridge-ring/lib/api/rest-client.js:6:65)
```

**Comment by ToracX** [comment]
Im having the same issue. Only work around is to automatically reboot homebridge.

is there a fix yet?
