### ISSUE TITLE
Doesn't work with iOS 14 Public Beta 2 - Error: bind EADDRINUSE

### ISSUE THREAD

**Issue by rlewandowski23** [dgreif/ring#401]
Homebridge v1.1.1 installed on Windows Server 2012 R2 Essentials
Node.js Version v12.18.2
Homebridge-config-ui-x v4.23.2
Homebridge-ring v9.5.0

Worked wonderful when my iPhone was running iOS 13.5.1.  Updated to iOS 14 public beta 2 and now I get the below when trying to access my ring camera in the Home app.  

Any way to fix it?

[7/11/2020, 3:13:45 PM] [Ring] Preparing Live Stream for Front Camera
[7/11/2020, 3:13:45 PM] [Ring] Failed to prepare stream for Front Camera (0.03s)
[7/11/2020, 3:13:45 PM] [Ring] Error: bind EADDRINUSE 0.0.0.0:50977
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 50977
}
(node:5184) UnhandledPromiseRejectionWarning: Error: bind EADDRINUSE 0.0.0.0:50977
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
(node:5184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5184) UnhandledPromiseRejectionWarning: Error: bind EADDRINUSE 0.0.0.0:50978
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
(node:5184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[7/11/2020, 3:13:56 PM] [Ring] Preparing Live Stream for Front Camera
[7/11/2020, 3:13:56 PM] [Ring] Failed to prepare stream for Front Camera (0.008s)
[7/11/2020, 3:13:56 PM] [Ring] Error: bind EADDRINUSE 0.0.0.0:50987
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 50987
}
(node:5184) UnhandledPromiseRejectionWarning: Error: bind EADDRINUSE 0.0.0.0:50987
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
(node:5184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:5184) UnhandledPromiseRejectionWarning: Error: bind EADDRINUSE 0.0.0.0:50988
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
(node:5184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[7/11/2020, 3:14:09 PM] [Ring] Preparing Live Stream for Front Camera
[7/11/2020, 3:14:09 PM] [Ring] Failed to prepare stream for Front Camera (0.009s)
[7/11/2020, 3:14:09 PM] [Ring] Error: bind EADDRINUSE 0.0.0.0:51005
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 51005
}
(node:5184) UnhandledPromiseRejectionWarning: Error: bind EADDRINUSE 0.0.0.0:51005
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
(node:5184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:5184) UnhandledPromiseRejectionWarning: Error: bind EADDRINUSE 0.0.0.0:51006
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
(node:5184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
[7/11/2020, 3:14:37 PM] [Ring] Snapshot failed to refresh after 70 attempts
[7/11/2020, 3:14:37 PM] [Ring] Failed to cache snapshot for Front Camera (42.128s), The camera currently reports that is it online #

**Comment by dgreif** [comment]
It’s really odd that you are consistently seeing this error. I see it occasionally, but never consistently. It is related to setting up for the stream locally on the server and shouldn’t have anything to do with the iOS version on your phone. I’d try restarting your server and try a few more streams.

**Comment by rlewandowski23** [comment]
That issue occured after a reboot.  But, then I rebooted again and suddenly it worked.  However, it would consistently have errors like the below.  I am restoring back to iOS 13.5.1 as it worked without errors when I was testing it.  I will let you know if it resolves these issues.

[7/11/2020, 3:14:37 PM] [Ring] Snapshot failed to refresh after 70 attempts
[7/11/2020, 3:14:37 PM] [Ring] Failed to cache snapshot for Front Camera (42.128s), The camera currently reports that is it online

[7/11/2020, 4:10:11 PM] [Ring] Failed to prepare stream for Front Camera (11.864s)
[7/11/2020, 4:10:11 PM] [Ring] Error: SIP Session has already ended
    at SipSession.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip-session.js:56:23)
    at Generator.next (<anonymous>)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip-session.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\admin\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip-session.js:4:12)
    at SipSession.start (C:\Users\admin\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip-session.js:50:16)
    at SipSession.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip-session.js:103:33)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\admin\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip-session.js:5:58)
    at runMicrotasks (<anonymous>)

**Comment by rlewandowski23** [comment]
I reloaded iOS 13.5.1 and it works perfectly.

[7/11/2020, 4:52:13 PM] Homebridge is running on port 51275.
[7/11/2020, 5:55:18 PM] [Ring] Preparing Live Stream for Front Camera
[7/11/2020, 5:55:20 PM] [Ring] Waiting for stream data from Front Camera (1.538s)
[7/11/2020, 5:55:20 PM] [Ring] Received stream data from Front Camera (1.761s)
[7/11/2020, 5:55:20 PM] [Ring] Streaming active for Front Camera
[7/11/2020, 5:55:48 PM] [Ring] Stopped Live Stream for Front Camera
[7/11/2020, 5:58:35 PM] [Ring] Preparing Live Stream for Front Camera
[7/11/2020, 5:58:36 PM] [Ring] Waiting for stream data from Front Camera (0.954s)
[7/11/2020, 5:58:36 PM] [Ring] Received stream data from Front Camera (1.117s)
[7/11/2020, 5:58:36 PM] [Ring] Streaming active for Front Camera
[7/11/2020, 5:58:43 PM] [Ring] Stopped Live Stream for Front Camera

I assume that homebridge uses my Apple as a HomeKit bridge?  Perhaps the AppleTV has to be updated to tvOS 14 for it to work properly with iOS 14?  Maybe that is why it wasn't working right...?

**Comment by dgreif** [comment]
Homebridge does use your apple tv as a streaming bridge, so it is possible that having it on a different version of tvOS than your phone would have caused issues.  The EADDRINUSE error should all be related to local ports on your homebridge server and not impacted by iOS or tvOS in any way.  Closing this for now since there are a number of users who have reported success with iOS 14 beta and it was likely due to your mismatched versions between tvOS and iOS
