### ISSUE TITLE
Refresh Token is not valid (despite using config-ui to obtain token)

### ISSUE THREAD

**Issue by danewallace** [dgreif/ring#406]
Hello, 

I ran into this issue out of the blue a couple of weeks ago. No changes to Ring account, app, or homebridge plugin. I've used the CLI method to get token before, and have also followed steps using config-ui-x to obtain a new one as a component isolation step. I am able to enter credentials, accept text message challenge, enter token, and restart Homebridge server (macOS), but have thus far been unable to resolve the issue. Log output below:

[7/13/2020, 5:54:04 PM] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed:
[7/13/2020, 5:54:04 PM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:122:36)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:16)
    at RingRestClient.refreshAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:217:33)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:234:26)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:25:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[7/13/2020, 5:54:04 PM] [Ring] Error connecting to API
[7/13/2020, 5:54:04 PM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:122:36)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:16)
    at RingRestClient.refreshAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:217:33)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:234:26)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:25:65)

**Comment by danewallace** [comment]
Additional info: 

Node: v14.1.0
NPM: v6.14.4

**Comment by dgreif** [comment]
This issue has been reported several times already. You just need to update your node version to 14.5.0 or 12.18.2

**Comment by danewallace** [comment]
Ah, thanks for the heads up. Didn't try 14.5.0 but 12.18.2 is working. Thanks for all your hard work and responsiveness!
