### ISSUE TITLE
Proposal: Show “Not Responding” in Home app when Ring API is inaccessible

### ISSUE THREAD

**Issue by smockle** [dgreif/ring#413]
# Feature Request

### Description

The following error was logged:
```
7/21/2020, 4:00:47 PM] [Ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  getaddrinfo ENOTFOUND oauth.ring.com.  Trying again in 5 seconds...
[7/21/2020, 4:02:05 PM] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed with status undefined. Response body: undefined
[7/21/2020, 4:02:05 PM] [Ring] Error connecting to API
[7/21/2020, 4:02:05 PM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/Users/clay/.config/yarn/global/node_modules/homebridge-ring/lib/api/rest-client.js:116:15)
    at RingRestClient.<anonymous> (/Users/clay/.config/yarn/global/node_modules/homebridge-ring/lib/api/rest-client.js:120:36)
    at Generator.next (<anonymous>)
    at /Users/clay/.config/yarn/global/node_modules/homebridge-ring/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/clay/.config/yarn/global/node_modules/homebridge-ring/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/Users/clay/.config/yarn/global/node_modules/homebridge-ring/lib/api/rest-client.js:119:16)
    at RingRestClient.<anonymous> (/Users/clay/.config/yarn/global/node_modules/homebridge-ring/lib/api/rest-client.js:143:33)
    at Generator.throw (<anonymous>)
    at rejected (/Users/clay/.config/yarn/global/node_modules/homebridge-ring/lib/api/rest-client.js:25:65)
```

The error itself is unremarkable—it’s probably an instance of #373, #374, or #397. I obtained a new refresh token and updated `homebridge-ring`, and things are working fine now.

But the incident made me realize something: Although Homebridge Ring was experiencing a fatal error, there was no indication anything was wrong in the Home app. All devices continued to show their last known states. When I repeatedly tapped a light in the Home app, the UI toggled between the “100%” (on) and “Off” states as if everything was working fine. But devices in my house were not actually being controlled, because Homebridge Ring couldn’t connect to the Ring API.

### Describe the solution you'd like

Several hours passed before I noticed the issue. I think it would be nice if–when Homebridge Ring is unable to connect to the Ring API–the plugin’s accessories showed “Not Responding” in the Home app, so fatal errors like this one are more obvious.

### Describe alternatives you've considered

I’m not sure which error messages are supported by the Home app. It’s possible there is a more specific/clear message than “Not Responding”. (Update 2020-11-20: From https://github.com/homebridge/HAP-NodeJS/pull/556, I found a list of [supported statuses](https://github.com/homebridge/HAP-NodeJS/blob/d70a1ba9fd8dbb6dba4ae4f8abae2766781cb643/src/lib/HAPServer.ts#L71-L84). `SERVICE_COMMUNICATION_FAILURE` seems to be the most appropriate.)

I have a few ideas about how the error which precipitated this could be approached (and, if I recall correctly, this has been discussed at length previously, in the aforementioned issues #373, #374, or #397 and elsewhere), but I’d like to scope discussion in this issue to error messages in the Home app.

**Comment by dgreif** [comment]
Thanks for the idea @smockle.  I'll look into it

**Comment by dgreif** [comment]
Haven't gotten around to this in a few years, and it doesn't look like there has been more requests for it. Thanks for the suggestion @smockle!
