### ISSUE TITLE
[Ring] Failed to reach Ring server 

### ISSUE THREAD

**Issue by paddy0furniture** [dgreif/ring#430]
# Bug Report

### Describe the Bug
 
I keep getting repeated errors
[Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  queryA EREFUSED app.ring.com.  Trying again in 5 seconds...

I have tried uninstalling and reinstalling as well as regenerating the refresh token many times.

### To Reproduce
 - Start Homebridge
Error appears after restart and every 5 seconds after
 - See error
Debug provided this:
[8/14/2020, 06:16:05] [Ring] DNS Cache for app.ring.com: {"errno":"EREFUSED","code":"EREFUSED","syscall":"queryA","hostname":"app.ring.com"}
[8/14/2020, 06:16:07] [Config] Changes to config.json saved.
[8/14/2020, 06:16:10] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  queryA EREFUSED app.ring.com.  Trying again in 5 seconds...
[8/14/2020, 06:16:10] [Ring] RequestError: queryA EREFUSED app.ring.com
    at PromisableRequest._makeRequest (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:1098:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at QueryReqWrap.onresolve [as oncomplete] (internal/dns/promises.js:174:17) {
  code: 'EREFUSED',
  timings: undefined
### Expected behavior
 A clear and concise description of what you expected to happen.
I used to get ring devices and a working camera within homekit

### Screenshots/Logs
[8/14/2020, 06:16:05] [Ring] DNS Cache for app.ring.com: {"errno":"EREFUSED","code":"EREFUSED","syscall":"queryA","hostname":"app.ring.com"}
[8/14/2020, 06:16:07] [Config] Changes to config.json saved.
[8/14/2020, 06:16:10] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  queryA EREFUSED app.ring.com.  Trying again in 5 seconds...
[8/14/2020, 06:16:10] [Ring] RequestError: queryA EREFUSED app.ring.com
    at PromisableRequest._makeRequest (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:1098:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at QueryReqWrap.onresolve [as oncomplete] (internal/dns/promises.js:174:17) {
  code: 'EREFUSED',
  timings: undefined

### Additional context
 This plugin has worked in the past for me.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [Raspbian GNU/Linux]
 - Node.js: [v12.18.2] 
 - NPM: [6.14.5] 
 - homebridge-ring: [v9.7.3]
 - homebridge: [1.1.2]
 - hoobs: [N/A]

**Comment by paddy0furniture** [comment]
I upgraded raspian, rebooted and reinstalled the plugin and it appears to be working again.
