### ISSUE TITLE
Request to https://api.ring.com/clients_api/dings/active failed:

### ISSUE THREAD

**Issue by veroled** [dgreif/ring#450]
# Bug Report  

9/16/2020, 14:47:42] [Ring] Request to https://api.ring.com/clients_api/dings/active failed:
[9/16/2020, 14:47:42] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:118:15)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:122:36)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:121:16)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:146:33)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:25:65)

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
Looks like your refresh token expired: `Refresh token is not valid`.  If you have `homebridge-config-ui-x`, you can just delete everything in the `Refresh Token` field.  Otherwise, follow the directions in https://github.com/dgreif/ring/wiki/Refresh-Tokens to generate a new refresh token.

**Comment by dgreif** [comment]
Did you get this straightened out @veroled ?

**Comment by dgreif** [comment]
Closing due to lack of response
