### ISSUE TITLE
Crashes Homebridge

### ISSUE THREAD

**Issue by jmac0027** [dgreif/ring#455]
# Bug Report

### Describe the Bug
For months I've been having issues with Ring crashing my Homebridge.  Once I restart it works fine for about a day, sometimes less.  When restarting I always get this error:  
[9/18/2020, 19:59:18] [Ring] 404 from endpoint https://api.ring.com/clients_api/ring_devices
[9/18/2020, 19:59:18] [Ring] Session hardware_id not found.  Creating a new session and trying again.

This error has continued even with a completely fresh install of of Pi OS and homebridge.  At my wits end.  Love the Ring plugin but it making Homebridge unstable.  Thank you for the plugin and even more thanks for any help.

JM

### To Reproduce
 - Start Homebridge
 - See attached log

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

            "refreshToken": "eyJhbGciOiJIUzUxMiIsImp...,
            "hideUnsupportedServices": true,
            "debug": true,
            "platform": "Ring"

```

### Environment

 - OS: Raspbian
 - Node.js: 12.18.3
 - NPM: 6.14.8
 - homebridge-ring: 9.9.0
 - homebridge: 1.2.2
[homebridge.log.txt](https://github.com/dgreif/ring/files/5249049/homebridge.log.txt)

 - hoobs: N/A

**Comment by dgreif** [comment]
The "Creating a new session" log is not actually an error so much as an informational log. It should definitely not be crashing your entire homebridge server. Is that the last log before it crashes each time, or do you just happen to see that after each restart? Do you have other plugins installed that could be causing it to crash? Please double check your logs to see if there are any other errors.

**Comment by jmac0027** [comment]
Good day dgreif

I am running the following plugins along with Ring:
Config UI X
Wink3
Samsung Tizen
MyQ
Camera FFmpeg
Ewelink
Tplink Smarthome
Xbox Tv

When looking at the main homebridge log, I seldom have any errors showing for plugins other than Ring.  Is the another log I should be reviewing?  What suggestions do you recommend to debug?  I've included a redacted version of my config to this post if it helps.


[config.pdf](https://github.com/dgreif/ring/files/5250151/config.pdf)


As shown in the log file attached in original post:
I notice that every time the homebridge stops running, the log also stops showing Ring data over and over again.  Similar to:

[9/18/2020, 16:35:24] [Ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  Session closed without receiving a SETTINGS frame.  Trying again in 5 seconds...
[9/18/2020, 16:35:24] [Ring] RequestError: Session closed without receiving a SETTINGS frame
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:891:25)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/usr/local/lib/node_modules/homebridge-ring/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at ClientRequest.flushHeaders (/usr/local/lib/node_modules/homebridge-ring/node_modules/http2-wrapper/source/client-request.js:363:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ClientHttp2Session.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/http2-wrapper/source/agent.js:396:22)
    at Object.onceWrapper (events.js:421:28)
    at ClientHttp2Session.emit (events.js:315:20)
    at emitClose (internal/http2/core.js:1016:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'HTTP2WRAPPER_NOSETTINGS',
  timings: {
    start: 1600472062976,
    socket: undefined,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1600472124903,
    abort: undefined,
    phases: {
      wait: undefined,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 61927
    }
  }
}

**Comment by dgreif** [comment]
@jmac0027 Sorry I missed the attached log in your original post. Anything weird in your network setup that could be causing random HTTP2 failures? That `Session closed without receiving a SETTINGS frame` is something I have never seen before, and can't find anything with a quick search.  That error doesn't look like it is crashing your whole bridge, but may be causing your Ring accessories to stop functioning.  I'd try restarting your router and homebridge server to see if you can get that error cleared up.

**Comment by jbittner1002** [comment]
Not sure if this applies but Amazon has made some major changes in the past week. First they no longer accept TLS1.0...must be TLS1.2, Second, they are using wildcard certs now and third they are using forward-slashes in the session-id.
The forward-slashes in the session-id are causing me issues. (Not homebridge related, Asterisk does not like the forward-slashes.) I now have to figure out a way to use a B2BUA to get it to work.

**Comment by dgreif** [comment]
@jmac0027 any new updates?

**Comment by dgreif** [comment]
Closing due to lack of response
