### ISSUE TITLE
Latest update crashes homebridge, error persists after rollback/uninstall-reinstall

### ISSUE THREAD

**Issue by Bahrovski** [dgreif/ring#500]
Latest update (9.12.6) crashes homebridge with following error:

[11/25/2020, 6:45:22 PM] ====================
[11/25/2020, 6:45:22 PM] ERROR LOADING PLUGIN homebridge-ring:
[11/25/2020, 6:45:22 PM] TypeError: Cannot assign to read only property 'toString' of object '#<Object>'
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
[11/25/2020, 6:45:22 PM] ====================
[11/25/2020, 6:45:22 PM] Loading 2 platforms...
[11/25/2020, 6:45:22 PM] [Config] Initializing config platform...
[11/25/2020, 6:45:22 PM] [Config] Running in Service Mode
[11/25/2020, 6:45:22 PM] Error loading platform requested in your config.json at position 2
[11/25/2020, 6:45:22 PM] Error: The requested platform 'Ring' was not registered by any plugin.
    at [object Object]
    at [object Object]
    at Array.forEach (<anonymous>)
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
[11/25/2020, 6:45:22 PM] Got SIGTERM, shutting down Homebridge...
[11/25/2020, 6:45:27 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[11/25/2020, 6:45:32 PM] [HB Supervisor] Restarting Homebridge...

Error persists after downgrade, even uninstall-reinstall will cause the errors to come back.. Only solution is to uninstall Ring plugin for now..

Mac mini - macOS Mojave
Node: 14.15.1
Npm: 6.14.9
Homebridge: 1.1.6

Other plugins installed: Homebridge UI

**Comment by johnray** [comment]
Same issue here.  Wish I had seen this 3 minutes ago! Rollbacks don't help.

Only difference is node 12.12.0.

**Comment by Bahrovski** [comment]
Yes I had node v12 also, I just updated to v14 thinking it might solve the issue, but it didn't..

**Comment by johnray** [comment]
I was able to make it at least start with a rollback to homebridge-ring@9.9.0 - but it doesn't appear to actually be /working/ ... so there's that.

**Comment by Corvetteguy19** [comment]
Same thing for me.  I did a system restore and loaded the previous version but in HK it’s not loading any video for me.

**Comment by Bahrovski** [comment]
Apparently many others are facing similar errors: https://github.com/oznu/homebridge-config-ui-x/issues/969

and many other threads on reddit too in the past few hours.. So maybe it's not Ring-Plugin related but a dependency that got updated at the same time?

**Comment by Crox77** [comment]
Just logged into the Ring app and my doorbell says offline!

**Comment by dgreif** [comment]
AWS is having issues, causing an outage for Ring and other platforms. Please see https://status.ring.com/ for updated status.

**Comment by Bahrovski** [comment]
I understand that Ring services are down, but it shouldn't crash Homebridge, this is I believe a different issue?

**Comment by johnray** [comment]
> I understand that Ring services are down, but it shouldn't crash Homebridge, this is I believe a different issue?

What he said :)  - Seems like a pretty hard way to fail for auth/connection issues... but fingers crossed that it IS the issue.

**Comment by Crox77** [comment]
So I removed 3 platforms from my config and HB started Ring, surepetcare and sky q however my broad link rm’s kept popping up in my log saying unable to ping and when I tried to use then HB crashed added the 3 platforms back to the config and HB won’t start so it seems it is the AWS issue screwing it all up

**Comment by Crox77** [comment]
11/25/2020, 7:17:20 PM] ERROR LOADING PLUGIN homebridge-ring:
[11/25/2020, 7:17:20 PM] TypeError: Cannot assign to read only property 'toString' of object '#<Object>'
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
[11/25/2020, 7:17:20 PM] ====================
[11/25/2020, 7:17:23 PM] ====================
[11/25/2020, 7:17:23 PM] ERROR LOADING PLUGIN homebridge-sky-q:
[11/25/2020, 7:17:23 PM] TypeError: Cannot assign to read only property 'toString' of object '#<Cookie>'
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
[11/25/2020, 7:17:23 PM] ====================
[11/25/2020, 7:17:24 PM] ====================
[11/25/2020, 7:17:24 PM] ERROR LOADING PLUGIN homebridge-sure-petcare-platform:
[11/25/2020, 7:17:24 PM] TypeError: Cannot assign to read only property 'toString' of object '#<Cookie>'
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
[11/25/2020, 7:17:24 PM] ====================
[11/25/2020, 7:17:24 PM] Loading 7 platforms...
[11/25/2020, 7:17:24 PM] [AppleTvNowPlayingPlatform] Initializing AppleTvNowPlayingPlatform platform...
[11/25/2020, 7:17:24 PM] Error loading platform requested in your config.json at position 2
[11/25/2020, 7:17:25 PM] Error: The requested platform 'SurePetcare' was not registered by any plugin.
    at [object Object]
    at [object Object]
    at Array.forEach (<anonymous>)
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
[11/25/2020, 7:17:25 PM] Got SIGTERM, shutting down Homebridge...
[11/25/2020, 7:17:31 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[11/25/2020, 7:17:36 PM] [HB Supervisor] Restarting Homebridge...
[11/25/2020, 7:17:36 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[11/25/2020, 7:17:36 PM] [HB Supervisor] Started Homebridge v1.1.6 with PID: 10888

**Comment by Bahrovski** [comment]
Ok I was able to fix it by rolling back Homebridge-UI to version 4.32.0

Once you downgrade Homebridge-UI everything starts working again..

**Comment by Crox77** [comment]
> Ok I was able to fix it by rolling back Homebridge-UI to version 4.32.0
> 
> Once you downgrade Homebridge-UI everything starts working again..

Can you remind me of the command line to downgrade please?

**Comment by Bahrovski** [comment]
npm uninstall -g homebridge-config-ui-x && npm install -g homebridge-config-ui-x@4.32.0

But I believe it's easier for you to just downgrade from the UI itself.. Just click the rewind button next to plugin of Homebridge-UI and select the version 4.32.0

**Comment by Crox77** [comment]
Thanks tried that but still the same error

**Comment by johnray** [comment]
The downgrade of homebridge-config-ui-x DID work for me.  Thanks @Bahrovski! Updated Ring plugin and everything is still running.

**Comment by Bahrovski** [comment]
@johnray, Glad I could help!

@Crox77 it’s weird that it didnt work for you, are you sure you downgraded with a clean install to the UI version 4.32.0? Maybe a reboot after the downgrade would help too?

**Comment by Crox77** [comment]
Hi yes mate I did the downgrade correct, not tried a reboot though, don’t know if it makes any difference me running HB on my iMac?

**Comment by Bahrovski** [comment]
I’m running mine on a mac mini, so we basically have the same setup.. Try this maybe it works for you: https://github.com/oznu/homebridge-config-ui-x/issues/969#issuecomment-733905048

**Comment by skanico** [comment]
25/11/2020 à 21:21:29 Error loading plugin "homebridge-ring"
25/11/2020 à 21:21:29 TypeError: Cannot assign to read only property 'toString' of object '#<Object>'
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/ip/lib/ip.js:63:13)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/stun/src/node_modules/attributes/stun-address-attribute.js:10:12)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/stun/src/node_modules/lib/attributes.js:5:30)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
25/11/2020 à 21:21:29 Loaded plugin 'homebridge-ring'
25/11/2020 à 21:21:29 Loading 2 platforms...
25/11/2020 à 21:21:29 [melcloud2] Initializing melcloud2 platform...
25/11/2020 à 21:21:29 [melcloud2] Fetching Melcloud devices...
25/11/2020 à 21:21:29 Error loading platform requested in your config.json at position 2
25/11/2020 à 21:21:29 Error: The requested platform 'Ring' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
25/11/2020 à 21:21:29 Got SIGTERM, shutting down Bridge...

Raspberry Pi 4B
HOOBS Version 3.2.10
Node Version 12.19.0

**Comment by Bahrovski** [comment]
@Crox77 try this also:

sudo npm uninstall axios

sudo npm install axios@'0.19.2'

**Comment by patrickbruckner** [comment]
Having the same issues here.
