### ISSUE TITLE
Ring plugin has stopped functioning and disables Hoobs

### ISSUE THREAD

**Issue by frios** [dgreif/ring#517]
Ring plug-in crashes on load in Hoobs. Terminates Bridge
```
12/3/2020, 1:40:01 PM Error loading platform requested in your config.json at position 5
12/3/2020, 1:40:01 PM Error: The requested platform 'Ring' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12/3/2020, 1:40:01 PM Got SIGTERM, shutting down Bridge...
```

This has been happening for at least 2 versions now.  Currently using version 9.12.7 of plugin with version 3.3.1 of Hoobs. When uninstalled, Hoobs loads and operates as expected.

**Comment by dgreif** [comment]
There should be another error further up in the logs.  Not sure what it would be, but this error just indicates something else failed above.

**Comment by frios** [comment]
Is this it?

```
Error loading plugin "homebridge-ring"
12/3/2020, 1:40:01 PM TypeError: Cannot assign to read only property 'toString' of object '#<Object>'
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/ip/lib/ip.js:63:13)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/stun/src/node_modules/attributes/stun-address-attribute.js:10:12)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/stun/src/node_modules/lib/attributes.js:5:30)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
```

**Comment by dgreif** [comment]
That _may_ be it.  Make sure you are on the latest version of HOOBS.

**Comment by frios** [comment]
Yes I am on the latest version of Hoobs.

**Comment by dgreif** [comment]
Which other plugins do you have installed?

**Comment by frios** [comment]
Node Alarm Dot Com
Platform Orbit
Sleepiq
Tplink Smarthome

**Comment by dgreif** [comment]
@frios I'm not sure what else I can do to help here.  Without any logs with errors, I have nothing to go off of.  I suggest you reach out to hoobs support and see if they have any ideas

**Comment by dgreif** [comment]
@frios did you ever get this figured out or find more errors in your logs?
