### ISSUE TITLE
Started getting this error today, not entirely sure what it means

### ISSUE THREAD

**Issue by QuiveryNut** [dgreif/ring#526]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
When I try to view my Ring Peephole Cam stream in the Home app, i get the error below, and the stream does not load and becomes unresponsive.
### To Reproduce
 - Start Homebridge
 - Attempt to ... view the Ring Video Stream in the Home app
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.
The stream loads in 3-6 seconds and is live.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
```
[12/17/2020, 1:03:10 AM] [Ring] Preparing Live Stream for Apartment Door
[12/17/2020, 1:03:11 AM] [Ring] Stream Prepared for Apartment Door (1.38s)
[12/17/2020, 1:03:12 AM] [Ring] Received stream data from Apartment Door (1.544s)
[12/17/2020, 1:03:12 AM] [Ring] Streaming active for Apartment Door
[12/17/2020, 1:03:12 AM] [Ring] Stopped Live Stream for Apartment Door
[12/17/2020, 1:03:12 AM] TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null
    at Function.from (buffer.js:333:9)
    at RTPStreamManagement._handleSelectedStreamConfigurationWrite (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:602:25)
    at Characteristic.emit (events.js:315:20)
    at Characteristic.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1439:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1281:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
```
### Additional context
 Add any other context about the problem here.
This just started today after using for three days.
### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

If I'm not mistaken its just a refresh token.

```

### Environment

 - OS: Raspbian
 - Node.js: v14.15.1 
 - NPM: 6.14.9 
 - homebridge-ring: v9.12.8
 - homebridge: v1.1.6 and v1.1.7
 - hoobs: N/A

**Comment by dgreif** [comment]
Looks like the error is coming from this line: https://github.com/homebridge/HAP-NodeJS/blob/d1a49b97c974ad91465078f712ea3a3b8d773f2d/src/lib/camera/RTPStreamManagement.ts#L602.  This line is actually triggered from the HomeKit side if I'm not mistaken, so isn't something the plugin should be causing issues with.  Are you on a beta OS version on any of your apple devices by chance?

**Comment by dgreif** [comment]
@QuiveryNut any updates?

**Comment by raiubreaksthings** [comment]
This might be untreated but I am also noting a weird error after testing 2 way audio. 
running HOOBS on MacBook air 

[1/2/2021, 8:16:29 PM] [Ring] audio stun error
[1/2/2021, 8:16:29 PM] [Ring] Error: timeout
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/stun/src/node_modules/net/request.js:184:38)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
