### ISSUE TITLE
Failed to cache snapshot / Homebridge

### ISSUE THREAD

**Issue by HomekitFresh** [dgreif/ring#535]
# Bug Report
I consistently get errors in the log file, especially whenever my ring detects motion.

### Describe the Bug
First and foremost, thank you for the plugin and the integration of RING into Homekit. However, I have 1-2 problems with the whole issue.

From time to time it happens (see 2nd logfile) that I want to watch a live video (camera) via the Homekit-App (original Apple), but only the loading bar turns and then I get the error message as shown in the log. 

Another problem is that I get a lot of error messages in the log about Snapshot, even though I have disabled the function.

### Expected behavior
I would like to go into my Homekit app normally, click on the camera and see a live image/video. 

### Screenshots/Logs

[28/12/2020, 23:16:23] [Ring] Haustür Detected Motion
[28/12/2020, 23:17:07] [Ring] Snapshot for Haustür failed to refresh after 70 attempts.  This is normal behavior since this camera is unable to capture snapshots while streaming
[28/12/2020, 23:17:07] [Ring] Failed to cache snapshot for Haustür (44.45s), The camera currently reports that it is online
[28/12/2020, 23:17:07] [Ring] Failed to cache snapshot for Haustür (44.442s), The camera currently reports that it is online

**OTHER**

[29/12/2020, 00:25:50] [Ring] Preparing Live Stream for Haustür
[29/12/2020, 00:25:51] [Ring] Stream Prepared for Haustür (1.458s)
[29/12/2020, 00:25:51] [Ring] Streaming active for Haustür
[29/12/2020, 00:26:20] [Ring] Stopped Live Stream for Haustür
[29/12/2020, 00:26:31] [Ring] Snapshot for Haustür failed to refresh after 70 attempts.  This is normal behavior since this camera is unable to capture snapshots while streaming
[29/12/2020, 00:26:31] [Ring] Failed to cache snapshot for Haustür (43.145s), The camera currently reports that it is online

### Homebridge Ring Config
{
            "refreshToken": "XXXXXXXXXXXXXXXXXXXXXX",
            "avoidSnapshotBatteryDrain": false,
            "platform": "Ring"

### Environment
 - OS: Homebridge
 - Node.js: v14.15.3
 - NPM: v6.14.9
 - homebridge-ring: v9.12.8
 - homebridge: v1.1.7

**Comment by dgreif** [comment]
The snapshot logs are probably happening because your camera has a battery.  See https://github.com/dgreif/ring/wiki/Snapshot-Limitations for full details.  Disabling the 24x7 snapshots in the Ring app does not change whether or not the homebridge plugin will try to fetch snapshots.  Snapshots are requested by the Home app whenever you have a camera in view.

Regarding the live stream some times timing out, the second log appears to be a normal, successful live stream.  If the stream did not reach your phone/ipad, it's likely network related on your end.  Make sure your homebridge server, home hub (apple tv, homepod), and phone/ipad have a clear network path to talk to each other.

**Comment by dgreif** [comment]
@HomekitFresh what type of router do you have?  If it's an Eero, check out the info here: https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Fix-Eero-Router-Internet-and-DNS-Connectivity-Issues

**Comment by HomekitFresh** [comment]
> The snapshot logs are probably happening because your camera has a battery. See https://github.com/dgreif/ring/wiki/Snapshot-Limitations for full details. Disabling the 24x7 snapshots in the Ring app does not change whether or not the homebridge plugin will try to fetch snapshots. Snapshots are requested by the Home app whenever you have a camera in view.
> 
> Regarding the live stream some times timing out, the second log appears to be a normal, successful live stream. If the stream did not reach your phone/ipad, it's likely network related on your end. Make sure your homebridge server, home hub (apple tv, homepod), and phone/ipad have a clear network path to talk to each other.

**Hello dgreif,**

first of all I wish you a happy new year and thank you for your feedback.

Regarding your feedback: I use the Ring Video Doorbell 3, which has a battery permanently connected (there is no other option according to my information), but is also wired in parallel to my house with the two standard cables.

Actually, I do not want to use the function of snapshots. I just want my camera to function as a motion detector on one side (allowing me to start automations) and on the other side I want my camera to either notify me via push (Homekit) when motion has been detected or I want my camera to call me when someone has ring the doorbell.

If I understood you and the link correctly, the errors should only occur when using a Ring Video Doorbell on battery only - but that's not the case for me. 

Regarding your second question: I am a customer of the German Telekom and also use their router, the current model is the Speedport Smart 3.

Generally, I would say that if I call the camera 10 times, I get a picture directly on 7 attempts and on the other 3 attempts the camera loads and loads without me getting a picture.

For example, a few minutes ago I didn't get a picture again, but a few minutes later it worked. In the log this time I get the following info:


[01/01/2021, 17:51:49] [Ring] Preparing Live Stream for front door.
[01/01/2021, 17:51:51] [Ring] Stream Prepared for Front Door (1.588s)
[01/01/2021, 17:51:51] [Ring] Streaming active for front door
[01/01/2021, 17:51:51] [Ring] Received stream data from front door (1.88s)
[01/01/2021, 17:51:52] [Ring] Stopped Live Stream for front door
(node:29111) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
    at SipCall.request (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
    at SipCall.sendKeyFrameRequest (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
    at SipCall.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
    at generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
(node:29111) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
[01/01/2021, 17:52:01] [Ring] Request to https://api.ring.com/clients_api/snapshots/timestamps failed with status 504. Response body: {"error": "Gateway Timeout", "status_code":504}
[01/01/2021, 17:52:01] [Ring] Response code 504 (Gateway Time-out)
[01/01/2021, 17:52:01] [Ring] Failed to cache snapshot for front door (13.39s), The camera currently reports that it is online
[01/01/2021, 17:53:37] [Ring] Preparing Live Stream for Front Door
[01/01/2021, 17:53:39] [Ring] Stream Prepared for Front Door (1.551s)
[01/01/2021, 17:53:39] [Ring] Streaming active for front door
[01/01/2021, 17:53:39] [Ring] Received stream data from front door (1.631s)
[01/01/2021, 17:54:00] [Ring] Stopped Live Stream for Front Door


If there is any solution or explanation to my mentioned "problems", it would be perfect.

Thanks and best regards

**Comment by HomekitFresh** [comment]
FYI, I just saw that the plugin from you (Ring) suggested an update, maybe the error had to do with that? I have just installed the update.

**Comment by dgreif** [comment]
The snapshot limitations exist on any camera that has a battery, regarless of whether or not you hardwire it.  Since it _has_ a battery, it can't pull a snapshot while streaming. 

The live stream still seem network related.  If it works _sometimes_ then it's working and any failures are probably due to your network.  Nothing else I can do to make it work better unfortunately
