### ISSUE TITLE
Can't get refresh token

### ISSUE THREAD

**Issue by dmarshall20** [dgreif/ring#536]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

Can't get refresh tokens after hoobs update.

### To Reproduce
 - Create an `ApiClient`
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - ring-client-api: [e.g 6.0.3]

HOOBS listening on port 80.
No plugins installed.
Bridge is running on port 51826.

> ffmpeg-for-homebridge@0.0.9 install /root/.hoobs/node_modules/ffmpeg-for-homebridge
> node install.js
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

ffmpeg has been downloaded to /root/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg
Thank you for using https://github.com/homebridge/ffmpeg-for-homebridge
+ homebridge-ring@9.12.8
added 162 packages from 143 contributors in 80.533s

20 packages are looking for funding
  run `npm fund` for details
Plugin "homebridge-ring" installed.
Got SIGINT, shutting down Bridge...
Loaded plugin 'homebridge-ring'
[12/29/2020, 6:51:28 PM] Registering platform 'homebridge-ring.Ring'
Loading 1 platforms...
[Ring] Initializing Ring platform...
Bridge is running on port 51826.
(node:6184) UnhandledPromiseRejectionWarning: Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
at RingRestClient.getGrantData (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:120:15)
at RingRestClient.<anonymous> (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:124:36)
at Generator.next (<anonymous>)
at /root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:27:71
at new Promise (<anonymous>)
at __awaiter (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:23:12)
at RingRestClient.getAuth (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:123:16)
at new RingRestClient (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:100:33)
at new RingApi (/root/.hoobs/node_modules/homebridge-ring/lib/api/api.js:26:27)
at RingPlatform.<anonymous> (/root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:147:53)
at Generator.next (<anonymous>)
at /root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:8:71
at new Promise (<anonymous>)
at __awaiter (/root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:4:12)
at RingPlatform.connectToApi (/root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:146:16)
at HomebridgeAPI.<anonymous> (/root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:133:18)
(node:6184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed:
(node:6184) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:120:15)
    at RingRestClient.<anonymous> (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:124:36)
    at Generator.next (<anonymous>)
    at /root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:123:16)
    at new RingRestClient (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:100:33)
    at new RingApi (/root/.hoobs/node_modules/homebridge-ring/lib/api/api.js:26:27)
    at RingPlatform.<anonymous> (/root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:147:53)
    at Generator.next (<anonymous>)
    at /root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:4:12)
    at RingPlatform.connectToApi (/root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:146:16)
    at HomebridgeAPI.<anonymous> (/root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:133:18)
[Ring] Error connecting to API
[Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:120:15)
    at RingRestClient.<anonymous> (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:124:36)
    at Generator.next (<anonymous>)
    at /root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:123:16)
    at new RingRestClient (/root/.hoobs/node_modules/homebridge-ring/lib/api/rest-client.js:100:33)
    at new RingApi (/root/.hoobs/node_modules/homebridge-ring/lib/api/api.js:26:27)
    at RingPlatform.<anonymous> (/root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:147:53)
    at Generator.next (<anonymous>)
    at /root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:4:12)
    at RingPlatform.connectToApi (/root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:146:16)
    at HomebridgeAPI.<anonymous> (/root/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:133:18)

**Comment by dgreif** [comment]
You need to generate a new refresh token.  You can clear out the refresh token in the HOOBS UI and then it should walk you through getting a new one.

**Comment by dmarshall20** [comment]
> You need to generate a new refresh token. You can clear out the refresh token in the HOOBS UI and then it should walk you through getting a new one.

My problem is that I can't enter my email prior to being prompted for my password.

hoobs@hoobs:/home/hoobs/.hoobs/etc $ npx -p ring-client-api ring-auth-cli
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
This CLI will provide you with a refresh token which you can use to configure ring-client-api and homebridge-ring.
Email: 
Password:

**Comment by dgreif** [comment]
That's a really odd issue.  If you are on the latest version of the HOOBS UI, you should be able to enter your account info in the UI instead of using the CLI

**Comment by dmarshall20** [comment]
I am on 3.3.1 node version 12.16.3 . Where on the HOOBS UI would I enter the information?
