### ISSUE TITLE
Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

### ISSUE THREAD

**Issue by donavanbecker** [dgreif/ring#537]
# Bug Report

### Describe the Bug

Got this error when live streaming

### To Reproduce

Showed up randomly when trying to live stream

### Screenshots/Logs

```
[12/30/2020, 6:43:12 AM] [Ring] Preparing Live Stream for Front Door
[12/30/2020, 6:43:13 AM] [Ring] Waiting for stream data from Front Door (1.074s)
[12/30/2020, 6:43:14 AM] [Ring] Received stream data from Front Door (1.418s)
[12/30/2020, 6:43:14 AM] [Ring] Streaming active for Front Door
[12/30/2020, 6:43:19 AM] [Ring] Stopped Live Stream for Front Door
(node:1905) UnhandledPromiseRejectionWarning: Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at RtpSplitter.<anonymous> (/usr/lib/node_modules/homebridge-ring/node_modules/@homebridge/camera-utils/lib/rtp-splitter.js:54:25)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-ring/node_modules/@homebridge/camera-utils/lib/rtp-splitter.js:5:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1905) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1905) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Homebridge Ring Config

```

        {
            "refreshToken": "xxxxxxxxx",
            "hideLightGroups": true,
            "hideDoorbellSwitch": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "platform": "Ring"
        },

```

### Environment

 - OS: [Raspbian]
 - Node.js: [v14.15.3] 
 - NPM: [v6.14.10] 
 - homebridge-ring: [v9.12.8]
 - homebridge: [v1.2.5]

**Comment by dgreif** [comment]
Looks like it may have happened after you stopped the stream.  The socket probably closed and then received another packet.  Did you notice any issues with the stream, or just happen to see this in the logs?

**Comment by donavanbecker** [comment]
@dgreif I just happened to see the log, so just wanted to report it, just incase it was an issue.

**Comment by dgreif** [comment]
Sounds good. I'll close for now and keep an eye on it

**Comment by donavanbecker** [comment]
@dgreif now getting this, on 1 instance.

```
[1/4/2021, 8:02:25 AM] [Ring] audio stun error
[1/4/2021, 8:02:25 AM] [Ring] Error: timeout
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/stun/src/node_modules/net/request.js:184:38)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[1/4/2021, 8:02:25 AM] [Ring] video stun error
[1/4/2021, 8:02:25 AM] [Ring] Error: timeout
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/stun/src/node_modules/net/request.js:184:38)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

this on another,
```
[1/4/2021, 8:15:35 AM] [Ring] Front Door Detected Motion
[Front Door] Snapshot request handler provided empty image buffer!
[Front Door] Snapshot request handler provided empty image buffer!
```
