### ISSUE TITLE
No audio on livestream in half of streams or no stream at all

### ISSUE THREAD

**Issue by jchristianj** [dgreif/ring#586]
# Bug Report

### No audio in app. 50% of live streams or no stream at all
When initiating a live stream by tapping the camera preview in home.app in about 50% of the streams there is no audio from the camera, or there is no stream at all.

### To Reproduce
Start home.app and immediately tap the preview from cam. Either it will show camera not available after 15s, or stream will start after 8 seconds, but without audio.

### Expected behavior
Should start each time tapped, and with audio.

### Screenshots/Logs
Not sure if related, but this happens very often:

[03/03/2021, 07:36:49] [Ring] Ding 6935313035548512380 is expired (480).  Fetching a new ding and trying video stream again
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:584:43)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[03/03/2021, 07:36:50] [Ring] Waiting for stream data from Haustür (1.132s)
[03/03/2021, 07:36:50] [Ring] Received stream data from Haustür (1.466s)
[03/03/2021, 07:36:50] [Ring] Streaming active for Haustür
[03/03/2021, 07:36:54] [Ring] Stopped Live Stream for Haustür
[03/03/2021, 07:37:06] [Ring] Preparing Live Stream for Haustür
[03/03/2021, 07:37:06] [Ring] Ding 6935313082793152636 is expired (480).  Fetching a new ding and trying video stream again
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:584:43)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[03/03/2021, 07:37:07] [Ring] Waiting for stream data from Haustür (1.162s)
[03/03/2021, 07:37:15] [Ring] Stopped Live Stream for Haustür
[03/03/2021, 07:37:26] [Ring] Preparing Live Stream for Haustür
[03/03/2021, 07:37:26] [Ring] Ding 6935313160102563964 is expired (480).  Fetching a new ding and trying video stream again

### Additional context
Issue applies to Ring2 (battery) and Ring Pro (wired) and happens with latest plugin. For testing went down to 9.12, happens there as well.
I went from Hoobs to homebridge last week, setup all new from scratch and even re-installed the ring plugin.

### Homebridge Ring Config
{
    "refreshToken": "eyJhbG...-4PQ",
    "platform": "Ring"
}

### Environment
 - OS: Raspbian GNU/Linux Buster (10)
 - Node.js:  v14.15.5
 - NPM: v7.5.4
 - homebridge-ring: 9.15.3
 - homebridge: 1.0.19
 - hoobs: n.a.

**Comment by jchristianj** [comment]
Need to add some information: 
It happens only with the Ring Pro. The Ring 2 streams perfect including audio.

**Comment by dgreif** [comment]
Thanks for clarifying.  Does the Ring Pro audio _ever_ work, or is it ~50% and the Ring 2 is 100%?

**Comment by jchristianj** [comment]
Yes, Ring 2 is almost 100% in Audio and Video. 
For Ring Pro it is as follows:
Don't have empiric figures, but my feeling says the live stream on the Pro initiates in 80% of all attempts. If it starts streaming, then 50% of the streams have audio. Others not.

If it fails on video, then the log shows:
[03/03/2021, 16:10:35] [Ring] Preparing Live Stream for Haustür
[03/03/2021, 16:10:36] [Ring] Waiting for stream data from Haustür (0.924s)
[03/03/2021, 16:10:44] [Ring] Stopped Live Stream for Haustür

Cannot find a relation between log and missing audio... sometimes it works, sometimes not.

**Comment by jchristianj** [comment]
> Thanks for clarifying. Does the Ring Pro audio _ever_ work, or is it ~50% and the Ring 2 is 100%?

Do you have any idea how to solve?
I mean, is the problem on my side (Homebridge installation, network, whatever) so that I have to investigate further, or is it something going on or Ring servers and/or the plugin and I can't do anything about it?
If you need further information let me know.

**Comment by dgreif** [comment]
Sorry for the lack of feedback, your response earlier is definitely helpful.  My guess is one of your cameras is using Rings newer media servers and the other is on their older media server.  My integration with the older servers is more reliable and works consistently, but the newer servers can have intermittent issues.  This is something that I need to investigate further, but haven't had the time to do.  At this point there isn't anything specific that I need from your end.  Hopefully I can track down these issues and fix them at some point in the near future.  I'll let you know when I find the time to tackle it and get a new version out.

**Comment by stubbz00** [comment]
I believe I'm experiencing the same issues as well.  I don't use the audio very much but notice that sometimes ring cameras show 'not responding' and only started around the time this post was created.  Rebooting the homebridge-ring child bridge usually fixes the issue, but inevitably happens again.  The only time I know it's happening is when I don't get motion alerts.  

Could all of this be also caused by Rings new media servers?

**Comment by petergp** [comment]
Also experiencing "not responding" 50% of the time on a Ring Video Doorbell 3. 

Let me know if I can help somehow.

**Comment by dgreif** [comment]
Thanks for your patience everyone, please give v`9.18.0` a try and see if it is more reliable.

**Comment by jchristianj** [comment]
Thanks! Video and audio success for both cams (Pro and Ring 2) is at 100%. But:
- Max. live view length is 30 seconds, then it stops
- snapshots do not refresh any longer after 10 secs on home WiFi (both cams), it seems to be set to 1 minute refresh?

**Comment by petergp** [comment]
I can also confirm that its very reliable now for starting the video and audio, however after exactly 30 seconds the feed stops. Here is a snippet from the logs.

```
1 bitrate=  28.1kbits/s speed=1.01x    
[5/4/2021, 10:20:00 AM] [Ring] From Ring (Front Door): size=      87kB time=00:00:25.23 bitrate=  28.1kbits/s speed=   1x    
[5/4/2021, 10:20:00 AM] [Ring] From Ring (Front Door): size=      88kB time=00:00:25.77 bitrate=  28.1kbits/s speed=   1x    
[5/4/2021, 10:20:01 AM] [Ring] From Ring (Front Door): size=      90kB time=00:00:26.28 bitrate=  28.1kbits/s speed=   1x    
[5/4/2021, 10:20:01 AM] [Ring] From Ring (Front Door): size=      92kB time=00:00:26.79 bitrate=  28.1kbits/s speed=1.01x    
[5/4/2021, 10:20:02 AM] [Ring] From Ring (Front Door): size=      94kB time=00:00:27.31 bitrate=  28.1kbits/s speed=   1x    
[5/4/2021, 10:20:02 AM] [Ring] From Ring (Front Door): size=      95kB time=00:00:27.82 bitrate=  28.1kbits/s speed=   1x    
[5/4/2021, 10:20:05 AM] [Ring] From Ring (Front Door): size=      96kB time=00:00:28.01 bitrate=  28.1kbits/s speed=0.935x    
[5/4/2021, 10:20:05 AM] [Ring] Stopped Live Stream for Front Door
[5/4/2021, 10:20:13 AM] [Ring] Return Audio (Front Door): stopped gracefully
[5/4/2021, 10:20:13 AM] [Ring] Return Audio (Front Door): pipe:: Connection timed out
Finishing stream 0:0 without any data written to it.

[5/4/2021, 10:20:13 AM] [Ring] Return Audio (Front Door): Output #0, rtp, to 'srtp://127.0.0.1:35232?pkt_size=188':
  Metadata:
    title           : Talk
    encoder         : Lavf58.45.100

[5/4/2021, 10:20:13 AM] [Ring] Return Audio (Front Door):     Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
    Metadata:
      encoder         : Lavc58.91.100 pcm_mulaw

[5/4/2021, 10:20:13 AM] [Ring] Return Audio (Front Door): size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)

[5/4/2021, 10:20:13 AM] [Ring] Return Audio (Front Door): Exiting normally, received signal 15.

[5/4/2021, 10:20:15 AM] [Ring] From Ring (Front Door): stopped gracefully
[5/4/2021, 10:20:15 AM] [Ring] From Ring (Front Door): pipe:: Connection timed out

[5/4/2021, 10:20:15 AM] [Ring] From Ring (Front Door): size=     104kB time=00:00:30.23 bitrate=  28.1kbits/s speed=0.753x    
video:0kB audio:89kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 16.854490%

[5/4/2021, 10:20:15 AM] [Ring] From Ring (Front Door): Exiting normally, received signal 15.
```

**Comment by dgreif** [comment]
@jchristianj @petergp thanks for confirming that the streams are starting reliably now 🎉.  The 30 second timeout is a known issue, and is being tracked in #479
