### ISSUE TITLE
Failure to start concurrent livestreams to different cameras

### ISSUE THREAD

**Issue by tsightler** [dgreif/ring#600]
# Bug Report

### Describe the Bug
I'm trying to understand if I have a bug in my own code, or if this is some limitation that I don't understand.  I have some code which starts a live stream by calling camera.streamVideo() function.  I use ffmpeg options to pipe a low frame rate MJPEG stream to a socket and then connect a listener to process the stream output and emit full JPEG images via MQTT to provide refreshed snapshot images during motion events every couple of seconds.

This works perfectly when one camera detects motion and starts a livestream, however, if a second camera starts motion, things don't go as well.  It's the identical code, but I get a weird failure that doesn't appear to be in my code (although I could be wrong):

```
 TypeError: Cannot read property 'toString' of null
    at /app/ring-mqtt-dev/node_modules/@homebridge/camera-utils/lib/ffmpeg-process.js:14:133
    at Array.map (<anonymous>)
    at new FfmpegProcess (/app/ring-mqtt-dev/node_modules/@homebridge/camera-utils/lib/ffmpeg-process.js:14:120)
    at SipSession.startTranscoder (/app/ring-mqtt-dev/node_modules/ring-client-api/lib/api/sip-session.js:162:17)
    at SipSession.<anonymous> (/app/ring-mqtt-dev/node_modules/ring-client-api/lib/api/sip-session.js:65:26)
    at Generator.next (<anonymous>)
    at fulfilled (/app/ring-mqtt-dev/node_modules/ring-client-api/lib/api/sip-session.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

When I attempt to track this down, the "toString()" that it is complaining about on a null value appears to be from this code in @homebridge/ffmpeg-process.ts

```
export class FfmpegProcess {
  private ff = spawn(
    this.options.ffmpegPath || defaultFfmpegPath,
    this.options.ffmpegArgs.map((x) => x.toString())
  )
```

Clearly, I'm probably above my head coding wise here, but I'm completely struggling to understand why calling this for one camera works while the second attempt on a different camera (if the stream is still active on the first) seems to fail.

### To Reproduce
Honestly, right now I've only reproduced it in the full ring-mqtt build, but I have a small sample that currently only does one camera, but I'll attempt to expand it to two concurrent cameras and see if it works or fails for the sample app.

### Expected behavior
I expected that starting a stream on two different cameras would be no issue.

### Environment

 - OS: Node 14 LTS container image (Alpine 3.12 based) on both x86-64 and RPi4
 - Node.js: 14.16.0
 - ring-client-api: 9.15.5

**Comment by tsightler** [comment]
I'm going to close this as I can't reproduce this behavior with a set of test code that I wrote that does basically the same thing.  With the test code both streams start and emit images as expected.  Not sure what's going on with my actual project, but I guess I'll have to go through it and figure out what could possibly be causing this.
