### ISSUE TITLE
Doorbell pressed not triggering

### ISSUE THREAD

**Issue by richarddas** [dgreif/ring#601]
# Bug Report

### Describe the Bug
Was working fine. For the past week however doorbell press has not been registering. Someone will press the doorbell, the unit will chime (Ring Doorbell Pro) and the Rapid Ring app will send a notification ok, but HomeBridge will not see it in the logs (HomePods won't chime, etc.)

Camera previews etc. work fine.

### To Reproduce
 - Start Homebridge
 - Press doorbell
 - Observe complete lack of reaction from HomeBridge

### Expected behavior
Expect to see the ring button press at least in the logs.

### Additional context
```
01/04/2021, 14:58:32 (node:20261) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
01/04/2021, 14:58:32 at SipCall.request (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
01/04/2021, 14:58:32 at SipCall.sendKeyFrameRequest (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
01/04/2021, 14:58:32 at SipCall.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
01/04/2021, 14:58:32 at Generator.next (<anonymous>)
01/04/2021, 14:58:32 at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
01/04/2021, 14:58:32 (Use `node --trace-warnings ...` to show where the warning was created)
01/04/2021, 14:58:32 (node:20261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
01/04/2021, 14:58:32 (node:20261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Homebridge Ring Config
```
{
    "platform": "Ring",
    "plugin_map": {
        "plugin_name": "homebridge-ring"
    },
    "hideCameraSirenSwitch": true,
    "hideCameraMotionSensor": true,
    "hideInHomeDoorbellSwitch": true,
    "hideAlarmSirenSwitch": true,
    "hideUnsupportedServices": true,
    "avoidSnapshotBatteryDrain": false,
    "sendDoorbellMotionNotificationsToTv": false,
    "sendCameraMotionNotificationsToTv": false,
    "hideDoorbellSwitch": true,
    "showPanicButtons": false,
    "cameraStatusPollingSeconds": 20,
    "cameraDingsPollingSeconds": 2,
    "hideDeviceIds": [],
    "locationIds": [],
    "onlyDeviceTypes": []
}
```

### Environment

 - OS: HOOBS
 - Node.js: 14.15.1
 - NPM: _
 - homebridge-ring: 9.15.5
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: 3.3.5

**Comment by richarddas** [comment]
I just read more, and suspect this is an issue with HOOBS 3.3.5 which was pulled. Current HOOBS is 3.3.3.
