### ISSUE TITLE
After upgrade to 9.16, Ring plugin will not initiate

### ISSUE THREAD

**Issue by bryonbnm** [dgreif/ring#609]
# Bug Report

### Describe the Bug
Ring plugin will not initiatie

### To Reproduce
 - Start Homebridge
 - Errors
 - [10/04/2021, 07:26:09] ====================
[10/04/2021, 07:26:09] ERROR LOADING PLUGIN homebridge-ring:
[10/04/2021, 07:26:09] /usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/index.js:1

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:18:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[10/04/2021, 07:26:09] ====================
[10/04/2021, 07:26:09] No plugin was found for the platform "Ring" in your config.json. Please make sure the corresponding plugin is installed correctly.

### Expected behavior
Expect to launch and run plugin

### Screenshots/Logs
[10/04/2021, 07:25:54] [Homebridge UI] Homebridge restart request received
[10/04/2021, 07:25:55] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[10/04/2021, 07:25:55] [Homebridge UI] Sending SIGTERM to Homebridge
[10/04/2021, 07:25:55] Got SIGTERM, shutting down Homebridge...
[10/04/2021, 07:26:00] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[10/04/2021, 07:26:05] [HB Supervisor] Restarting Homebridge...
[10/04/2021, 07:26:05] [HB Supervisor] Starting Homebridge with extra flags: -I
[10/04/2021, 07:26:05] [HB Supervisor] Started Homebridge v1.3.4 with PID: 3312
Initializing HAP-NodeJS v0.9.4...
[10/04/2021, 07:26:06] Loaded config.json with 0 accessories and 5 platforms.
[10/04/2021, 07:26:07] Loaded 31 cached accessories from cachedAccessories.
[10/04/2021, 07:26:07] ---
[10/04/2021, 07:26:09] Loaded plugin: homebridge-bond@3.2.6
[10/04/2021, 07:26:09] Registering platform 'homebridge-bond.Bond'
[10/04/2021, 07:26:09] ---
[10/04/2021, 07:26:09] Loaded plugin: homebridge-config-ui-x@4.41.0
[10/04/2021, 07:26:09] Registering platform 'homebridge-config-ui-x.config'
[10/04/2021, 07:26:09] ---
[10/04/2021, 07:26:09] Loaded plugin: homebridge-myq@2.6.2
[10/04/2021, 07:26:09] Registering platform 'homebridge-myq.myQ'
[10/04/2021, 07:26:09] ---
[10/04/2021, 07:26:09] Loaded plugin: homebridge-platform-wemo@2.15.2
[10/04/2021, 07:26:09] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[10/04/2021, 07:26:09] ---
[10/04/2021, 07:26:09] ====================
[10/04/2021, 07:26:09] ERROR LOADING PLUGIN homebridge-ring:
[10/04/2021, 07:26:09] /usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/index.js:1

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:18:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[10/04/2021, 07:26:09] ====================
[10/04/2021, 07:26:09] Loading 5 platforms...
[10/04/2021, 07:26:09] [Config] Initializing config platform...
[10/04/2021, 07:26:09] [Config] Running in Service Mode
[10/04/2021, 07:26:09] [Bond] Initializing Bond platform...
[10/04/2021, 07:26:09] [Wemo] Initializing BelkinWeMo platform...
[10/04/2021, 07:26:09] [myQ] Initializing myQ platform...
[10/04/2021, 07:26:09] [myQ] Adjusting myQ API normal refresh duration from NaN to 300. Setting too high of a normal refresh duration is strongly discouraged due to myQ occasionally blocking accounts who overtax the myQ API.
[10/04/2021, 07:26:09] No plugin was found for the platform "Ring" in your config.json. Please make sure the corresponding plugin is installed correctly.
[10/04/2021, 07:26:09] [Wemo] [v2.15.2] initialised. Setting up device discovery.
[10/04/2021, 07:26:11] [Wemo] ✓ Setup complete. Interested in sponsoring this plugin? https://github.com/sponsors/bwp91
Preparing Advertiser for 'Homebridge E338' using bonjour-hap backend!
Setup Payload:
X-HM://0024QOE5YA42M
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 768-34-742 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge E338' using bonjour-hap backend!
[10/04/2021, 07:26:11] Homebridge v1.3.4 (Homebridge) is running on port 51338.
[10/04/2021, 07:26:11] [Bond] 4 cached accessories were loaded
[10/04/2021, 07:26:11] [Bond] Getting devices for this Bond (ZZDF77879)...
[10/04/2021, 07:26:11] [Bond] 4 devices were found on this Bond (ZZDF77879).
[10/04/2021, 07:26:11] [Bond] No new devices to add for this Bond (ZZDF77879).
[10/04/2021, 07:26:11] [Wemo] [Bar Pendants] Polling may be needed to update external brightness changes, see config.
[10/04/2021, 07:26:11] [Wemo] [Bar Pendants] initialised with s/n M19AA029W06493 and mac address E8:9F:80:1C:C1:5E.
[10/04/2021, 07:26:11] [Bond] Configuring Accessory: Living Room Living Room Fan
[10/04/2021, 07:26:11] [Bond] [Living Room Fan] actions: TurnOff,SetSpeed,Stop,TogglePower,TurnOn,IncreaseSpeed,DecreaseSpeed
[10/04/2021, 07:26:11] [Bond] Configuring Accessory: Office Office fan
[10/04/2021, 07:26:11] [Bond] [Office fan] actions: SetSpeed,TurnOff,Stop,TogglePower,TurnOn,IncreaseSpeed,DecreaseSpeed
[10/04/2021, 07:26:11] [Bond] Configuring Accessory: Master Bedroom Master fan
[10/04/2021, 07:26:11] [Bond] [Master fan] actions: TurnOff,SetSpeed,Stop,TogglePower,TurnOn,IncreaseSpeed,DecreaseSpeed
[10/04/2021, 07:26:11] [Bond] Configuring Accessory: Guest Bedroom Guest fan
[10/04/2021, 07:26:11] [Bond] [Guest fan] actions: SetSpeed,TurnOff,Stop,TogglePower,TurnOn,IncreaseSpeed,DecreaseSpeed
[10/04/2021, 07:26:11] [Wemo] [Sink] Polling may be needed to update external brightness changes, see config.
[10/04/2021, 07:26:11] [Wemo] [Sink] initialised with s/n M19AA029W06340 and mac address E8:9F:80:1C:C0:2C.
[10/04/2021, 07:26:12] [Wemo] [Salt Lamp] initialised with s/n M1BAB133D87682 and mac address E8:9F:80:3E:A6:58.
[10/04/2021, 07:26:12] [Wemo] [Bar Pendants] updating brightness to [25%].
[10/04/2021, 07:26:13] [Wemo] [Fireplace] Polling may be needed to update external brightness changes, see config.
[10/04/2021, 07:26:13] [Wemo] [Fireplace] initialised with s/n M19AA029W06018 and mac address E8:9F:80:1C:BD:A8.
[10/04/2021, 07:26:13] [Wemo] [Overhead] Polling may be needed to update external brightness changes, see config.
[10/04/2021, 07:26:13] [Wemo] [Overhead] initialised with s/n M19AA029W06366 and mac address E8:9F:80:1C:C0:60.
[10/04/2021, 07:26:13] [Wemo] [Lamp] initialised with s/n M1BAB133D87607 and mac address E8:9F:80:3E:A5:C2.
[10/04/2021, 07:26:14] [Wemo] [Spider Lamp] initialised with s/n M1BAB133D87709 and mac address E8:9F:80:3E:A6:8E.
[10/04/2021, 07:26:16] [myQ] myQ API: Successfully connected to the myQ API.
[10/04/2021, 07:26:17] [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: CG0860AECB21, gateway: GW0F002C506E).
[10/04/2021, 07:26:17] [myQ] myQ API: Discovered device family gateway: Garage Door [Liftmaster WiFi GDO AC 3/4 HP] (serial number: GW0F002C506E).
[10/04/2021

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
{
    "refreshToken": "xxx",
    "platform": "Ring"
}
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment
<!-- ✍️edit: -->
 - OS: [e.g.Raspbian] Raspbian
 - Node.js: [e.g. 12.14.1] 14.16.0
 - NPM: [e.g 6.13.4] 7.6.2
 - homebridge-ring: 9.16.0
 - homebridge: 1.3.4

**Comment by dgreif** [comment]
This is likely an issue with npm.  It looks like you are on npm 7, which still has some bugs when it comes to ensuring all child dependencies are up to date.  You can start by deleting the rxjs module by running `rm -rf /usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs`, then installing the ring plugin again `npm i -g homebridge-ring`.  Hopefully that straightens it out, but if not, you may need to downgrade to npm 6.  I tried using npm 7 myself for a while, but had to revert back because of bugs like this one.

**Comment by bryonbnm** [comment]
Many thanks. 

Sent from my iPhone

On Apr 10, 2021, at 7:57 AM, Dusty Greif ***@***.***> wrote:

﻿
This is likely an issue with npm. It looks like you are on npm 7, which still has some bugs when it comes to ensuring all child dependencies are up to date. You can start by deleting the rxjs module by running rm -rf /usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs, then installing the ring plugin again npm i -g homebridge-ring. Hopefully that straightens it out, but if not, you may need to downgrade to npm 6. I tried using npm 7 myself for a while, but had to revert back because of bugs like this one.
