### ISSUE TITLE
Ring Video Doorbell 2 

### ISSUE THREAD

**Issue by d2ustin** [dgreif/ring#622]
Live Streaming Issue

Describe the live streaming issue
When attempting to live stream the video attempts to load, but eventually says camera not responding. I've done a few tests, the snapshot updates for any motion it's just an issue with the live stream.  I've tried different wifi networks, and followed the wiki.  I realize you might not be able to assist, but the error message I'm getting below, I'm hoping you could let me know what it means.  I enabled additional logging.  I've noticed that I'm getting the same error each time I attempt to live stream in the logs. 

### Screenshots/Logs
[21/04/2021, 12:14:09] [Ring] Used cached snapshot for Back Door
[21/04/2021, 12:14:09] [Ring] Loading new snapshot into cache for Back Door
[21/04/2021, 12:14:10] [Ring] Preparing Live Stream for Back Door
[21/04/2021, 12:14:10] [Ring] Ding 6953644776290174850 is expired (480).  Fetching a new ding and trying video stream again
[21/04/2021, 12:14:10] [Ring] Stream Prepared for Back Door (0.749s)
[21/04/2021, 12:14:10] [Ring] video stun complete
[21/04/2021, 12:14:10] [Ring] audio stun complete
[21/04/2021, 12:14:10] [Ring] From Ring (Back Door): stopped gracefully
[21/04/2021, 12:14:10] [Ring] Return Audio (Back Door): stopped gracefully
[21/04/2021, 12:14:10] [Ring] Streaming active for Back Door
[21/04/2021, 12:14:12] [Ring] requesting key frame
(node:3076) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
    at SipCall.request (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
    at SipCall.sendKeyFrameRequest (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
    at SipCall.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
(node:3076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
[21/04/2021, 12:14:16] [Ring] Stopped Live Stream for Back Door(8.887s)
[21/04/2021, 12:14:21] [Ring] Used cached snapshot for Back Door
[21/04/2021, 12:14:21] [Ring] Preparing Live Stream for Back Door
[21/04/2021, 12:14:22] [Ring] Stream Prepared for Back Door (0.566s)
[21/04/2021, 12:14:22] [Ring] video stun complete
[21/04/2021, 12:14:22] [Ring] audio stun complete
[21/04/2021, 12:14:22] [Ring] From Ring (Back Door): stopped gracefully
[21/04/2021, 12:14:22] [Ring] Return Audio (Back Door): stopped gracefully
[21/04/2021, 12:14:22] [Ring] Streaming active for Back Door
[21/04/2021, 12:14:24] [Ring] requesting key frame
(node:3076) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
    at SipCall.request (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
    at SipCall.sendKeyFrameRequest (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
    at SipCall.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
(node:3076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
[21/04/2021, 12:14:43] [Ring] Back Door Detected Motion
[21/04/2021, 12:14:43] [Ring] Used cached snapshot for Back Door
[21/04/2021, 12:14:43] [Ring] Loading new snapshot into cache for Back Door
[21/04/2021, 12:14:52] [Ring] Stopped Live Stream for Back Door

[21/04/2021, 12:35:38] [Ring] Preparing Live Stream for Back Door
[21/04/2021, 12:35:39] [Ring] Stream Prepared for Back Door (0.506s)
[21/04/2021, 12:35:39] [Ring] video stun complete
[21/04/2021, 12:35:39] [Ring] audio stun complete
[21/04/2021, 12:35:39] [Ring] From Ring (Back Door): stopped gracefully
[21/04/2021, 12:35:39] [Ring] Return Audio (Back Door): stopped gracefully
[21/04/2021, 12:35:39] [Ring] Streaming active for Back Door
[21/04/2021, 12:35:41] [Ring] requesting key frame
(node:3076) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
    at SipCall.request (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
    at SipCall.sendKeyFrameRequest (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
    at SipCall.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
(node:3076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 22

Environment

 - Ring Camera: Ring Video Doorbell 2
 - OS: Raspbian
 - Node.js: v14.16.1
 - NPM: 6.14.12
 - homebridge-ring: v9.17.0
 - homebridge: v1.3.4
 - hoobs (if applicable): [e.g. 0.4.50 or N/A]

Network Environment
 
Network setup: ATT Gateway for Fiber (IP Passthrough to Netgear), Netgear RXA70 (Nighthawk) Router setup which hosts the wifi.  HomeBridge server is Rasberry Pi 3 B + with hombridge flash installed.  HomeKit Home up is HomePod

**Comment by dgreif** [comment]
`SIP request made after call was destroyed` is not a very typical error.  It looks like the ffmpeg processes are exiting early, which may be why you are having issues.  Can you turn on the Debug flag in homebridge?  I think it's in the homebridge options menu if you are using homebridge-config-ui-x

**Comment by d2ustin** [comment]
Hey there.  The log I pasted had the -D flag on (I think I did a few tests with the flag on and off).  I turned on and ran a few things here's what I did..  Rebooted HB and ring.  Waited, opened cam in HB, let it load, it failed saying camera not responding, when I close the camera the snap shot is updated, but still can't live view.. Did the same thing again, seems like the same error is persisting. 

[21/04/2021, 19:06:18] [Ring] No snapshot cached for Back Door
[21/04/2021, 19:06:18] [Ring] Loading new snapshot into cache for Back Door
[21/04/2021, 19:06:22] [Ring] Snapshot cached for Back Door (3.502s)
[21/04/2021, 19:06:29] [Ring] Used cached snapshot for Back Door
[21/04/2021, 19:06:30] [Ring] Preparing Live Stream for Back Door
[21/04/2021, 19:06:30] [Ring] Stream Prepared for Back Door (0.683s)
[21/04/2021, 19:06:30] [Ring] video stun complete
[21/04/2021, 19:06:30] [Ring] audio stun complete
[21/04/2021, 19:06:30] [Ring] From Ring (Back Door): stopped gracefully
[21/04/2021, 19:06:30] [Ring] Return Audio (Back Door): stopped gracefully
[21/04/2021, 19:06:31] [Ring] Streaming active for Back Door
[21/04/2021, 19:06:33] [Ring] requesting key frame
(node:5438) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
    at SipCall.request (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
    at SipCall.sendKeyFrameRequest (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
    at SipCall.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:5438) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[21/04/2021, 19:07:00] [Ring] Stopped Live Stream for Back Door
[21/04/2021, 19:07:08] [Ring] Used cached snapshot for Back Door
[21/04/2021, 19:07:08] [Ring] Loading new snapshot into cache for Back Door
[21/04/2021, 19:07:11] [Ring] Preparing Live Stream for Back Door
[21/04/2021, 19:07:11] [Ring] Ding 6953751295774082946 is expired (480).  Fetching a new ding and trying video stream again
[21/04/2021, 19:07:11] [Ring] Stream Prepared for Back Door (0.75s)
[21/04/2021, 19:07:11] [Ring] camera connected to ring server
[21/04/2021, 19:07:11] [Ring] audio stun complete
[21/04/2021, 19:07:11] [Ring] video stun complete
[21/04/2021, 19:07:11] [Ring] From Ring (Back Door): stopped gracefully
[21/04/2021, 19:07:11] [Ring] Return Audio (Back Door): stopped gracefully
[21/04/2021, 19:07:11] [Ring] Streaming active for Back Door
[21/04/2021, 19:07:11] [Ring] requesting key frame
(node:5438) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
    at SipCall.request (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
    at SipCall.sendKeyFrameRequest (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
    at SipCall.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:5438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[21/04/2021, 19:11:21] [Ring] Used cached snapshot for Back Door
[21/04/2021, 19:11:31] [Ring] Preparing Live Stream for Back Door
[21/04/2021, 19:11:31] [Ring] Stream Prepared for Back Door (0.572s)
[21/04/2021, 19:11:32] [Ring] audio stun complete
[21/04/2021, 19:11:32] [Ring] video stun complete
[21/04/2021, 19:11:32] [Ring] From Ring (Back Door): stopped gracefully
[21/04/2021, 19:11:32] [Ring] Return Audio (Back Door): stopped gracefully
[21/04/2021, 19:11:32] [Ring] Streaming active for Back Door
[21/04/2021, 19:11:34] [Ring] requesting key frame
(node:5438) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
    at SipCall.request (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
    at SipCall.sendKeyFrameRequest (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
    at SipCall.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
(node:5438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)

[21/04/2021, 19:16:47] [Ring] Preparing Live Stream for Back Door
[21/04/2021, 19:16:48] [Ring] Stream Prepared for Back Door (0.615s)
[21/04/2021, 19:16:48] [Ring] audio stun complete
[21/04/2021, 19:16:48] [Ring] video stun complete
[21/04/2021, 19:16:48] [Ring] From Ring (Back Door): stopped gracefully
[21/04/2021, 19:16:48] [Ring] Return Audio (Back Door): stopped gracefully
[21/04/2021, 19:16:48] [Ring] Streaming active for Back Door
[21/04/2021, 19:16:50] [Ring] requesting key frame
(node:5438) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
    at SipCall.request (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
    at SipCall.sendKeyFrameRequest (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
    at SipCall.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
(node:5438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)

If there's any other troubleshooting I can do let me know I'm happy to do it.  

Thanks so much

**Comment by d2ustin** [comment]
Hey Dustin - I updated to the newest version and it still seems I’m getting the same error. Any suggestions? Thanks!

**Comment by d2ustin** [comment]
So I got it to stream I’m still getting some error messages, I did some full server reboots uninstalled ring plugin and reinstalled which I also think forced a reinstall of ffmpeg .  If the other errors come back I’ll post.

I did notice though, that when I live steam from HomeKit it triggers a push notification from the ring app saying there’s motion, is that how it triggers the live view, a fake motion event?

**Comment by d2ustin** [comment]
Here’s the new error info:
`[03/05/2021, 22:57:56] [Ring] Preparing Live Stream for Back Door
[03/05/2021, 22:57:57] [Ring] Waiting for stream data from Back Door (0.69s)
[03/05/2021, 22:58:05] [Ring] Stopped Live Stream for Back Door
[03/05/2021, 22:58:05] [Ring] Failed to prepare stream for Back Door (9.353s)
[03/05/2021, 22:58:05] [Ring] Error: 
    at _super (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/createErrorClass.ts:13:22)
    at new EmptyErrorImpl (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/EmptyError.ts:26:7)
    at Object.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/lastValueFrom.ts:70:18)
    at Object.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:193:14)
    at SafeSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
    at SafeSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
    at OperatorSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
    at OperatorSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
    at OperatorSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
    at OperatorSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
    at OperatorSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
    at OperatorSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
    at OperatorSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
    at OperatorSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
    at Subject.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subject.ts:84:28)
    at Object.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/share.ts:145:16)
    at Object.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:193:14)
    at SafeSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
    at SafeSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
    at /usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/takeUntil.ts:47:87
    at OperatorSubscriber._this._next (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:43:13)
    at OperatorSubscriber.Subscriber.next (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:74:12) {
  message: 'no elements in sequence'
}
`

**Comment by r3dlobst3r** [comment]
Going to hop on this issue. I have the same doorbell and I am facing the same issue 9 out of 10 times I try to open the video feed.
`[7/15/2021, 2:11:24 PM] [Ring] Error: 
    at _super (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/createErrorClass.ts:13:22)
    at new EmptyErrorImpl (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/EmptyError.ts:26:3)
    at Object.complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/lastValueFrom.ts:72:18)
    at Object.complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:193:14)
    at SafeSubscriber.Subscriber._complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
    at SafeSubscriber.Subscriber.complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
    at OperatorSubscriber.Subscriber._complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
    at OperatorSubscriber.Subscriber.complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
    at OperatorSubscriber.Subscriber._complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
    at OperatorSubscriber.Subscriber.complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:105:12) {
  message: 'no elements in sequence'
}`

**Comment by dgreif** [comment]
@d2ustin to answer your question from a while ago, you are correct that the setting triggers a doorbell event for motion events to trick the TV into streaming.  I've heard rumors that iOS 15 will support this natively, so hopefully that can be removed down the road.  

Regarding the `_super` error, I'll keep an eye out for that bug.

**Comment by dgreif** [comment]
Would either of you mind trying `9.18.2` to see if you are still experiencing the `Error: at _super` issue?

**Comment by r3dlobst3r** [comment]
I have updated the plugin and will report back if any issues arise. I also realized that in power settings, I had it only periodically check motion to save power. It seems that having motion always enabled helped the issue, but I have put it back down to low power to test the new update.

**Comment by r3dlobst3r** [comment]
24 hours later and not a single issue connecting to the doorbell on any power setting. Thanks for the hard work!

**Comment by dgreif** [comment]
@d2ustin are you still having issues or is this resolved with the latest version?

**Comment by d2ustin** [comment]
Yes seems to be resolved.
