### ISSUE TITLE
Setting alarm from Homekit fails with error 400 in homebridge logs

### ISSUE THREAD

**Issue by jnmmoore** [dgreif/ring#637]
### Describe the Bug
Trying to arm the ring alarm in HK does nothing and an error is seen in the HB logs

### To Reproduce
 - Open Homekit
 - Set alarm to Home or Away
 - See error

### Expected behavior
Ring alarm is armed

### Screenshots/Logs
[5/5/2021, 11:02:18] [Ring] Setting <ADDRESS REMOVED> Mode to home
[5/5/2021, 11:02:18] [Ring] Request to https://app.ring.com/api/v1/mode/location/u1231m-2dpk4-0 failed with status 400. Response body: {"error":999005,"msg":"Not allowed to use this api to change mode"}
(node:19602) UnhandledPromiseRejectionWarning: HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:19602) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 35)

### Additional context
Works fine in Ring app

### Homebridge Ring Config
        {
            "refreshToken": "XXXXXXXX",
            "hideCameraMotionSensor": true,
            "hideCameraSirenSwitch": true,
            "hideAlarmSirenSwitch": true,
            "platform": "Ring"
        },

### Environment

 - OS: Raspbian GNU/Linux Buster (10)
 - Node.js: v12.16.3
 - NPM: 6.14.4
 - homebridge-ring: v9.18.0
 - homebridge: v1.3.4
 - hoobs: N/A

**Comment by jnmmoore** [comment]
Resolved with a restart of Homebridge since alarm had been installed since last start
