### ISSUE TITLE
Replacing Ring - no streaming video to HomeKit App

### ISSUE THREAD

**Issue by panthertom** [dgreif/ring#642]
Hi,
i had to replace the ring doorbell 2 by a doorbell (2020).
Now the new one is active and running, but no video is streaming.
1. I reinstalled and connected the plugin with my account, Name is "Eingang"
2. I restarted the container. 
2. At the status page there is no issue shown:
[5/7/2021 3:39:03 PM] [Ring] Preparing Live Stream for Eingang[5/7/2021 3:39:04 PM] [Ring] Waiting for stream data from Eingang (0.613s)[5/7/2021 3:39:05 PM] [Ring] Received stream data from Eingang (2.118s)[5/7/2021 3:39:05 PM] [Ring] Streaming active for Eingang[5/7/2021 3:39:34 PM] [Ring] Stopped Live Stream for Eingang
So for 30 seconds there should be some video.

3. But at the HomeKit App the camera shows
"No answer. this camera is not responding" 
no video is shown.

With the old camera everything worked perfectly.
Any idea?
Please let me know if you need some information.

Thanks for your help and stay healthy.

Thanks

**Comment by dgreif** [comment]
@panthertom Unfortunately issues like this are tough to debug.  If this is your only accessory in the Ring plugin, then your best bet is probably to remove the Ring plugin, restart homebridge, then add the plugin back.

**Comment by panthertom** [comment]
After a reboot I got this one:

[5/11/2021, 4:26:01 PM] [Ring] Preparing Live Stream for Eingang
[5/11/2021, 4:26:02 PM] [Ring] Waiting for stream data from Eingang (0.639s)
[5/11/2021, 4:26:10 PM] [Ring] Stopped Live Stream for Eingang
[5/11/2021, 4:26:10 PM] [Ring] Failed to prepare stream for Eingang (9.107s)
[5/11/2021, 4:26:10 PM] [Ring] Error: 
    at _super (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/createErrorClass.ts:13:22)
    at new EmptyErrorImpl (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/EmptyError.ts:26:7)
    at Object.complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/lastValueFrom.ts:70:18)
    at Object.complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:193:14)
    at SafeSubscriber.Subscriber._complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
    at SafeSubscriber.Subscriber.complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
    at OperatorSubscriber.Subscriber._complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
    at OperatorSubscriber.Subscriber.complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:105:12)
    at OperatorSubscriber.Subscriber._complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:131:24)
    at OperatorSubscriber.Subscriber.complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:105:12) {
  message: 'no elements in sequence'


Any idea?

**Comment by crossic84** [comment]
Hi, I am facing the same problem...no video stream goes to the HomeKit ❌ 

Getting this error:

[5/16/2021, 2:04:23 PM] [Ring] Preparing Live Stream for Front Door
[5/16/2021, 2:04:23 PM] [Ring] Ding 6962857687359336378 is expired (480).  Fetching a new ding and trying video stream again
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/homebridge/node_modules/homebridge-ring/node_modules/sip/sip.js:584:43)
    at TLSSocket.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[5/16/2021, 2:04:24 PM] [Ring] Waiting for stream data from Front Door (1.003s)
[5/16/2021, 2:04:25 PM] [Ring] Received stream data from Front Door (2.014s)
[5/16/2021, 2:04:25 PM] [Ring] Streaming active for Front Door
[5/16/2021, 2:04:26 PM] [Ring] Stopped Live Stream for Front Door
(node:4441) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
    at SipCall.request (/homebridge/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
    at SipCall.sendKeyFrameRequest (/homebridge/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
    at SipCall.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
(node:4441) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by panthertom** [comment]
@crossic84 : thanks for your information.
What kind of ring camera do you use?
I use an actual Doorbell - 2020 Release.
I hope @dgreif has an idea at that point...

**Comment by crossic84** [comment]
> @crossic84 : thanks for your information.
> What kind of ring camera do you use?
> I use an actual Doorbell - 2020 Release.
> I hope @dgreif has an idea at that point...

I have Doorbell v2. Running my HB in container on QNAP nas.

**Comment by panthertom** [comment]
Same here.
HB running on my Synology in a docker.
Hope @dgreif is able to help us.

**Comment by panthertom** [comment]
@dgreif : You are my hero of the hour!
The update v9.18.1 fixed the issue.
Thanks!
