### ISSUE TITLE
Camera says 'No Response' in HomeKit after around 30 seconds

### ISSUE THREAD

**Issue by Ironboltx** [dgreif/ring#645]
# Live Streaming Issue

### Describe the live streaming issue
 After I start streaming a camera for around 30 seconds without touching anything in HomeKit, the camera just says no response and an error returns in the logs. 

### Screenshots/Logs
 

Return Audio (Front Door): Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'pipe:':
  Metadata:
    title           : Talk
  Duration: N/A, bitrate: N/A
    Stream #0:0: Audio: aac, 16000 Hz, mono, s16
Stream mapping:
  Stream #0:0 -> #0:0 (aac (libfdk_aac) -> pcm_mulaw (native))
Finishing stream 0:0 without any data written to it.
Output #0, rtp, to 'srtp://127.0.0.1:40739?pkt_size=188':
  Metadata:
    title           : Talk
    encoder         : Lavf58.45.100
    Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
    Metadata:
      encoder         : Lavc58.91.100 pcm_mulaw
size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
Exiting normally, received signal 15.

### Recommended solution
 I didn't know what was happening so I just made the plugin as a child bride but it did not fix anything. I also deleted ffmpeg-for-homebridge but it still didn't fix anything. 

### Environment

 - Ring Camera: 4 Ring Floodlight camera and 1 Ring Doorbell camera (All have the streaming experience this issue) 
 - OS: Raspbian GNU/Linux Buster (10)
 - Node.js: v12.20.0
 - NPM: 6.14.8
 - homebridge-ring: v9.18.0
 - homebridge: v1.3.4 

### Network Environment
 
My homebridge server is in a raspberry pi 4 (8gbs of ram) which is connected via ethernet to my router (eero pro 6). The plugin is in child bride mode. I have 4 HomeKit hubs. 1 apple tv 4K which is connected via ethernet and 2 apple tv HDs, one of which is on ethernet and another that is on Wifi. I also have a HomePod (non-mini). My router is connected to my XB7 xfinity modem which is in bridge mode. I have xfinity's gigabit internet service. The eero pro 6 is expecting homekit certification.

**Comment by ITDevTom** [comment]
Hello! 
I am also having this issue. But looking at the logs it seems to treat it like the device has terminated the stream. 

[5/11/2021, 6:48:24 PM] [Ring] Preparing Live Stream for Front Door
[5/11/2021, 6:48:24 PM] [Ring] Waiting for stream data from Front Door (0.562s)
[5/11/2021, 6:48:27 PM] [Ring] Received stream data from Front Door (2.793s)
[5/11/2021, 6:48:27 PM] [Ring] Streaming active for Front Door
[5/11/2021, 6:48:57 PM] [Ring] Stopped Live Stream for Front Door

**Comment by mdsebert** [comment]
Experiencing this problem as well on 9.18.0 with a Ring "Doorbell 2 (doorbell_v4)" per Homekit.

[5/11/2021, 8:01:06 PM] [Ring] Preparing Live Stream for Front Door
[5/11/2021, 8:01:07 PM] [Ring] Waiting for stream data from Front Door (0.757s)
[5/11/2021, 8:01:07 PM] [Ring] Received stream data from Front Door (1.533s)
[5/11/2021, 8:01:08 PM] [Ring] Streaming active for Front Door
[5/11/2021, 8:01:38 PM] [Ring] Stopped Live Stream for Front Door

**Comment by adavison007** [comment]
@dgreif Hope all is well? I am also have the exact same issue other than all 9 of my cameras fail after about 20 seconds. The below is me opening it and then leaving it open.

[15/05/2021, 11:26:17] [Ring] Preparing Live Stream for Garden
[15/05/2021, 11:26:18] [Ring] Connecting to Garden using STUN
[15/05/2021, 11:26:18] [Ring] Waiting for stream data from Garden (0.521s)
[15/05/2021, 11:26:18] [Ring] From Ring (Garden): [udp @ 0x34c8970] attempted to set receive buffer to size 393216 but it only ended up set as 360448

[15/05/2021, 11:26:18] [Ring] From Ring (Garden): [udp @ 0x34c8ac0] attempted to set receive buffer to size 393216 but it only ended up set as 360448

[15/05/2021, 11:26:18] [Ring] Return Audio (Garden): [udp @ 0x3e289e0] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[udp @ 0x3e28b30] attempted to set receive buffer to size 393216 but it only ended up set as 360448

[15/05/2021, 11:26:18] [Ring] Video stream latched for Garden
[15/05/2021, 11:26:18] [Ring] Received stream data from Garden (0.54s)
[15/05/2021, 11:26:18] [Ring] Audio stream latched for Garden
[15/05/2021, 11:26:18] [Ring] From Ring (Garden): Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'pipe:':
  Metadata:
    title           : Talk
  Duration: N/A, start: 0.000000, bitrate: 64 kb/s
    Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_mulaw (native) -> aac (libfdk_aac))
Output #0, rtp, to 'srtp://10.173.45.20:54564?localrtcpport=15642&pkt_size=188':
  Metadata:
    title           : Talk
    encoder         : Lavf58.45.100
    Stream #0:0: Audio: aac (libfdk_aac) (ELD), 16000 Hz, mono, s16, 24 kb/s
    Metadata:
      encoder         : Lavc58.91.100 libfdk_aac

[15/05/2021, 11:26:18] [Ring] Streaming active for Garden
[15/05/2021, 11:26:18] [Ring] From Ring (Garden): size=       2kB time=00:00:00.55 bitrate=  31.4kbits/s speed= 1.1x    
[15/05/2021, 11:26:19] [Ring] From Ring (Garden): size=       4kB time=00:00:01.07 bitrate=  29.8kbits/s speed=1.04x    
[15/05/2021, 11:26:19] [Ring] From Ring (Garden): size=       6kB time=00:00:01.61 bitrate=  29.2kbits/s speed=1.04x    
[15/05/2021, 11:26:20] [Ring] requesting key frame
[15/05/2021, 11:26:20] [Ring] From Ring (Garden): size=       8kB time=00:00:02.12 bitrate=  28.9kbits/s speed=1.02x    
[15/05/2021, 11:26:20] [Ring] From Ring (Garden): size=       9kB time=00:00:02.63 bitrate=  28.7kbits/s speed=1.02x    
[15/05/2021, 11:26:21] [Ring] From Ring (Garden): size=      11kB time=00:00:03.15 bitrate=  28.6kbits/s speed=1.02x    
[15/05/2021, 11:26:21] [Ring] From Ring (Garden): size=      13kB time=00:00:03.63 bitrate=  28.5kbits/s speed=1.01x    
[15/05/2021, 11:26:22] [Ring] From Ring (Garden): size=      14kB time=00:00:04.14 bitrate=  28.5kbits/s speed=1.01x    
[15/05/2021, 11:26:22] [Ring] From Ring (Garden): size=      16kB time=00:00:04.65 bitrate=  28.4kbits/s speed=1.01x    
[15/05/2021, 11:26:23] [Ring] From Ring (Garden): size=      18kB time=00:00:05.19 bitrate=  28.4kbits/s speed=1.01x    
[15/05/2021, 11:26:23] [Ring] From Ring (Garden): size=      20kB time=00:00:05.67 bitrate=  28.4kbits/s speed=1.01x    
[15/05/2021, 11:26:24] [Ring] From Ring (Garden): size=      21kB time=00:00:06.19 bitrate=  28.3kbits/s speed=1.01x    
[15/05/2021, 11:26:24] [Ring] From Ring (Garden): size=      23kB time=00:00:06.70 bitrate=  28.3kbits/s speed=1.01x    
[15/05/2021, 11:26:25] [Ring] From Ring (Garden): size=      25kB time=00:00:07.21 bitrate=  28.3kbits/s speed=1.01x    
[15/05/2021, 11:26:25] [Ring] From Ring (Garden): size=      27kB time=00:00:07.72 bitrate=  28.3kbits/s speed=1.01x    
[15/05/2021, 11:26:26] [Ring] From Ring (Garden): size=      28kB time=00:00:08.23 bitrate=  28.3kbits/s speed=1.01x    
[15/05/2021, 11:26:27] [Ring] From Ring (Garden): size=      30kB time=00:00:08.68 bitrate=  28.3kbits/s speed=0.979x    
[15/05/2021, 11:26:27] [Ring] From Ring (Garden): size=      33kB time=00:00:09.45 bitrate=  28.2kbits/s speed=1.01x    
[15/05/2021, 11:26:27] [Sonos] Study Speaker: get Remaining Duration: return 0s
[15/05/2021, 11:26:28] [Ring] From Ring (Garden): size=      34kB time=00:00:09.93 bitrate=  28.2kbits/s speed=   1x    
[15/05/2021, 11:26:28] [Ring] From Ring (Garden): size=      36kB time=00:00:10.44 bitrate=  28.2kbits/s speed=1.01x    
[15/05/2021, 11:26:29] [Ring] From Ring (Garden): size=      38kB time=00:00:10.95 bitrate=  28.2kbits/s speed=1.01x    
[15/05/2021, 11:26:29] [Ring] From Ring (Garden): size=      39kB time=00:00:11.47 bitrate=  28.2kbits/s speed=1.01x    
[15/05/2021, 11:26:30] [Ring] From Ring (Garden): size=      41kB time=00:00:11.95 bitrate=  28.2kbits/s speed=   1x    
[15/05/2021, 11:26:31] [Ring] From Ring (Garden): size=      43kB time=00:00:12.39 bitrate=  28.2kbits/s speed=0.962x    
[15/05/2021, 11:26:31] [Sonos] warning: heartbeat 171186, drift 345
[15/05/2021, 11:26:32] [Ring] From Ring (Garden): size=      46kB time=00:00:13.29 bitrate=  28.2kbits/s speed=0.976x    
[15/05/2021, 11:26:32] [Ring] From Ring (Garden): size=      49kB time=00:00:14.19 bitrate=  28.2kbits/s speed=   1x    
[15/05/2021, 11:26:32] [Sonos] warning: heartbeat 171187, drift 274
[15/05/2021, 11:26:32] [Ring] From Ring (Garden): size=      51kB time=00:00:14.70 bitrate=  28.2kbits/s speed=   1x    
[15/05/2021, 11:26:33] [Ring] From Ring (Garden): size=      52kB time=00:00:15.21 bitrate=  28.2kbits/s speed=   1x    
[15/05/2021, 11:26:33] [Ring] From Ring (Garden): size=      54kB time=00:00:15.75 bitrate=  28.2kbits/s speed=   1x    
[15/05/2021, 11:26:34] [Ring] From Ring (Garden): size=      56kB time=00:00:16.23 bitrate=  28.2kbits/s speed=   1x    
[15/05/2021, 11:26:34] [Ring] From Ring (Garden): size=      58kB time=00:00:16.75 bitrate=  28.2kbits/s speed=   1x    
[15/05/2021, 11:26:35] [Ring] From Ring (Garden): size=      59kB time=00:00:17.26 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:35] [Ring] From Ring (Garden): size=      61kB time=00:00:17.80 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:36] [Ring] From Ring (Garden): size=      63kB time=00:00:18.31 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:36] [Ring] From Ring (Garden): size=      65kB time=00:00:18.83 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:37] [Ring] From Ring (Garden): size=      66kB time=00:00:19.34 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:37] [Ring] From Ring (Garden): size=      68kB time=00:00:19.85 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:38] [Ring] From Ring (Garden): size=      70kB time=00:00:20.23 bitrate=  28.1kbits/s speed=0.993x    
[15/05/2021, 11:26:39] [Ring] From Ring (Garden): size=      72kB time=00:00:20.94 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:39] [Ring] From Ring (Garden): size=      74kB time=00:00:21.45 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:40] [Ring] From Ring (Garden): size=      76kB time=00:00:21.99 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:41] [Ring] From Ring (Garden): size=      77kB time=00:00:22.31 bitrate=  28.1kbits/s speed=0.975x    
[15/05/2021, 11:26:41] [Ring] From Ring (Garden): size=      80kB time=00:00:23.21 bitrate=  28.1kbits/s speed=0.987x    
[15/05/2021, 11:26:42] [Ring] From Ring (Garden): size=      83kB time=00:00:24.07 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:42] [Ring] From Ring (Garden): size=      84kB time=00:00:24.59 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:43] [Ring] From Ring (Garden): size=      86kB time=00:00:25.07 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:43] [Ring] From Ring (Garden): size=      88kB time=00:00:25.58 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:44] [Ring] From Ring (Garden): size=      90kB time=00:00:26.09 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:44] [Ring] From Ring (Garden): size=      91kB time=00:00:26.63 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:45] [Ring] From Ring (Garden): size=      93kB time=00:00:27.11 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:45] [Ring] From Ring (Garden): size=      95kB time=00:00:27.63 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:46] [Ring] From Ring (Garden): size=      97kB time=00:00:28.14 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:46] [Ring] From Ring (Garden): size=      98kB time=00:00:28.65 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:47] [Ring] From Ring (Garden): size=     100kB time=00:00:29.16 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:47] [Ring] From Ring (Garden): size=     102kB time=00:00:29.67 bitrate=  28.1kbits/s speed=   1x    
[15/05/2021, 11:26:48] [Ring] Stopped Live Stream for Garden
[15/05/2021, 11:26:48] [Ring] Return Audio (Garden): stopped gracefully
[15/05/2021, 11:26:48] [Ring] Return Audio (Garden): Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'pipe:':
  Metadata:
    title           : Talk
  Duration: N/A, bitrate: N/A
    Stream #0:0: Audio: aac, 16000 Hz, mono, s16
Stream mapping:
  Stream #0:0 -> #0:0 (aac (libfdk_aac) -> pcm_mulaw (native))
Finishing stream 0:0 without any data written to it.
Output #0, rtp, to 'srtp://127.0.0.1:36623?pkt_size=188':
  Metadata:
    title           : Talk
    encoder         : Lavf58.45.100
    Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
    Metadata:
      encoder         : Lavc58.91.100 pcm_mulaw
size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
Exiting normally, received signal 15.

[15/05/2021, 11:26:51] [Ring] Preparing Live Stream for Garden
[15/05/2021, 11:26:52] [Ring] Connecting to Garden using STUN
[15/05/2021, 11:26:52] [Ring] Waiting for stream data from Garden (0.737s)
[15/05/2021, 11:26:52] [Ring] From Ring (Garden): [udp @ 0x27b9970] attempted to set receive buffer to size 393216 but it only ended up set as 360448

[15/05/2021, 11:26:52] [Ring] From Ring (Garden): [udp @ 0x27b9ac0] attempted to set receive buffer to size 393216 but it only ended up set as 360448

[15/05/2021, 11:26:52] [Ring] Return Audio (Garden): [udp @ 0x38f99e0] attempted to set receive buffer to size 393216 but it only ended up set as 360448

[15/05/2021, 11:26:52] [Ring] Return Audio (Garden): [udp @ 0x38f9b30] attempted to set receive buffer to size 393216 but it only ended up set as 360448

[15/05/2021, 11:26:52] [Ring] Audio stream latched for Garden
[15/05/2021, 11:26:52] [Ring] From Ring (Garden): Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'pipe:':

[15/05/2021, 11:26:52] [Ring] From Ring (Garden):   Metadata:
    title           : Talk
  Duration: N/A, start: 0.000000, bitrate: 64 kb/s
    Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s

[15/05/2021, 11:26:52] [Ring] From Ring (Garden): Stream mapping:
  Stream #0:0 -> #0:0 (pcm_mulaw (native) -> aac (libfdk_aac))

[15/05/2021, 11:26:52] [Ring] From Ring (Garden): Output #0, rtp, to 'srtp://10.173.45.20:57847?localrtcpport=11715&pkt_size=188':
  Metadata:
    title           : Talk
    encoder         : Lavf58.45.100

[15/05/2021, 11:26:52] [Ring] From Ring (Garden):     Stream #0:0: Audio: aac (libfdk_aac) (ELD), 16000 Hz, mono, s16, 24 kb/s
    Metadata:
      encoder         : Lavc58.91.100 libfdk_aac

[15/05/2021, 11:26:52] [Ring] Video stream latched for Garden
[15/05/2021, 11:26:52] [Ring] Received stream data from Garden (0.823s)
[15/05/2021, 11:26:52] [Ring] Streaming active for Garden
[15/05/2021, 11:26:53] [Ring] Used cached snapshot for Den
[15/05/2021, 11:26:53] [Ring] Loading new snapshot into cache for Den
[15/05/2021, 11:26:53] [Ring] Used cached snapshot for Front Door
[15/05/2021, 11:26:53] [Ring] Loading new snapshot into cache for Front Door
[15/05/2021, 11:26:53] [Ring] Used cached snapshot for Side Gate
[15/05/2021, 11:26:53] [Ring] Loading new snapshot into cache for Side Gate
[15/05/2021, 11:26:53] [Ring] Used cached snapshot for Hallway
[15/05/2021, 11:26:53] [Ring] Loading new snapshot into cache for Hallway
[15/05/2021, 11:26:53] [Ring] Used cached snapshot for Lounge
[15/05/2021, 11:26:53] [Ring] Loading new snapshot into cache for Lounge
[15/05/2021, 11:26:53] [Ring] Used cached snapshot for Garden
[15/05/2021, 11:26:53] [Ring] Loading new snapshot into cache for Garden
[15/05/2021, 11:26:53] [Ring] Used cached snapshot for Kitchen
[15/05/2021, 11:26:53] [Ring] Loading new snapshot into cache for Kitchen
[15/05/2021, 11:26:53] [Ring] Used cached snapshot for Gate
[15/05/2021, 11:26:53] [Ring] Loading new snapshot into cache for Gate
[15/05/2021, 11:26:53] [Ring] Used cached snapshot for Dining Room
[15/05/2021, 11:26:53] [Ring] Loading new snapshot into cache for Dining Room
[15/05/2021, 11:26:53] [Ring] Used cached snapshot for Patio
[15/05/2021, 11:26:53] [Ring] Loading new snapshot into cache for Patio
[15/05/2021, 11:26:54] [Ring] Snapshot cached for Kitchen (0.958s)
[15/05/2021, 11:26:54] [Ring] From Ring (Garden): size=       0kB time=00:00:00.01 bitrate= 109.1kbits/s speed=0.00701x    
[15/05/2021, 11:26:54] [Ring] Stopped Live Stream for Garden
[15/05/2021, 11:26:54] [Ring] Return Audio (Garden): stopped gracefully
[15/05/2021, 11:26:54] [Ring] Return Audio (Garden): Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'pipe:':
  Metadata:
    title           : Talk
  Duration: N/A, bitrate: N/A
    Stream #0:0: Audio: aac, 16000 Hz, mono, s16
Stream mapping:
  Stream #0:0 -> #0:0 (aac (libfdk_aac) -> pcm_mulaw (native))
Finishing stream 0:0 without any data written to it.

[15/05/2021, 11:26:54] [Ring] Return Audio (Garden): Output #0, rtp, to 'srtp://127.0.0.1:53601?pkt_size=188':
  Metadata:
    title           : Talk
    encoder         : Lavf58.45.100

[15/05/2021, 11:26:54] [Ring] Return Audio (Garden):     Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
    Metadata:
      encoder         : Lavc58.91.100 pcm_mulaw

[15/05/2021, 11:26:54] [Ring] Return Audio (Garden): size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)

[15/05/2021, 11:26:54] [Ring] Return Audio (Garden): Exiting normally, received signal 15.

[15/05/2021, 11:26:54] [Ring] Snapshot cached for Gate (1.055s)
[15/05/2021, 11:26:54] [Ring] From Ring (Garden): stopped gracefully
[15/05/2021, 11:26:54] [Ring] From Ring (Garden): [sdp @ 0x27b3630] max delay reached. need to consume packet
[sdp @ 0x27b3630] RTP: missed 5 packets

[15/05/2021, 11:26:54] [Ring] From Ring (Garden): size=       1kB time=00:00:00.18 bitrate=  32.3kbits/s speed=0.0854x    
video:0kB audio:1kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 17.252396%

[15/05/2021, 11:26:54] [Ring] From Ring (Garden): Exiting normally, received signal 15.

[15/05/2021, 11:26:54] [Ring] requesting key frame
(node:26769) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
    at SipCall.request (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
    at SipCall.sendKeyFrameRequest (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
    at SipCall.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
(node:26769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)
[15/05/2021, 11:26:54] [Ring] Snapshot cached for Hallway (1.561s)
[15/05/2021, 11:26:54] [Ring] Snapshot cached for Lounge (1.552s)
[15/05/2021, 11:26:55] [Ring] Snapshot cached for Garden (1.686s)
[15/05/2021, 11:26:55] [Ring] Snapshot cached for Dining Room (1.646s)
[15/05/2021, 11:26:55] [Ring] Snapshot cached for Patio (1.809s)
[15/05/2021, 11:26:55] [Ring] Snapshot cached for Den (2.256s)
[15/05/2021, 11:26:56] [Ring] Snapshot cached for Front Door (3.47s)
[15/05/2021, 11:26:56] [Ring] Snapshot cached for Side Gate (3.553s)
[15/05/2021, 11:26:58] [Ring] From Ring (Garden): stopped gracefully
[15/05/2021, 11:26:58] [Ring] From Ring (Garden): pipe:: Connection timed out

[15/05/2021, 11:26:58] [Ring] From Ring (Garden): size=     103kB time=00:00:30.12 bitrate=  28.1kbits/s speed=0.752x    
video:0kB audio:88kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 16.856377%

[15/05/2021, 11:26:58] [Ring] From Ring (Garden): Exiting normally, received signal 15.

**Comment by SpikePlayz** [comment]
I have this exact same issue with my Ring Video Doorbell Pro 1st Generation.

**Comment by dgreif** [comment]
Hey all, thanks for weighing in.  This has been a long standing issue and is being tracked in #479.  I have some ideas on how to fix it, but haven't had the time to try them all out.  The short story is that Ring is migrating all of their video streaming over to a new set of media servers which run different software.  I've put a lot of effort into getting streaming working with those servers, but the 30 second cutoff is something specific to those new servers.  As they move users over (seemingly at random), more and more homebridge users are experiencing this issue.  For now there is nothing you can do on your end, I just need to keep trying ideas until I find the right combination to make the new servers happy and keep the stream open.  Thanks for your patience!

**Comment by adavison007** [comment]
@dgreif Thanks fo the update, appreciate the continued efforts :)
