### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by DerRemo** [dgreif/ring#69]
Hi, I get the following error wen starting home bridge:

> Loaded plugin: homebridge-ring
/usr/local/lib/node_modules/homebridge/lib/server.js:166
      plugin.initializer(this._api);
             ^
   TypeError: plugin.initializer is not a function
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:166:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:140:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:28:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

Homebridge-Version is the newest and node 10.16.

**Comment by dgreif** [comment]
@DerRemo I just tried with the following versions:

`homebridge`: `0.4.50`
`node`: `10.16.0`
`homebridge-ring`: `4.0.7`

Everything started up just fine, so there must be something else specific to your setup.  I don't know your background, but if you are able to debug this a little bit on your end you can add some `console.log()`s in https://github.com/nfarina/homebridge/blob/master/lib/plugin.js#L72-L79 to verify the initializer is getting set.  Not sure what else I can do from my end, sorry!

**Comment by dgreif** [comment]
@DerRemo any luck getting it to work?

**Comment by DerRemo** [comment]
> @DerRemo any luck getting it to work?

Not yet.

**Comment by dgreif** [comment]
@DerRemo I'm going to close this as it appears to be specific to your setup.  Let me know if you have any questions that I can answer

**Comment by dgreif** [comment]
See #12 and #151.  Looks like it's an issue with older versions of homebridge and you just need to update to the latest
