### ISSUE TITLE
v9.19.0 is no bueno - But v9.18.6 still works

### ISSUE THREAD

**Issue by mikesalz** [dgreif/ring#717]
# Bug Report

### Describe the Bug
 Upgraded to homebridge-ring v9.19.0 and then it went kablooey.  v9.18.6 DOES work.

### To Reproduce
 - Start Homebridge
 - Upgrade to v9.18.6
 - Grab some popcorn and watch it blow up

### Expected behavior
 Not this

### Screenshots/Logs
 
```

[8/1/2021, 7:39:41 PM] [Ring] Request to https://api.ring.com/clients_api/ring_devices failed with status 200. Response body: �YY���+��[݇߂
           �i�l��` �e1-���{��I����y�6�HV��:�nR��w��˻%
k�����U�.oŹ�����l��'p[D���g�nq'(�)s}�zq��/�� ���[��?��_����n8Щ��};��Jv�tDє�{޾e�(qZ3����_�԰:�e��\
                                                                                                W��)�ӕ�<���R�t��r���w�����Evq�f��g{ɳ�i�5�͢�x�a&a�d��hyɬ4q��?va���ّ�>�O���tfO�~��~�Ev�����μ�Es��w+�d˟�Y�v抣N
                                                                             ��[�a�z��I��/��K�s�B��+aim��7RE�V�xu���9�����4��������ɾ�q��d�Q�3�_�Y�k�z�>b���E�2��Ǚx���wV��C�/��u�"��xDL ƿ�'|��D����6.�N��s��������յ��ڭ ����"�s�[�|#�U��!���F|V�WF���O1�U\�lui���L.8��Z�����-�����;��V�Q|e'�DQWa�M��t ��r�,���lϏ
                                                  ;����!�}��K7
                                                              s�h�N�?�'L�       �$`�V�y�
                                                                                        ��7��e|D����5�Z{��
                                                                                                          b��'
                                                                                                              n�<ǡ��I���P}/��3�$�T'��7��O� �&r�&Az9�<?If�:a�NWiE�;���L=�
                                          �i�n���rwZu\�Mq��uz���8���~��v�����Cd��!g��[����X�?���(-�a���$~�n�EHH�=`7��Y��q�0@�V��Mgޜ����G��I
[x�l�g6�2~���xq'勃$p�d~�(��8"��$t�o_�!Z����k����7�*nk�)fF�g��p�%+����ǡ$��zPg7Q� ���o򷌕�u�%�OCED���j�'$��3/x�)F>�C��|�98�'���g9U5Fy
��S�/��JQC%~ǛN�&z<
g4q>Cé�Zi��EUh�$�"�c��Lb����;�}�d7�}�i7��n7�}�s�ψZ��]�߂ea�Xxc���h���X�g�ݎ�%��!��k�̺~Ӵ�Soi�w��f����>xK�mtK��sK[xؤ���Į��~��J1�U2��5�F�xho㋡5m����,W��YM��e�A�=������G"��<��-�R{�G���a�J����Fέ�"����gp�߬{�Z�&o�T{����Z�qHs�+B�q�j�eLMn�5��vN����]�rv�b����S׶
                                                                                                                         x̩��l�7��i\���t�-Z��Q2�~3�;��ش#\������(��G���
љ�ܔ*���${�>�lٚO��[Jv�,A5$��ﰖ
JɆ��o!,���tROu�C�����{-�B%���N�޺�������7mi]�w�b�s��ym�;u9�&G-U� f�,�bcS�

��(�XYɂ��V=�!koHݜ~ǔ��W:QŊ1u|fhF��
m(m.�Km����9zɖ-�h��e�<3���f�L��ni����b(g��h��Gs�~u��Y7��{�CM��  #��S>�"ԓ+˫���.m��n�:�퐇�sI�~6�,���{e�KvD�|��x��Ga�YK�vpx����a�ҟ)IW*j}��ۻ�����������t
Y�0�Cm�               �����SǮGs�
����lܶ��Y�bf:�so
ZKY��u��赢����b'ZN(:Y��50]-)�تp��G��8�E*����]�O�GO���W�~����� ���%����,���P0�oGs�!2x?J��YC���k��́�gTR��ƾ��r����F�%M�2ÆNP6E��,Ȇ���{������*
r2�(
��q�b���YT�<�4�]�`8�)B�|����@�`Qdjܢ�ac��J��يl�  U->'`�����ݟh��B��N��C��_�Q�W�u�X��f�S   ?��Ô#��԰~ES�p���Id�NR�c��0����+M�|r�
                                                                                                                            S5�͡+��X|�9ر��c���0J�(IxzӢ
                       ������2i��(Y)�?[l��w���+CU�"�"
                                                     uT|������Ӊ�خk{�g7ڇ�>p煉���ƹ���:�)?�Y�#WQSK�Ļ��
|BZ.i����/��Gm
[8/1/2021, 7:39:41 PM] [Ring] Error connecting to API
[8/1/2021, 7:39:41 PM] [Ring] RequestError: Unexpected token  in JSON at position 0 in "https://api.ring.com/clients_api/ring_devices"
    at Object.parseBody [as default] (/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/parse-body.js:22:15)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:72:61)
    at JSON.parse (<anonymous>)
    at parseJson (/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/index.js:118:35)
    at Object.parseBody [as default] (/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/parse-body.js:11:48)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:72:61)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'ParseError',
  code: undefined,
  timings: {
    start: 1627846781106,
    socket: 1627846781107,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: 1627846781107,
    response: 1627846781350,
    end: 1627846781352,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: NaN,
      firstByte: 243,
      download: 2,
      total: 246
    }
  }
}
```

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
That looks like a weird issue with data from the Ring servers.  Can you try upgrading again and see if the error happens consistently on `9.19.0`?

**Comment by mikesalz** [comment]
Thanks for getting back to me.  Yes, you are right!  I reinstalled 9.19.0 and restarted Homebridge a few times.  It worked every time.  So I guess I just had bad luck the first time I ran it.
