### ISSUE TITLE
Live streaming doesn't work 70% of the time

### ISSUE THREAD

**Issue by eliteladen** [dgreif/ring#719]
Ring Doorbell Gen 1,

When clicking for live view, the stream simply doesn't work, it takes about 4-6 tries for it to work almost every time, same error message shows:

[03/08/2021, 11:19:53] [Ring] Preparing Live Stream for Campainha
[03/08/2021, 11:19:54] [Ring] Waiting for stream data from Campainha (0.88s)
[03/08/2021, 11:20:02] [Ring] Stopped Live Stream for Campainha
[03/08/2021, 11:20:02] [Ring] Failed to prepare stream for Campainha (9.1s)
[03/08/2021, 11:20:02] [Ring] Error: 
    at _super (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/createErrorClass.ts:13:22)
    at new EmptyErrorImpl (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/EmptyError.ts:26:3)
    at Object.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/lastValueFrom.ts:72:18)
    at Object.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:194:14)
    at SafeSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at SafeSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12) {
  message: 'no elements in sequence'
}

**Comment by dgreif** [comment]
Sorry to hear it's not reliable for you. This is likely a side effect of your network setup.  The plugin is a best-effort to support live streams but it's simply not reliable on some networks.  I encourage you to take a look at https://github.com/dgreif/ring/wiki/Camera-Troubleshooting.  Beyond that, there isn't anything I can do.
