### ISSUE TITLE
After switching to text 2fa I cannot reconnect

### ISSUE THREAD

**Issue by jackgithome** [dgreif/ring#724]
I just updated form email to text 2fa with ring.  When trying to get a new token I keep getting the following error and it won't connect.  I haven't changed anything else and have tried updating the token multiple times with the same results.

-------------------------------------------------------
| Ring Device Integration via MQTT                    |
| Addon for Hass.io                                   |
|                                                     |
| Report issues at:                                   |
| https://github.com/tsightler/ring-mqtt-hassio-addon |
-------------------------------------------------------
Node version v12.15.0
NPM version 6.13.4
git version 2.24.1
-------------------------------------------------------
Running "npm audit fix" to update packages with any vulnerabilities...
added 3 packages from 4 contributors, removed 4 packages, updated 24 packages and moved 1 package in 15.701s
7 packages are looking for funding
  run `npm fund` for details
fixed 23 of 29 vulnerabilities in 388 scanned packages
  2 vulnerabilities required manual review and could not be updated
  2 package updates for 4 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
-------------------------------------------------------
Running ring-mqtt.js version 3.0.1...
2021-08-06T03:41:38.388Z ring-mqtt Configuration file read from: /data/options
2021-08-06T03:41:38.887Z ring-mqtt Error: Request failed with status code 404
    at createError (/ring-mqtt/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/ring-mqtt/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/ring-mqtt/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
2021-08-06T03:41:38.889Z ring-mqtt Couldn't create the API instance. This could be because the Ring servers are down/unreachable
2021-08-06T03:41:38.890Z ring-mqtt or maybe the refreshToken is invalid. Please check settings and try again.
2021-08-06T03:41:38.892Z ring-mqtt Exit code: 2

**Comment by dgreif** [comment]
I don't see anything in here related to the `ring-client-api`.  Did you mean to open an issue on https://github.com/tsightler/ring-mqtt-hassio-addon?

**Comment by jackgithome** [comment]
Yes, sorry.
