### ISSUE TITLE
Cannot launch livestream

### ISSUE THREAD

**Issue by eliassylvain** [dgreif/ring#725]
Hello,

Since couple week, I am not able anymore to launch the livestream from my Ring Video dorbell 3.

Here are the logs of the error shown on the homebridge : 
06/08/2021, 09:56:40] [Ring] Preparing Live Stream for Sonnette Portail
[06/08/2021, 09:56:40] [Ring] Waiting for stream data from Sonnette Portail (0.554s)
[06/08/2021, 09:56:49] [Ring] Stopped Live Stream for Sonnette Portail
[06/08/2021, 09:56:49] [Ring] Failed to prepare stream for Sonnette Portail (9.031s)
[06/08/2021, 09:56:49] [Ring] Error: 
    at _super (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/createErrorClass.ts:13:22)
    at new EmptyErrorImpl (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/EmptyError.ts:26:3)
    at Object.complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/lastValueFrom.ts:72:18)
    at Object.complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:194:14)
    at SafeSubscriber.Subscriber._complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at SafeSubscriber.Subscriber.complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (/usr/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12) {
  message: 'no elements in sequence'

 - Ring Camera: Dorbell 3
 - OS: Debian
 - Node.js: v14.17.4
 - NPM: v6.14.8
 - homebridge-ring (if applicable): v9.20.0
 - homebridge (if applicable): v1.3.4

Any help will be really appreciated, thank you in advance.

# Live Streaming Issue

### Describe the live streaming issue
 A clear and concise description of the problem.  If all you can say is that "live streaming doesn't work on my network", then please do not open an issue.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Recommended solution
 Please describe what you think is causing this issue, and how you recommend it be fixed

### Environment

 - Ring Camera: [e.g. Stickup Cam Battery]
 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring (if applicable): [e.g 6.0.3 or N/A]
 - homebridge (if applicable): [e.g. 0.4.50 or N/A]
 - hoobs (if applicable): [e.g. 0.4.50 or N/A]

### Network Environment
 Please provide a detailed description of your network setup, including all network hardware between your camera, the internet, your homebridge server, and your HomeKit home hub (Apple TV, HomePod, iPad).  Please include brand and model for each device that the network traffic passes through.

**Comment by dgreif** [comment]
Please see https://github.com/dgreif/ring/wiki/Camera-Troubleshooting
