### ISSUE TITLE
sip INVITE request failed with status 503

### ISSUE THREAD

**Issue by etai** [dgreif/ring#730]
Hi,

I just installed my Ring as a new device on Homebridge, and it was working for around a day or so, I now get the following error when trying to stream video fro my front door:

`[8/8/2021, 3:25:45 PM] [Ring] sip INVITE request failed with status 503
[8/8/2021, 3:25:45 PM] [Ring] Failed to prepare stream for Front Door (0.046s)
[8/8/2021, 3:25:45 PM] [Ring] Error: sip INVITE request failed with status 503
    at /homebridge/node_modules/homebridge-ring/lib/api/sip-call.js:147:28
    at next (/homebridge/node_modules/homebridge-ring/lib/api/sip.js:1153:13)
    at searching (/homebridge/node_modules/homebridge-ring/lib/api/sip.js:1159:20)
    at /homebridge/node_modules/homebridge-ring/lib/api/sip.js:1144:32
    at Object.message (/homebridge/node_modules/homebridge-ring/lib/api/sip.js:943:13)
    at Object.signal (/homebridge/node_modules/homebridge-ring/lib/api/sip.js:824:63)
    at TLSSocket.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/api/sip.js:1142:28)
    at TLSSocket.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
(node:7028) UnhandledPromiseRejectionWarning: Error: 
    at _super (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/createErrorClass.ts:13:22)
    at new EmptyErrorImpl (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/EmptyError.ts:26:3)
    at Object.complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/lastValueFrom.ts:72:18)
    at Object.complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:194:14)
    at SafeSubscriber.Subscriber._complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at SafeSubscriber.Subscriber.complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (/homebridge/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
(node:7028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[8/8/2021, 3:25:49 PM] [Ring] Preparing Live Stream for Front Door
err:  Error: connect EHOSTUNREACH 52.16.178.119:15064
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '52.16.178.119',
  port: 15064
}`

**Comment by dgreif** [comment]
Are you able to stream from that camera in the Ring app? I think this can happen if the battery is dead

**Comment by etai** [comment]
Hmmm no the battery is fine but I can stream now. It looks like I temporarily lost internet connection to my server.
