### ISSUE TITLE
Ring Floodlight Cam No Longer Responds in HomeBridge 

### ISSUE THREAD

**Issue by Johnrr6** [dgreif/ring#738]
# Bug Report

### Describe the Bug
<!-- Ring Floodlight Cam No Longer Responds in Homebridge,Ring Doorbell Cam working Fine...Floodlight Cam works fine in RING software 08-14-2021

### To Reproduce
 - Start Homebridge
 - Have taken these steps
 - Updated Mac to latest OS
 - Updated iPhone to Latest OS
 - Updated Apple TV to latest OS
 - Updated HomeBridge UI and Ring Plugin to latest 
 - Restarted Ring Floodlight Cam after ensuring latest firmware
 - Restarted all devices
 - See error log below

### Expected behavior
Expected behavior is Ring Floodlight Camera used to work fine in Homekit....it no longer does so

### Screenshots/Logs
[8/14/2021, 1:52:39 PM] [Ring] Waiting for stream data from Front (0.46s)
[8/14/2021, 1:52:48 PM] [Ring] Stopped Live Stream for Front
[8/14/2021, 1:52:48 PM] [Ring] Failed to prepare stream for Front (9.127s)
[8/14/2021, 1:52:48 PM] [Ring] Error: 
    at _super (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/createErrorClass.ts:13:22)
    at new EmptyErrorImpl (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/EmptyError.ts:26:3)
    at Object.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/lastValueFrom.ts:72:18)
    at Object.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:194:14)
    at SafeSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at SafeSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12) {
  message: 'no elements in sequence'
}
[8/14/2021, 1:52:48 PM] [Ring] Snapshot for Front (hp_cam_v2 - Spotlight Cam) failed to refresh after 70 attempts
```
### Additional context
Ring Floodlight camera works fine in Ring software

### Homebridge Ring Config
{
    "bridge": {
        "name": "Homebridge 5A20",
        "username": "0E:66:BE:24:5A:20",
        "port": 51219,
        "pin": "763-49-144"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "refreshToken": xxx
        }
    ]
}
HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment
Timezone | GMT-0400
-- | --
macOS
JOHNs-Mac-mini.local
192.168.1.29
fe80::1090:17cb:f9ea:8db8
v12.18.1
v6.14.5
xxx
/Users/jxxx/.homebridge
/Users/jxxx/.homebridge/config.json
Yes

**Comment by Johnrr6** [comment]
Please close Bug...Floodlight cam working fine now.

Appears last update to plugin which occurred a few hours ago has repaired the issue.

**Comment by Johnrr6** [comment]
Appears last plugin update of a few hours ago solved this issue.  Ring Floodlight cam now working again in HomeKit
