### ISSUE TITLE
Live Streaming Error

### ISSUE THREAD

**Issue by JoaoCharnetTR** [dgreif/ring#781]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
When accessing the live view in home kit, I get a camera offline, and when looking at the logs I see an error. Logs bellow

### To Reproduce
 - Start Home App
 - Attempt to view live stream from Ring
 - Shows offline after a few seconds

### Expected behavior
 A clear and concise description of what you expected to happen.
Should be able to live stream

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
[29/09/2021, 16:55:38] [homebridge-ring] Preparing Live Stream for Front Door
[29/09/2021, 16:55:38] [homebridge-ring] Waiting for stream data from Front Door (0.842s)
[29/09/2021, 16:55:47] [homebridge-ring] Stopped Live Stream for Front Door
[29/09/2021, 16:55:47] [homebridge-ring] Failed to prepare stream for Front Door (9.066s)
[29/09/2021, 16:55:47] [homebridge-ring] Error: 
    at _super (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/createErrorClass.ts:13:22)
    at new EmptyErrorImpl (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/util/EmptyError.ts:26:3)
    at Object.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/lastValueFrom.ts:72:18)
    at Object.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:194:14)
    at SafeSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at SafeSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:106:12) {
  message: 'no elements in sequence'
}
### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

{
            "refreshToken": "xxx",
            "alarmOnEntryDelay": false,
            "_bridge": {
                "username": "xxx",
                "port": xxx
            },
            "platform": "Ring"
        },

```

### Environment

 - OS: Raspbian GNU/Linux Buster (10)
 - Node.js: v14.15.4
 - NPM: 6.14.10
 - homebridge-ring: homebridge-ring v9.21.2
 - homebridge: 1.3.4
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by JoaoCharnetTR** [comment]
Seems it's working now, maybe it was a Ring problem.
Ignore this please.
