### ISSUE TITLE
Ring fails to stream camera

### ISSUE THREAD

**Issue by witchdrash** [dgreif/ring#819]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

### To Reproduce
 - Start Homebridge
 - Attempt to stream from ring doorbell
 - See error:
 - [11/8/2021, 8:54:56 AM] [Ring] Failed to prepare stream for Front Door (0.022s)
[11/8/2021, 8:54:56 AM] [Ring] TypeError: (0 , camera_utils_1.doesFfmpegSupportCodec) is not a function
    at CameraSource.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/homebridge/camera-source.js:156:63)
    at Generator.next (<anonymous>)
    at /homebridge/node_modules/homebridge-ring/lib/homebridge/camera-source.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/homebridge/node_modules/homebridge-ring/lib/homebridge/camera-source.js:4:12)
    at CameraSource.prepareStream (/homebridge/node_modules/homebridge-ring/lib/homebridge/camera-source.js:140:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:977:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:59797) UnhandledPromiseRejectionWarning: TypeError: camera_utils_1.RtpSplitter is not a constructor
    at RingCamera.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/api/ring-camera.js:443:35)
    at Generator.next (<anonymous>)
    at /homebridge/node_modules/homebridge-ring/lib/api/ring-camera.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/homebridge/node_modules/homebridge-ring/lib/api/ring-camera.js:4:12)
    at RingCamera.createSipSession (/homebridge/node_modules/homebridge-ring/lib/api/ring-camera.js:442:16)
    at CameraSource.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/homebridge/camera-source.js:145:37)
    at Generator.next (<anonymous>)
    at /homebridge/node_modules/homebridge-ring/lib/homebridge/camera-source.js:8:71
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59797) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:59797) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Expected behavior
 Doorbell streams successfully

### Screenshots/Logs
 N/A

### Additional context
 N/A

### Homebridge Ring Config
{
      "refreshToken": -removed-
      "platform": "Ring"
  },

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

### Environment

 - OS: Homebridge Docker container
 - Node.js: [e.g. 12.14.1] 14.17.3
 - NPM: [e.g 6.13.4] 6.14.13
 - homebridge-ring: 9.23.0
 - homebridge: 1.3.5
 - hoobs: N/A

**Comment by dgreif** [comment]
Odd, I'm not sure what exactly is leading to this error.  I'd say your npm modules are messed up somehow.  Can you try removing the plugin and re-installing?
