### ISSUE TITLE
[Streaming]: 

### ISSUE THREAD

**Issue by SamTheGeek** [dgreif/ring#839]
### Streaming Issue

All live streams result in `Ding XXX is expired (480).  Fetching a new ding and trying video stream again` followed by `err:  Error: remote peer disconnected` — which is normal and expected. 

However, it appears that a new ding is not being fetched. The retries are all attempted with the same Ding ID.

I have generated a new refresh token and tried on multiple devices.

### Proposed Solution

I'm not sure why the ding is not refreshing, the issue is somewhere with how the new ding is being retrieved and used.

### Environment

Homebridge

### What operating system are you on?

Linux

### Relevant log output

```shell
[12/15/2021, 12:37:23 PM] [Ring] Ding [...]89764 is expired (480).  Fetching a new ding and trying video stream again
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/api/sip.js:557:38)
    at TLSSocket.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[12/15/2021, 12:37:23 PM] [Ring] Ding [...]89764 is expired (480).  Fetching a new ding and trying video stream again
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/api/sip.js:557:38)
    at TLSSocket.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[12/15/2021, 12:37:23 PM] [Ring] Ding [...]89764 is expired (480).  Fetching a new ding and trying video stream again
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/api/sip.js:557:38)
    at TLSSocket.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[12/15/2021, 12:37:24 PM] [Ring] Ding [...]89764 is expired (480).  Fetching a new ding and trying video stream again
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/api/sip.js:557:38)
    at TLSSocket.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by JacVid** [comment]
Same "problem" for me. Is there a config to adjust ?

**Comment by Lemmons** [comment]
This appears to be an issue related to homebridge-config-ui-x v4.41.5.  I only noticed the issue after upgrading to v4.41.5 and downgrading to v4.41.4 fix the issue for me.

**Comment by SamTheGeek** [comment]
@Lemmons thanks for the insight! Any idea what causes the issue? I'd like to let @oznu know

**Comment by dgreif** [comment]
I'm not having any issues on `4.41.5` of homebridge ui.  It's possible that simply rebooting homebridge fixed the issue.  Can you try updating to 4.41.5 again and confirm it fails with the same error listed in the logs above?

**Comment by SamTheGeek** [comment]
Huh, I was seeing this error on Homebridge UI `4.41.5` (I never downgraded) until about 12/18 and then it stopped after a restart and hasn't reappeared.

**Comment by SamTheGeek** [comment]
It has begun again, as of 1/5. I'll reboot and see if that fixes the issue.

**Comment by SamTheGeek** [comment]
It has continued to happen intermittently — regardless of Homebridge, Config-UI-X, and Homebridge-Ring version. Seems like somewhere the 'fetch a new ding' can get into a state where a new ding cannot be fetched for whatever reason

**Comment by dgreif** [comment]
When you start your homebridge server, do you see something in your logs along the lines of `Unable to get system uuid.  Falling back to random session id`?

**Comment by SamTheGeek** [comment]
Nothing of that sort at all, actually. Just `[Ring] Configuring cached accessory <GUID>` and then later `[Ring] Found the following locations: locationID:<GUID>`

**Comment by SamTheGeek** [comment]
Doing some more digging here and it's clear that even across multiple days the ding isn't being refreshed. What is interesting is that this might not be an issue with Homebridge-Ring. I also cannot stream from the Rapid Ring app when this occurs.

**Comment by SamTheGeek** [comment]
For anyone who finds this in the future, the root problem was actually poor connectivity between Ring's cloud service and my doorbell. Doing some changes to the network configuration that ensured a consistent and fast connection solved the problem. 

It seems as if Ring's battery-powered doorbells very much do not like anything but perfect wireless signal (weird for a product designed to be used outside).
