### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by devlinandrew** [dgreif/ring#844]
# Bug Report

### Describe the Bug
Homebridge-Ring plugin suddenly won't start when HomeBridge boots.  I get an error in the logs:

`[12/26/2021, 10:05:35 PM] Homebridge v1.3.8 (HAP v0.9.7) (Homebridge) is running on port 51826.
[12/26/2021, 10:05:35 PM] ====================
[12/26/2021, 10:05:35 PM] ERROR LOADING PLUGIN homebridge-ring:

[12/26/2021, 10:05:35 PM] RangeError: Maximum call stack size exceeded
`

Homebridge starts just fine, but I have no cameras in the accessories section nor in the Home app.

### To Reproduce
 - Start Homebridge
 - See error in Logs

### Expected behavior
Cameras show up in the Home app.  This worked until a few days ago.

### Screenshots/Logs

`[12/26/2021, 10:05:35 PM] Homebridge v1.3.8 (HAP v0.9.7) (Homebridge) is running on port 51826.
[12/26/2021, 10:05:35 PM] ====================
[12/26/2021, 10:05:35 PM] ERROR LOADING PLUGIN homebridge-ring:

[12/26/2021, 10:05:35 PM] RangeError: Maximum call stack size exceeded
at Function.Array.from (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/collections/shim-array.js:29:23)
at Function.Array.from (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/collections/shim-array.js:31:22)
at Function.Array.from (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/collections/shim-array.js:31:22)
[12/26/2021, 10:05:35 PM] ====================`

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
        {
            "refreshToken": "token",
            "platform": "Ring"
        },
```

### Environment
 - OS: Unraid Docker
 - Node.js: v12.20.1
 - NPM: v6.14.10
 - homebridge-ring: v9.23.0
 - homebridge: v1.3.8
 - hoobs: N/A

**Comment by dgreif** [comment]
Based on the path from the error (`homebridge-camera-ffmpeg/node_modules/collections/shim-array.js`), I think this is actually an issue from another plugin.  Closing in favor of https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/1240
