### ISSUE TITLE
Plug-In not working at all

### ISSUE THREAD

**Issue by lostboyrulz** [dgreif/ring#929]
# Bug Report

### Describe the Bug
 I did an update for the ring plug-in to v.10, which said it was successful. Upon going back to the home app homepage the ring accessories just vanished. In the morning it said there was another update. I did this and updated to the latest version of v.11.0.0 This still has not fixed the issue and when restarting homebridge, it now says there is no plug-in found for ring. (this is in red text)
I have uninstalled and re-installed and re-connected my account with a new refresh token, but this has still not helped. There is nothing in the logs to suggest anything has gone wrong. 

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
I expected the homebridge to restart and everything be fine as it has been for the last several months
![Ring not loading 1](https://user-images.githubusercontent.com/69427493/167616940-f95761bc-cecb-4724-a1ac-42a83a649659.jpg)
![Ring not loading 2](https://user-images.githubusercontent.com/69427493/167616993-0d120654-9403-4809-a6ce-b4a2b1ce648f.jpg)
.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config---- I have uploaded the config which does not show the full ring config like it did before.
![Config screen](https://user-images.githubusercontent.com/69427493/167617990-999c2bd2-c278-4936-85ec-677daff55325.jpg)

```

 },
        {
            "refreshToken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxREFRESH TOKENxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "showPanicButtons": true,
            "platform": "Ring"
        }
    ]
}

```

### Environment

 - OS: Ubuntu
 - Node.js: [e.g. 12.14.1]  NO IDEA HOW TO DO THIS SORRY
 - NPM: [e.g 6.13.4] NO IDEA HOW TO DO THIS SORRY
 - homebridge-ring: 11.0.0
 - homebridge: 1.4.1
 - hoobs: N/A

**Comment by n8stowell82** [comment]
I am running into the exact same errors

**Comment by dgreif** [comment]
You need to update to node 16 for v10/11 to work properly

**Comment by xImportExportx** [comment]
I am having a similar issue, I have checked and my node version is reported as v16

logs show the following, I am running onus's docker image in this case. Version 9.2.4 fixed my issue as well.

[5/10/2022, 12:20:28 PM] Error: Cannot get schema for 'Array' target
    at AsnSchemaStorage.get (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/asn1-schema/build/cjs/schema.js:18:19)
    at Function.toASN (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/asn1-schema/build/cjs/serializer.js:21:48)
    at Function.toAsnItem (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/asn1-schema/build/cjs/serializer.js:136:33)
    at Function.toASN (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/asn1-schema/build/cjs/serializer.js:46:46)
    at Function.serialize (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/asn1-schema/build/cjs/serializer.js:14:21)
    at Function.serialize (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/asn1-schema/build/cjs/convert.js:10:43)
    at Function.create (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/x509/build/x509.cjs.js:1740:43)
    at Function.CipherContext.createSelfSignedCertificateWithKey (/homebridge/node_modules/homebridge-ring/node_modules/@koush/dtls/src/context/cipher.ts:111:18)
    at RTCDtlsTransport.setupCertificate (/homebridge/node_modules/homebridge-ring/node_modules/@koush/werift/src/transport/dtls.ts:69:9)
    at ensureCert (/homebridge/node_modules/homebridge-ring/node_modules/@koush/werift/src/peerConnection.ts:1039:9)

**Comment by dgreif** [comment]
@xImportExportx I haven't seen that error before.  Maybe try updating to a later version of node 16 if you aren't on the latest

**Comment by xImportExportx** [comment]
@dgreif I am on the latest version of node v16.15.0

**Comment by shayweiss** [comment]
@dgreif - I had the same issue. Upgrading Node.Js to v16.5.0 fixed the error on HB, but now I don't get any Live Stream from the camera via HomeKit... any idea?

**Comment by nicolle19** [comment]
> You need to update to node 16 for v10/11 to work properly

How do you update to node 16?

**Comment by n8stowell82** [comment]
@nicolle19 follow these instructions: https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js

**Comment by kbrashears5** [comment]
for me, `sudo apt install nodejs` was only installing 14.x, so I had to follow [this](https://joshtronic.com/2021/05/09/how-to-install-nodejs-16-on-ubuntu-2004-lts/)

after that, ring plugin loads successfully
