### ISSUE TITLE
iOS 16 Beta Remote Streaming Issue

### ISSUE THREAD

**Issue by donavanbecker** [dgreif/ring#978]
### Streaming Issue

Getting no response on remote streaming

### Proposed Solution

Remote streaming to work 
![7A2EB650-F342-4687-ADFB-C540515F0908](https://user-images.githubusercontent.com/9875439/176820019-571c12d4-489e-4f14-9aa0-e982c54220f3.png)

### Environment

Homebridge

### What operating system are you on?

Mac

### Honesty Time

- [X] I swear this is worth your time!

**Comment by rfiorentino1** [comment]
Can you paste the actual output of debug logs etc here? That will likely be very helpful in addressing the issue, especially if it's something new in the Beta. It's pretty early in the beta cycle though, so Apple may just need to fix some things on their end first as well.

**Comment by donavanbecker** [comment]
I can see if there are any logs for it, that give us any good details.

**Comment by rfiorentino1** [comment]
When you say remote streaming, do you mean that you can only access the feed from within your home network? Or you can't stream at all regardless of whether you're connected to Wi-Fi or cellular data? If it's the former, I doubt that's an iOS 16 specific issue

**Comment by lteffertiller** [comment]
I have a similar problem (when using iOS 16 and macOS Ventura that causes a SIGTERM but I'm not confident it's related to iOS 16 specifically. 

The first log is upon opening the preview for the camera.

[06/07/2022, 18:41:25] [Ring] Preparing Live Stream for Front Door
[06/07/2022, 18:41:26] [Ring] Stream Prepared for Front Door (0.441s)
[06/07/2022, 18:41:26] [Ring] Activating stream for Front Door (0.502s)
[06/07/2022, 18:41:26] [Ring] iceConnectionStateChange: completed
[06/07/2022, 18:41:26] Error: Cannot get schema for 'EcDsaSignature' target
    at AsnSchemaStorage.get (/var/lib/homebridge/node_modules/.pnpm/@peculiar+asn1-schema@2.1.7/node_modules/@peculiar/asn1-schema/build/cjs/schema.js:18:19)
    at Function.fromASN (/var/lib/homebridge/node_modules/.pnpm/@peculiar+asn1-schema@2.1.7/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:39:52)
    at Function.parse (/var/lib/homebridge/node_modules/.pnpm/@peculiar+asn1-schema@2.1.7/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:29:26)
    at Function.sign (/var/lib/homebridge/node_modules/.pnpm/@peculiar+webcrypto@1.4.0/node_modules/@peculiar/webcrypto/build/webcrypto.js:1580:50)
    at EcdsaProvider.onSign (/var/lib/homebridge/node_modules/.pnpm/@peculiar+webcrypto@1.4.0/node_modules/@peculiar/webcrypto/build/webcrypto.js:1740:25)
    at EcdsaProvider.sign (/var/lib/homebridge/node_modules/.pnpm/webcrypto-core@1.7.5/node_modules/webcrypto-core/build/webcrypto-core.js:160:28)
    at SubtleCrypto.sign (/var/lib/homebridge/node_modules/.pnpm/webcrypto-core@1.7.5/node_modules/webcrypto-core/build/webcrypto-core.js:1405:39)
    at Function.create (/var/lib/homebridge/node_modules/.pnpm/@peculiar+x509@1.7.2/node_modules/@peculiar/x509/build/x509.cjs.js:1807:47)
    at Function.CipherContext.createSelfSignedCertificateWithKey (/var/lib/homebridge/node_modules/.pnpm/werift@0.15.8/node_modules/dtls/src/context/cipher.ts:108:18)
    at RTCDtlsTransport.setupCertificate (/var/lib/homebridge/node_modules/.pnpm/werift@0.15.8/node_modules/werift/src/transport/dtls.ts:71:9)
    at ensureCert (/var/lib/homebridge/node_modules/.pnpm/werift@0.15.8/node_modules/werift/src/peerConnection.ts:1154:34)
    at RTCPeerConnection.ensureCerts (/var/lib/homebridge/node_modules/.pnpm/werift@0.15.8/node_modules/werift/src/peerConnection.ts:1162:7)
    at RTCPeerConnection.createAnswer (/var/lib/homebridge/node_modules/.pnpm/werift@0.15.8/node_modules/werift/src/peerConnection.ts:1167:5)
    at WeriftPeerConnection.createAnswer (/var/lib/homebridge/node_modules/.pnpm/homebridge-ring@11.0.6/node_modules/homebridge-ring/lib/api/streaming/peer-connection.js:117:24)
    at WebrtcConnection.handleMessage (/var/lib/homebridge/node_modules/.pnpm/homebridge-ring@11.0.6/node_modules/homebridge-ring/lib/api/streaming/webrtc-connection.js:29:32)
[06/07/2022, 18:41:26] Got SIGTERM, shutting down Homebridge...
[06/07/2022, 18:41:26] [Ring] Stopped Live Stream for Front Door
[06/07/2022, 18:41:26] [Ring] connectionStateChange: closed
[06/07/2022, 18:41:26] [Ring] iceConnectionStateChange: closed
[06/07/2022, 18:41:31] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[06/07/2022, 18:41:36] [HB Supervisor] Restarting Homebridge...

**Comment by donavanbecker** [comment]
Closing as haven't had any issues with beta 3
