### ISSUE TITLE
Issue with Ring doorbell switch

### ISSUE THREAD

**Issue by bobafetts3** [dgreif/ring#980]
# Bug Report

### Describe the Bug
Trying to turn off the doorbell switch doesn't work. In the homebridge log it shows a HTTP Error response. The rest of the cameras work fine, just no way to disable the doorbell mechanical switch like the readme etc says. 

[7/1/2022, 1:06:31 PM] [Ring] Request to https://api.ring.com/clients_api/doorbots/4766643/ failed with status 422. Response body: 
[7/1/2022, 1:06:31 PM] [Ring] HTTPError: Response code 422 (Unprocessable Entity)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1656705990902,
    socket: 1656705990905,
    lookup: 1656705990906,
    connect: 1656705990911,
    secureConnect: 1656705991119,
    upload: 1656705991120,
    response: 1656705991265,
    end: 1656705991266,
    error: undefined,
    abort: 1656705991274,
    phases: {
      wait: 3,
      dns: 1,
      tcp: 5,
      tls: 208,
      request: 1,
      firstByte: 145,
      download: 1,
      total: 372
    }
  }
}

### To Reproduce
 - Start Homebridge
 - Attempt to turn off the doorbell mechanical switch (if enabled)
 - See error

### Expected behavior
The doorbell to disable the mechanical doorbell.

### Screenshots/Logs
[7/4/2022, 1:34:44 PM] [Ring] Request to https://api.ring.com/clients_api/doorbots/4766643/ failed with status 422. Response body: 
[7/4/2022, 1:34:44 PM] [Ring] HTTPError: Response code 422 (Unprocessable Entity)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1656966884401,
    socket: 1656966884404,
    lookup: 1656966884404,
    connect: 1656966884411,
    secureConnect: 1656966884620,
    upload: 1656966884621,
    response: 1656966884781,
    end: 1656966884783,
    error: undefined,
    abort: 1656966884791,
    phases: {
      wait: 3,
      dns: 0,
      tcp: 7,
      tls: 209,
      request: 1,
      firstByte: 160,
      download: 2,
      total: 390
    }
  }
}
[7/4/2022, 1:34:47 PM] [Ring] Request to https://api.ring.com/clients_api/doorbots/4766643/ failed with status 422. Response body: 
[7/4/2022, 1:34:47 PM] [Ring] HTTPError: Response code 422 (Unprocessable Entity)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1656966887577,
    socket: 1656966887578,
    lookup: 1656966887578,
    connect: 1656966887583,
    secureConnect: 1656966887796,
    upload: 1656966887797,
    response: 1656966887945,
    end: 1656966887946,
    error: undefined,
    abort: 1656966887948,
    phases: {
      wait: 1,
      dns: 0,
      tcp: 5,
      tls: 213,
      request: 1,
      firstByte: 148,
      download: 1,
      total: 371
    }
  }
}

<img width="1194" alt="Screen Shot 2022-07-04 at 1 35 03 PM" src="https://user-images.githubusercontent.com/25782222/177214088-853ee046-3bf5-482b-adac-02de7e1b65a3.png">

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
homebridge-ring v11.0.6

homebridge 1.5.0
Homebridge UI
homebridge-config-ui-x v4.48.1

        {
            "refreshToken": ""
            "hideDoorbellSwitch": false,
            "hideUnsupportedServices": true,
            "nightModeBypassFor": "some",
            "platform": "Ring"
        },

### Environment

 - OS: [Raspbian]
 - Node.js: [e.g. 12.14.1]   v16.15.0
 - NPM: [e.g 6.13.4] .8.5.5
 - homebridge-ring: [11.0.6]
 - homebridge: [e1.5.0]
 - hoobs: [N/A]

**Comment by dgreif** [comment]
Are you still experiencing this issue? I'm unable to recreate this problem
